# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 14-Q · Mock Exam — Databricks Certified Data Engineer Associate (120 questions)
# MAGIC A bank of **120 exam-style questions** following the **May 2026 exam guide** and its domain mix:
# MAGIC
# MAGIC | Domain | Questions in the bank | In each 45-question simulation |
# MAGIC |---|---|---|
# MAGIC | D1 Databricks Intelligence Platform | 8 | 3 |
# MAGIC | D2 Data Ingestion and Loading | 25 | 9 |
# MAGIC | D3 Data Transformation and Modeling | 26 | 10 |
# MAGIC | D4 Working with Lakeflow Jobs | 19 | 7 |
# MAGIC | D5 Implementing CI/CD | 12 | 5 |
# MAGIC | D6 Troubleshooting, Monitoring and Optimization | 12 | 4 |
# MAGIC | D7 Governance and Security | 18 | 7 |
# MAGIC
# MAGIC **Two ways to use it**
# MAGIC 1. **⏱️ Exam simulation** — 45 questions drawn with the real domain mix, **90-minute countdown**, no feedback until you
# MAGIC    click **Submit exam**. Change the `exam_seed` widget (1, 2, 3 …) to get a different exam. Ready signal: **≥ 80 %**
# MAGIC    in three different simulations.
# MAGIC 2. **📚 Practice** — all 120 (or one domain) with instant feedback and explanations.
# MAGIC
# MAGIC Multi-answer questions say *Choose TWO/THREE*. Collapse the question-bank cell — it contains the answers.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- D1 Platform ----------------
    {"topic": "D1 Platform",
     "q": "Which of these runs in the Databricks **control plane**?",
     "options": ["The web application, notebooks service and job scheduler",
                 "The worker VMs of a classic all-purpose cluster",
                 "The cloud object storage that holds your Delta tables",
                 "The Spark executors that process your data"],
     "answer": 0,
     "explanation": "The control plane (in the Databricks account) hosts the web app, notebooks, job scheduler, cluster manager and Unity Catalog metadata. Classic compute runs in your cloud account (compute plane) and the data stays in your own storage."},
    {"topic": "D1 Platform",
     "q": "A team wants notebooks that start in seconds, scale automatically and require **no infrastructure management**, for Python and SQL work. What should they use?",
     "options": ["An all-purpose cluster attached to an instance pool",
                 "Serverless compute for notebooks",
                 "A classic SQL warehouse",
                 "A single-node all-purpose cluster with auto-termination"],
     "answer": 1,
     "explanation": "Serverless compute is managed by Databricks, starts in seconds and auto-scales. Pools reduce classic start time but you still manage the cluster; a SQL warehouse runs SQL only."},
    {"topic": "D1 Platform",
     "q": "A nightly production ETL job must run on **classic** compute at the lowest cost. Which compute should it use?",
     "options": ["A pro SQL warehouse",
                 "A shared all-purpose cluster that the analysts also use",
                 "Jobs compute created for the run and terminated afterwards",
                 "An all-purpose cluster with auto-termination disabled"],
     "answer": 2,
     "explanation": "Jobs compute has a lower DBU rate than all-purpose compute and exists only for the run. Running scheduled jobs on all-purpose clusters is a classic cost mistake."},
    {"topic": "D1 Platform",
     "q": "What gives Delta Lake its **ACID** guarantees?",
     "options": ["The Photon engine",
                 "The Parquet file format",
                 "Unity Catalog permissions",
                 "The transaction log (`_delta_log`) of ordered, atomic commits"],
     "answer": 3,
     "explanation": "Every write is an atomic commit (a JSON file) in the _delta_log; readers see a consistent snapshot. Parquet alone has no transactions; Photon is a query engine."},
    {"topic": "D1 Platform",
     "q": "Which ordering of the Unity Catalog object hierarchy is correct?",
     "options": ["Metastore → catalog → schema → table / view / volume / function",
                 "Workspace → catalog → table → schema",
                 "Catalog → metastore → schema → table",
                 "Schema → catalog → table → volume"],
     "answer": 0,
     "explanation": "A metastore (one per region) contains catalogs, catalogs contain schemas, schemas contain tables, views, volumes, functions and models: catalog.schema.object."},
    {"topic": "D1 Platform",
     "q": "Which statements about **spot instances** on classic compute are true? (Choose TWO)",
     "options": ["They are best used for worker nodes, keeping the driver on-demand",
                 "They cost less than on-demand instances but can be reclaimed by the cloud provider",
                 "They guarantee the job finishes faster",
                 "They are the only instance type allowed for jobs compute"],
     "answer": [0, 1],
     "explanation": "Spot capacity is cheap but can be taken back; losing a worker is recoverable, losing the driver kills the job — so keep the driver on-demand."},
    {"topic": "D1 Platform",
     "q": "What is **Photon**?",
     "options": ["A streaming source for IoT devices",
                 "A file format that replaces Parquet",
                 "A vectorized native query engine that speeds up SQL and DataFrame workloads",
                 "The Databricks machine-learning library"],
     "answer": 2,
     "explanation": "Photon is Databricks' C++ vectorized engine, compatible with Spark APIs; it accelerates SQL/DataFrame operations (scans, joins, aggregations)."},
    {"topic": "D1 Platform",
     "q": "A CSV file must be stored so that notebooks can read it **and** access is governed by Unity Catalog. Where should it go?",
     "options": ["The local disk of the driver, `/tmp/`",
                 "`/FileStore/` in the DBFS root",
                 "A DBFS mount under `/mnt/`",
                 "A Unity Catalog volume, e.g. `/Volumes/main/raw/files/`"],
     "answer": 3,
     "explanation": "Volumes are Unity Catalog objects for files, with READ/WRITE VOLUME privileges. The DBFS root and mounts are legacy and not governed by UC; /tmp is lost when the compute stops."},
    # ---------------- D2 Ingestion ----------------
    {"topic": "D2 Ingestion",
     "q": "Millions of JSON files per day land in cloud storage, and new fields are added from time to time. The team wants **incremental** ingestion into Delta with the least custom code. What should they use?",
     "options": ["Auto Loader (`cloudFiles`) with a schema location",
                 "A daily `CREATE OR REPLACE TABLE … AS SELECT * FROM read_files(…)`",
                 "`spark.read.json()` on the whole folder with `mode(\"append\")`",
                 "`INSERT INTO … SELECT * FROM json.`path``"],
     "answer": 0,
     "explanation": "Auto Loader discovers only new files, scales to millions of files, and infers and evolves the schema (schemaLocation). The other options reprocess everything or create duplicates."},
    {"topic": "D2 Ingestion",
     "q": "A SQL analyst loads about 30 new CSV files per day from a volume and must be able to **re-run the load safely** without creating duplicates. Simplest solution?",
     "options": ["`INSERT INTO target SELECT * FROM read_files(…)`",
                 "`COPY INTO` the target table from the folder",
                 "A Python notebook with `spark.read.csv(...).write.mode(\"append\")`",
                 "A view over `read_files(…)`"],
     "answer": 1,
     "explanation": "COPY INTO is a SQL command that tracks which files were already loaded and skips them — idempotent. INSERT INTO and append reload every file each time."},
    {"topic": "D2 Ingestion",
     "q": "The statement below ran successfully. It is run **again** without any new file in the folder. What happens?",
     "code": "COPY INTO bronze.instructors\nFROM '/Volumes/skillwave/landing/raw/instructors/'\nFILEFORMAT = CSV\nFORMAT_OPTIONS ('header' = 'true', 'inferSchema' = 'true')",
     "options": ["All rows are loaded a second time",
                 "The statement fails because the table is not empty",
                 "Nothing is loaded — the files were already loaded",
                 "The table is truncated and reloaded"],
     "answer": 2,
     "explanation": "COPY INTO remembers loaded files in the table's metadata; re-running it only loads new files (num_affected_rows = 0 here)."},
    {"topic": "D2 Ingestion",
     "q": "A file loaded by `COPY INTO` was corrected and must be **loaded again**. Which option forces it?",
     "options": ["`FORMAT_OPTIONS ('mergeSchema' = 'true')`",
                 "`FILEFORMAT = DELTA`",
                 "`VALIDATE ALL`",
                 "`COPY_OPTIONS ('force' = 'true')`"],
     "answer": 3,
     "explanation": "'force' = 'true' disables idempotency and loads the selected files regardless of whether they were loaded before. VALIDATE only previews."},
    {"topic": "D2 Ingestion",
     "q": "With default options, Auto Loader ingests JSON files and **every column is a STRING** in the table. Why?",
     "options": ["For JSON/CSV Auto Loader infers columns as strings unless `cloudFiles.inferColumnTypes` is true",
                 "Delta tables convert numbers to strings",
                 "JSON can't store numbers",
                 "The schema location is corrupted"],
     "answer": 0,
     "explanation": "To avoid type mismatches across files, Auto Loader infers JSON, CSV and XML columns as STRING by default. Set cloudFiles.inferColumnTypes = true or use schemaHints."},
    {"topic": "D2 Ingestion",
     "q": "An Auto Loader stream with default schema-evolution settings stops with an `UnknownFieldException` after a new field appears in the files. What should you do?",
     "options": ["Delete the checkpoint and reprocess everything",
                 "Restart the stream — the schema has already been updated and the new column will be added",
                 "Switch to `COPY INTO`",
                 "Nothing can be done; the new field is lost"],
     "answer": 1,
     "explanation": "The default mode addNewColumns updates the schema in the schema location and fails the stream once. Restarting (e.g. with job retries) continues with the new column; the sink needs mergeSchema."},
    {"topic": "D2 Ingestion",
     "q": "An Auto Loader stream must **never stop** because of schema changes; unexpected new fields should be kept but the table schema must stay fixed. Which setting?",
     "options": ["`cloudFiles.schemaEvolutionMode = addNewColumns`",
                 "`cloudFiles.schemaEvolutionMode = failOnNewColumns`",
                 "`cloudFiles.schemaEvolutionMode = rescue`",
                 "`cloudFiles.inferColumnTypes = false`"],
     "answer": 2,
     "explanation": "rescue never evolves the schema and never fails: data that doesn't fit lands in the _rescued_data column."},
    {"topic": "D2 Ingestion",
     "q": "Which option does Auto Loader need to **infer and track** the schema of the incoming files across runs?",
     "options": ["`cloudFiles.includeExistingFiles`",
                 "`cloudFiles.maxFilesPerTrigger`",
                 "`cloudFiles.useNotifications`",
                 "`cloudFiles.schemaLocation`"],
     "answer": 3,
     "explanation": "The schema location stores the inferred schema and its versions; it's required for inference and evolution (often a subfolder of the checkpoint)."},
    {"topic": "D2 Ingestion",
     "q": "What does `.trigger(availableNow=True)` do in a Structured Streaming query?",
     "options": ["Processes all data available at start, possibly in several micro-batches, then stops",
                 "Runs a micro-batch every second forever",
                 "Processes only the newest file",
                 "Processes one record and stops"],
     "answer": 0,
     "explanation": "availableNow gives incremental batch processing: consume everything new (respecting rate limits like maxFilesPerTrigger), then stop — ideal for scheduled jobs."},
    {"topic": "D2 Ingestion",
     "q": "This query returns columns `_c0, _c1, …` and the header line appears as a data row. What is the simplest fix?",
     "code": "SELECT * FROM csv.`/Volumes/main/raw/courses/`",
     "options": ["Add `LIMIT 1 OFFSET 1`",
                 "Use `read_files('/Volumes/main/raw/courses/', format => 'csv', header => true)`",
                 "Convert the file to JSON first",
                 "Use `json.` instead of `csv.`"],
     "answer": 1,
     "explanation": "The csv.`path` shortcut can't take options. read_files (or a temp view with OPTIONS) lets you set header, sep, schema hints, etc."},
    {"topic": "D2 Ingestion",
     "q": "On Unity Catalog compute, how do you record **which file** each ingested row came from?",
     "options": ["`input_file_name`",
                 "`current_file()`",
                 "`_metadata.file_path` (or `_metadata.file_name`)",
                 "`spark.sparkContext.files`"],
     "answer": 2,
     "explanation": "The hidden _metadata column (file_path, file_name, file_size, file_modification_time) is the supported way; input_file_name is not supported on UC shared/serverless compute."},
    {"topic": "D2 Ingestion",
     "q": "The company wants to ingest **Salesforce** objects incrementally into Unity Catalog with minimal code and no infrastructure to maintain. What should the engineer configure?",
     "options": ["A custom Python notebook that calls the Salesforce REST API",
                 "A JDBC external table pointing to Salesforce",
                 "Auto Loader on the Salesforce web URL",
                 "A Lakeflow Connect managed connector for Salesforce"],
     "answer": 3,
     "explanation": "Lakeflow Connect managed connectors (Salesforce, Workday, ServiceNow, Google Analytics…) create a connection and a serverless ingestion pipeline that writes streaming tables incrementally."},
    {"topic": "D2 Ingestion",
     "q": "With Lakeflow Connect, which component extracts snapshots and change data from an **on-premises SQL Server** database?",
     "options": ["The ingestion gateway",
                 "A SQL warehouse",
                 "The Databricks CLI",
                 "A file arrival trigger"],
     "answer": 0,
     "explanation": "Database connectors use an ingestion gateway (running on classic compute with network access to the source) to capture snapshots and CDC into staging; the ingestion pipeline then applies them to streaming tables."},
    {"topic": "D2 Ingestion",
     "q": "A dashboard needs data at most **one hour old**, and cost matters more than seconds of latency. Which loading pattern fits best?",
     "options": ["Continuous streaming with a 500 ms trigger",
                 "Incremental batch: an hourly job running Auto Loader with `availableNow`",
                 "A full reload of all history every hour",
                 "Manual uploads by an analyst"],
     "answer": 1,
     "explanation": "Incremental batch processes only new data on a schedule and lets compute shut down between runs — far cheaper than an always-on stream, and fresher than daily."},
    {"topic": "D2 Ingestion",
     "q": "Which statements comparing COPY INTO and Auto Loader are correct? (Choose TWO)",
     "options": ["Auto Loader scales better to millions of files and supports schema evolution",
                 "COPY INTO requires a streaming checkpoint location",
                 "COPY INTO is an idempotent SQL command, well suited to thousands of files",
                 "Auto Loader can only run as an always-on continuous stream"],
     "answer": [0, 2],
     "explanation": "COPY INTO tracks loaded files in the table (no checkpoint needed). Auto Loader is a streaming source that can run continuously or as incremental batch (availableNow)."},
    {"topic": "D2 Ingestion",
     "q": "Analysts use **Power BI** and want to query gold tables in Databricks. What is the standard way to connect?",
     "options": ["Mount the Delta files in Power BI",
                 "Export CSV files every night",
                 "Use `dbutils.fs` from Power BI",
                 "Connect Power BI to a SQL warehouse through its connector (JDBC/ODBC)"],
     "answer": 3,
     "explanation": "BI tools connect to a SQL warehouse (server hostname + HTTP path) with the Databricks connector or JDBC/ODBC drivers; Unity Catalog permissions still apply."},
    {"topic": "D2 Ingestion",
     "q": "A small web application must run SQL statements against Databricks **over HTTPS without installing a JDBC/ODBC driver**. What should it use?",
     "options": ["The SQL Statement Execution REST API against a SQL warehouse",
                 "The Spark UI",
                 "Delta Sharing",
                 "A file arrival trigger"],
     "answer": 0,
     "explanation": "The Statement Execution API runs SQL on a warehouse via REST and returns results (inline or as links) — no driver needed."},
    {"topic": "D2 Ingestion",
     "q": "The column `profile` is a **JSON string** like `{\"address\": {\"city\": \"Riyadh\"}}`. Which SQL returns the city?",
     "options": ["`SELECT profile.address.city FROM customers`",
                 "`SELECT profile:address:city FROM customers`",
                 "`SELECT profile['address']['city'] FROM customers`",
                 "`SELECT explode(profile) FROM customers`"],
     "answer": 1,
     "explanation": "The colon syntax extracts fields from JSON strings (and VARIANT). Dot notation only works on STRUCT columns, e.g. after from_json."},
    {"topic": "D2 Ingestion",
     "q": "Why would you write `from_json(profile, schema_of_json('<sample>'))`?",
     "options": ["To convert a STRUCT back into a string",
                 "To compress the JSON",
                 "To convert the JSON string into a typed STRUCT once, so fields can be used with dot notation",
                 "To validate that the column is not NULL"],
     "answer": 2,
     "explanation": "from_json parses a JSON string into a struct given a schema; schema_of_json derives that schema from an example. to_json does the reverse."},
    {"topic": "D2 Ingestion",
     "q": "Scanned PDFs and product images must be ingested for later AI processing, with Unity Catalog governance. What is the recommended approach?",
     "options": ["Put them in the DBFS root",
                 "Convert them to JSON with a Python UDF first",
                 "Store them as base64 strings in a CSV",
                 "Store the files in a volume and read them with the `binaryFile` format"],
     "answer": 3,
     "explanation": "Unstructured files live in UC volumes; binaryFile (path, modificationTime, length, content) or read_files(format => 'binaryFile') brings them into tables."},
    {"topic": "D2 Ingestion",
     "q": "What is the main advantage of the **VARIANT** type for semi-structured data?",
     "options": ["It stores JSON-like data in an efficient binary form and allows path queries without a fixed schema",
                 "It makes JSON data immutable",
                 "It enforces a strict schema on write",
                 "It can only store arrays"],
     "answer": 0,
     "explanation": "VARIANT handles changing structures flexibly and is faster to query than JSON strings (parse_json, v:path::type)."},
    {"topic": "D2 Ingestion",
     "q": "What is the purpose of the **checkpoint location** of a streaming query?",
     "options": ["It stores a backup copy of the output table",
                 "It stores the query's progress (offsets, committed batches, state) so it can restart exactly where it stopped",
                 "It can be shared by all streams writing to the same table",
                 "It is only needed for the console sink"],
     "answer": 1,
     "explanation": "The checkpoint (write-ahead log + commit log + state) enables fault tolerance and exactly-once with an idempotent sink. Each query needs its own checkpoint."},
    {"topic": "D2 Ingestion",
     "q": "A daily job runs `CREATE OR REPLACE TABLE bronze.events AS SELECT * FROM read_files('/Volumes/main/raw/events/')`. The folder grows by one file per day. What is the problem?",
     "options": ["read_files can't read JSON",
                 "CREATE OR REPLACE loses the table history",
                 "Every run re-reads **all** files, so it gets slower and costlier every day",
                 "The job reads only the newest file"],
     "answer": 2,
     "explanation": "CTAS over read_files is a full batch read each time. For growing folders use incremental ingestion: Auto Loader, a streaming table (STREAM read_files) or COPY INTO. (CREATE OR REPLACE keeps history.)"},
    {"topic": "D2 Ingestion",
     "q": "A Structured Streaming query reads a Kafka topic. The `value` column appears as binary. What do you do to read the JSON payload?",
     "code": "df = (spark.readStream.format(\"kafka\")\n      .option(\"kafka.bootstrap.servers\", \"broker:9092\")\n      .option(\"subscribe\", \"enrollments\")\n      .load())",
     "options": ["Use `.option(\"valueFormat\", \"json\")`",
                 "Kafka values can't be read in Databricks",
                 "Use `explode(value)`",
                 "Cast `value` to STRING and parse it with `from_json`"],
     "answer": 3,
     "explanation": "Kafka key/value are binary: `from_json(col(\"value\").cast(\"string\"), schema)` turns the payload into columns."},
    {"topic": "D2 Ingestion",
     "q": "A stream-static join enriches a stream of orders with a static Delta table of products. Which product data does each micro-batch use?",
     "options": ["The latest version of the products table at the time the micro-batch runs",
                 "A random snapshot",
                 "The version of the products table from when the stream started",
                 "Only products inserted after the stream started"],
     "answer": 0,
     "explanation": "In a stream-static join the static Delta side is re-read at its latest version for each micro-batch; only the streaming side drives incremental processing."},
    # ---------------- D3 Transformation ----------------
    {"topic": "D3 Transformation",
     "q": "`df.dropDuplicates([\"customer_id\"])` is applied to a table with several rows per customer. Which row is kept for each customer?",
     "options": ["All rows are kept",
                 "One arbitrary row per customer",
                 "The most recent row",
                 "The first row in file order, always"],
     "answer": 1,
     "explanation": "dropDuplicates keeps one row per key without any guaranteed order. To keep the latest, use row_number() over a window ordered by the timestamp."},
    {"topic": "D3 Transformation",
     "q": "Which query keeps only the **latest** record per `customer_id` (by `updated_at`)?",
     "options": ["`SELECT customer_id, max(updated_at) FROM t`",
                 "`SELECT DISTINCT customer_id, updated_at FROM t`",
                 "`SELECT * FROM t QUALIFY row_number() OVER (PARTITION BY customer_id ORDER BY updated_at DESC) = 1`",
                 "`SELECT * FROM t ORDER BY updated_at DESC LIMIT 1`"],
     "answer": 2,
     "explanation": "row_number per customer ordered by updated_at DESC, keeping 1, returns the full latest row for every customer. Option A has no GROUP BY (and loses the other columns); B returns every customer/timestamp pair; D returns one row overall."},
    {"topic": "D3 Transformation",
     "q": "`df_a` has columns (id, name, city) and `df_b` has the same columns in the order (id, city, name). What does `df_a.union(df_b)` do?",
     "options": ["Matches columns by name automatically",
                 "Raises an error",
                 "Removes duplicate rows",
                 "Appends rows by position, so names and cities from df_b end up in the wrong columns"],
     "answer": 3,
     "explanation": "union() resolves by position and keeps duplicates (like UNION ALL). Use unionByName() to match by column name."},
    {"topic": "D3 Transformation",
     "q": "What does a **LEFT ANTI JOIN** of `orders` with `customers` on `customer_id` return?",
     "options": ["Orders whose customer_id has no match in customers",
                 "Orders with a matching customer, with customer columns added",
                 "Customers without orders",
                 "Every combination of orders and customers"],
     "answer": 0,
     "explanation": "Anti join = rows of the left side WITHOUT a match (orphans), left columns only. LEFT SEMI returns the left rows WITH a match."},
    {"topic": "D3 Transformation",
     "q": "A table has 1,000 rows; 40 have a NULL `email`. What do `count(*)` and `count(email)` return?",
     "options": ["960 and 1,000",
                 "1,000 and 960",
                 "1,000 and 1,000",
                 "960 and 960"],
     "answer": 1,
     "explanation": "count(*) counts rows; count(column) ignores NULL values."},
    {"topic": "D3 Transformation",
     "q": "A table `sales` exists with 5 columns. A developer runs `INSERT OVERWRITE sales SELECT *, current_date() AS load_date FROM staging` (6 columns). What happens?",
     "options": ["The extra column is silently dropped",
                 "The new column is added and the data replaced",
                 "The statement fails because INSERT OVERWRITE can't change the table schema",
                 "The rows are appended"],
     "answer": 2,
     "explanation": "INSERT OVERWRITE replaces data but keeps the schema; a mismatching schema fails. CREATE OR REPLACE TABLE (or overwriteSchema in the DataFrame API) can change it."},
    {"topic": "D3 Transformation",
     "q": "A `MERGE INTO customers USING updates ON …` fails because **multiple source rows matched the same target row**. What is the correct fix?",
     "options": ["Disable the transaction log",
                 "Run the MERGE twice",
                 "Replace MERGE with INSERT INTO",
                 "Deduplicate the source so there is at most one row per key (e.g. the latest per key)"],
     "answer": 3,
     "explanation": "MERGE requires an unambiguous match. Reduce the source to one row per key (row_number / latest by timestamp) before merging."},
    {"topic": "D3 Transformation",
     "q": "Which statement implements a **slowly changing dimension type 1** for `dim_customer` from `customer_updates`?",
     "options": ["`MERGE INTO dim_customer t USING customer_updates s ON t.id = s.id WHEN MATCHED THEN UPDATE SET * WHEN NOT MATCHED THEN INSERT *`",
                 "`CREATE VIEW dim_customer AS SELECT * FROM customer_updates`",
                 "`INSERT INTO dim_customer SELECT * FROM customer_updates`",
                 "`DELETE FROM dim_customer`"],
     "answer": 0,
     "explanation": "SCD 1 overwrites attributes in place (upsert) and keeps no history. SCD 2 would insert new versions with validity columns."},
    {"topic": "D3 Transformation",
     "q": "Which of these are **lazy transformations** (they don't start a Spark job by themselves)? (Choose TWO)",
     "options": ["`df.write.saveAsTable(\"t\")`",
                 "`df.filter(\"price > 0\")`",
                 "`df.select(\"id\", \"price\")`",
                 "`df.count()`"],
     "answer": [1, 2],
     "explanation": "Transformations (select, filter, join, groupBy…) build the plan; actions (count, show, collect, write) execute it."},
    {"topic": "D3 Transformation",
     "q": "Some customers have an **empty** `interests` array. You need one row per interest **and** keep customers without interests (with NULL). Which function?",
     "options": ["`collect_list(interests)`",
                 "`explode(interests)`",
                 "`explode_outer(interests)`",
                 "`flatten(interests)`"],
     "answer": 2,
     "explanation": "explode drops rows whose array is NULL or empty; explode_outer keeps them with a NULL element."},
    {"topic": "D3 Transformation",
     "q": "`items` is an ARRAY<STRUCT<product_id STRING, quantity INT>>. Which expression keeps only items with quantity greater than 1, **without exploding**?",
     "options": ["`TRANSFORM(items, i -> i.quantity > 1)`",
                 "`WHERE items.quantity > 1`",
                 "`EXISTS(items, i -> i.quantity > 1)`",
                 "`FILTER(items, i -> i.quantity > 1)`"],
     "answer": 3,
     "explanation": "FILTER returns the array elements matching the lambda. TRANSFORM maps each element (here to booleans); EXISTS returns a single boolean."},
    {"topic": "D3 Transformation",
     "q": "Three courses have revenues 900, 900 and 700. What do `rank()` and `dense_rank()` (ordered by revenue DESC) return?",
     "options": ["rank 1, 1, 3 · dense_rank 1, 1, 2",
                 "rank 1, 2, 3 · dense_rank 1, 1, 2",
                 "both 1, 2, 3",
                 "rank 1, 1, 2 · dense_rank 1, 1, 3"],
     "answer": 0,
     "explanation": "rank leaves gaps after ties (1,1,3); dense_rank doesn't (1,1,2); row_number always gives 1,2,3."},
    {"topic": "D3 Transformation",
     "q": "You need one row per category with one **column per channel** (web, mobile, partner) containing revenue. Which SQL feature?",
     "options": ["UNPIVOT",
                 "PIVOT (sum(revenue) FOR channel IN ('web', 'mobile', 'partner'))",
                 "LATERAL VIEW",
                 "GROUPING SETS"],
     "answer": 1,
     "explanation": "PIVOT turns values of a column into columns with an aggregate; UNPIVOT does the reverse."},
    {"topic": "D3 Transformation",
     "q": "A 2 TB fact table is joined to a 5 MB country table. The plan shows a large shuffle of the fact table. What is the best improvement?",
     "options": ["Increase the number of shuffle partitions to 10,000",
                 "Repartition the fact table by country before the join",
                 "Broadcast the small table (broadcast hint / let it fall under `autoBroadcastJoinThreshold`)",
                 "Convert the country table to CSV"],
     "answer": 2,
     "explanation": "A broadcast hash join copies the small table to every executor, so the large side is not shuffled."},
    {"topic": "D3 Transformation",
     "q": "What does `spark.sql.shuffle.partitions` control?",
     "options": ["The number of files read per task",
                 "The number of executors",
                 "The maximum size of a broadcast table",
                 "The number of partitions produced by wide transformations (joins, aggregations) after a shuffle"],
     "answer": 3,
     "explanation": "It sets how many partitions a shuffle creates (default 200 on classic; AQE can coalesce them; serverless uses 'auto'). Broadcast size is spark.sql.autoBroadcastJoinThreshold; read split size is spark.sql.files.maxPartitionBytes."},
    {"topic": "D3 Transformation",
     "q": "After changing a tuning parameter, how should you **measure** whether a transformation got faster?",
     "options": ["Compare the duration and metrics of comparable runs in the query profile / Spark UI (same data, warm-up considered)",
                 "Look at the table's DESCRIBE HISTORY",
                 "Run `df.count()` once and trust the result",
                 "Check the number of notebook cells"],
     "answer": 0,
     "explanation": "Measure with real metrics (duration, shuffle bytes, spill, task skew) for equivalent runs. A single count() may trigger a different, cheaper plan."},
    {"topic": "D3 Transformation",
     "q": "A gold aggregation is read **hundreds of times per day** by a dashboard and its sources change once a day. Which object is the best fit?",
     "options": ["A standard view",
                 "A materialized view refreshed after the daily load",
                 "A temporary view",
                 "A global temporary view"],
     "answer": 1,
     "explanation": "A materialized view stores the result and is refreshed (incrementally when possible) — reads are cheap. A view recomputes on every read; temp views are session-scoped."},
    {"topic": "D3 Transformation",
     "q": "Which gold object type processes each new input row **once** and is meant for append-only sources?",
     "options": ["Materialized view",
                 "Standard view",
                 "Streaming table",
                 "Temporary view"],
     "answer": 2,
     "explanation": "Streaming tables process data incrementally (each input row once). Materialized views recompute results (incrementally when possible) and support any query shape."},
    {"topic": "D3 Transformation",
     "q": "In a declarative pipeline: `CONSTRAINT valid_price EXPECT (price >= 0) ON VIOLATION DROP ROW`. What happens to rows with a negative price?",
     "options": ["The pipeline update fails",
                 "They are written to the target and a warning is logged",
                 "They are moved to a quarantine table automatically",
                 "They are removed from the target and counted in the data-quality metrics"],
     "answer": 3,
     "explanation": "DROP ROW drops violating rows and records the counts in the event log. FAIL UPDATE stops the update; without ON VIOLATION the row is kept (warn). Quarantine tables must be built yourself."},
    {"topic": "D3 Transformation",
     "q": "An expectation is declared **without** an `ON VIOLATION` clause. What is the behaviour?",
     "options": ["Violating rows are kept; the violations are counted in the pipeline metrics",
                 "The update fails at the first violation",
                 "The expectation is ignored",
                 "Violating rows are dropped"],
     "answer": 0,
     "explanation": "The default action is warn: records are written and the number of failing records is reported."},
    {"topic": "D3 Transformation",
     "q": "`ALTER TABLE orders ADD CONSTRAINT positive CHECK (amount > 0)` succeeded. Later an `INSERT` contains 1,000 rows, 3 of them with negative amounts. What happens?",
     "options": ["997 rows are inserted, 3 are skipped",
                 "The whole INSERT fails and no row is written",
                 "All rows are inserted; the constraint is informational",
                 "The 3 rows are inserted with amount set to NULL"],
     "answer": 1,
     "explanation": "Delta CHECK constraints are enforced; a violating transaction fails atomically. (PRIMARY/FOREIGN KEY constraints are the informational ones.)"},
    {"topic": "D3 Transformation",
     "q": "Why are built-in functions usually preferred over **Python UDFs** for transformations?",
     "options": ["Built-in functions are always written in Python",
                 "Python UDFs can't return strings",
                 "Built-ins are optimized by Catalyst/Photon, while Python UDFs serialize rows to a Python process and are opaque to the optimizer",
                 "Python UDFs only work on serverless"],
     "answer": 2,
     "explanation": "Python UDFs add serialization overhead and block optimizations. Use built-ins, SQL UDFs, or vectorized pandas UDFs when Python is unavoidable."},
    {"topic": "D3 Transformation",
     "q": "What is the **default save mode** of `df.write.saveAsTable(\"sales\")` when the table already exists?",
     "options": ["ignore",
                 "append",
                 "overwrite",
                 "errorifexists — the write fails"],
     "answer": 3,
     "explanation": "The default mode is errorifexists (error). Use .mode(\"append\"), \"overwrite\" or \"ignore\" explicitly."},
    {"topic": "D3 Transformation",
     "q": "Which statements about views are true? (Choose TWO)",
     "options": ["A standard view stores a copy of the data",
                 "A temporary view exists only in the current Spark session",
                 "A standard view runs its query each time it is read",
                 "A materialized view is always up to date without any refresh"],
     "answer": [1, 2],
     "explanation": "Views store only the query; temp views are session-scoped. Materialized views store results and are as fresh as their last refresh."},
    {"topic": "D3 Transformation",
     "q": "With ANSI mode enabled, `CAST('12.5 EUR' AS DOUBLE)` raises an error during cleaning. You want invalid values to become NULL instead. What do you use?",
     "options": ["`CAST(... AS STRING)`",
                 "`try_cast('12.5 EUR' AS DOUBLE)`",
                 "`coalesce(CAST(...), 0)`",
                 "`nvl(CAST(...))`"],
     "answer": 1,
     "explanation": "try_cast returns NULL when the conversion fails; coalesce wouldn't help because the CAST itself fails first."},
    {"topic": "D3 Transformation",
     "q": "Duplicate events may be re-delivered in later files. Which write pattern guarantees each `event_id` is stored **once** in silver, even if a load is re-run?",
     "options": ["`INSERT INTO silver SELECT DISTINCT * FROM bronze`",
                 "`df.write.mode(\"append\").saveAsTable(\"silver\")`",
                 "An insert-only MERGE: `MERGE INTO silver t USING new s ON t.event_id = s.event_id WHEN NOT MATCHED THEN INSERT *`",
                 "`CREATE TABLE silver AS SELECT * FROM bronze` each time"],
     "answer": 2,
     "explanation": "The insert-only MERGE skips keys that already exist, so re-processing is idempotent. DISTINCT only removes duplicates inside the current batch."},
    # ---------------- D4 Lakeflow Jobs ----------------
    {"topic": "D4 Lakeflow Jobs",
     "q": "A `notify_team` task must run **only when** at least one of its upstream tasks failed. Which *Run if* condition?",
     "options": ["All succeeded",
                 "All done",
                 "None failed",
                 "At least one failed"],
     "answer": 3,
     "explanation": "At least one failed runs the task when any dependency failed — typical for alerting/rollback tasks."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A `cleanup` task must **always** run after its upstream tasks finish, whether they succeeded or failed. Which *Run if* condition?",
     "options": ["All done",
                 "At least one succeeded",
                 "All succeeded",
                 "All failed"],
     "answer": 0,
     "explanation": "All done runs once every dependency has finished, regardless of the outcome."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "Task `quality_check` sets a task value `bad_rows`. An **If/else condition** task must compare it with 10. Which left operand do you write?",
     "options": ["`${quality_check.bad_rows}`",
                 "`{{tasks.quality_check.values.bad_rows}}`",
                 "`{{job.parameters.bad_rows}}`",
                 "`dbutils.jobs.taskValues.get(\"bad_rows\")`"],
     "answer": 1,
     "explanation": "Dynamic value references use {{tasks.<task_key>.values.<key>}} for task values; numeric operators (>, >=, <, <=) compare numbers."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "How does a notebook task pass a small computed value (e.g. a row count) to a **downstream** task?",
     "options": ["`print()` the value and read the logs",
                 "A global temporary view",
                 "`dbutils.jobs.taskValues.set(key=\"rows\", value=n)` upstream and `dbutils.jobs.taskValues.get(taskKey=\"load\", key=\"rows\")` downstream",
                 "Write it to the driver's /tmp folder"],
     "answer": 2,
     "explanation": "Task values are the supported mechanism for small JSON-serializable values between tasks (and for If/else conditions)."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "The same notebook must run once **for each country** in a list produced by an upstream task, with at most 3 runs in parallel. What should you use?",
     "options": ["Three copies of the notebook task",
                 "A continuous trigger",
                 "A while loop with `dbutils.notebook.run` on the driver",
                 "A For each task with the list as input, `{{input}}` as parameter and concurrency 3"],
     "answer": 3,
     "explanation": "For each iterates a nested task over a JSON array (job parameter, task value or literal); {{input}} is the current element; concurrency limits parallel iterations."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "What is the **default concurrency** of a For each task?",
     "options": ["1 (iterations run one after another)",
                 "Equal to the number of inputs",
                 "10",
                 "Unlimited"],
     "answer": 0,
     "explanation": "By default iterations run sequentially; raise the concurrency to run them in parallel."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A task calls an external API that sometimes fails with transient timeouts. What is the simplest way to make the job resilient?",
     "options": ["Duplicate the task",
                 "Configure retries on that task (number of retries and minimum interval)",
                 "Set the job to continuous",
                 "Increase the cluster size"],
     "answer": 1,
     "explanation": "Task-level retries re-run a failed task automatically; {{task.execution_count}} tells the notebook which attempt it is."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "In a 6-task job, task 4 failed; tasks 5 and 6 depend on it and were skipped. After fixing the bug you click **Repair run**. What runs?",
     "options": ["Only task 4",
                 "Tasks 1–3 only",
                 "Task 4 and its dependent tasks 5 and 6 — the successful tasks 1–3 are not re-run",
                 "All 6 tasks from the beginning"],
     "answer": 2,
     "explanation": "Repair re-runs failed and skipped tasks (plus dependents) within the same run, reusing the successful results. It uses the job's current settings."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A job must run **every day at 02:30 Riyadh time**. How do you configure it?",
     "options": ["A table update trigger",
                 "A file arrival trigger",
                 "A continuous trigger with a 24 h pause",
                 "A scheduled trigger with Quartz cron `0 30 2 * * ?` and time zone Asia/Riyadh"],
     "answer": 3,
     "explanation": "Schedules use Quartz cron syntax (seconds first, ? for day-of-week/day-of-month) plus a time zone."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "Partners upload files at **unpredictable times** into a Unity Catalog volume. The job should start soon after a new file arrives and not run when nothing arrives. Which trigger?",
     "options": ["A file arrival trigger on the volume path",
                 "A continuous trigger",
                 "A schedule every 5 minutes",
                 "Manual runs"],
     "answer": 0,
     "explanation": "File arrival triggers monitor a volume or external location and start a run when new files appear — data-driven, no idle runs."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A reporting job should run whenever the Unity Catalog table `silver.orders` receives new data. Which trigger fits best?",
     "options": ["File arrival trigger on the table's storage path",
                 "Table update trigger on `silver.orders`",
                 "A schedule every minute",
                 "Continuous trigger"],
     "answer": 1,
     "explanation": "Table update triggers fire when the monitored UC table(s) are updated (any or all of up to 10 tables)."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "When is a **time-based** trigger a better choice than a data-driven one?",
     "options": ["When you want to avoid runs without new data",
                 "When data arrives at random times and latency matters",
                 "When downstream consumers expect results at a fixed time (e.g. a report at 07:00) regardless of when data arrived",
                 "When the source is a table that updates continuously"],
     "answer": 2,
     "explanation": "Schedules fit fixed business deadlines and batch windows; data-driven triggers (file arrival, table update) fit irregular arrivals and avoid empty runs."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A job defines the job parameter `env = prod`. A notebook task also has a task parameter `env = dev`. Which value does the notebook see?",
     "options": ["Both, as a list",
                 "dev",
                 "Neither; the run fails",
                 "prod — job parameters are pushed down to tasks and take precedence over task parameters with the same key"],
     "answer": 3,
     "explanation": "Job-level parameters are passed to every task and override task parameters with the same name."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A notebook lands files; a **declarative pipeline** must then process them in the same job. How do you model it?",
     "options": ["A notebook task followed by a pipeline task that depends on it",
                 "Two separate jobs on schedules 5 minutes apart",
                 "A SQL task that runs the pipeline's SQL files",
                 "Call the pipeline's notebook with %run"],
     "answer": 0,
     "explanation": "The pipeline task triggers an update of an existing pipeline; the dependency guarantees the order."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "Which dynamic value reference passes the **run's start date** (e.g. `2026-10-03`) to a task parameter?",
     "options": ["`{{current_date}}`",
                 "`{{job.start_time.iso_date}}`",
                 "`{{task.name}}`",
                 "`${date}`"],
     "answer": 1,
     "explanation": "{{job.start_time.iso_date}} (and other job.start_time fields) are resolved at run time. {{task.name}} is the task key."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "An If/else task evaluates to **true**. A task attached to its **false** branch shows the status *Excluded*. What does that mean for the run?",
     "options": ["The task will run in the next scheduled run",
                 "The task was cancelled by a user",
                 "The task was not run because its branch wasn't taken; this does not make the run fail",
                 "The run fails"],
     "answer": 2,
     "explanation": "Excluded tasks are on the branch not taken; they count as successful for the run's result."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "A job has *Maximum concurrent runs = 1* and queueing enabled. The schedule fires while the previous run is still active. What happens?",
     "options": ["The schedule is disabled",
                 "Both runs execute in parallel",
                 "The running run is cancelled",
                 "The new run is queued and starts when the active run finishes"],
     "answer": 3,
     "explanation": "With max concurrent runs reached, queued runs wait (up to 48 h); without queueing the new run would be skipped."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "What does a **continuous** trigger do?",
     "options": ["Keeps exactly one run active: when a run ends, a new one starts (with back-off after failures)",
                 "Runs the job every minute",
                 "Runs the job only when files arrive",
                 "Runs the job once per day"],
     "answer": 0,
     "explanation": "Continuous jobs always have one active run — used for streaming workloads."},
    {"topic": "D4 Lakeflow Jobs",
     "q": "Which TWO task types are **control-flow** tasks in Lakeflow Jobs? (Choose TWO)",
     "options": ["For each",
                 "If/else condition",
                 "Notebook",
                 "Pipeline"],
     "answer": [0, 1],
     "explanation": "If/else (branching) and For each (looping) control the flow; notebook, pipeline, SQL, dbt, etc. do the work. Retries are task settings."},
    # ---------------- D5 CI/CD ----------------
    {"topic": "D5 CI/CD",
     "q": "In a Git folder, a developer wants to work on a new feature **without affecting `main`**. What should they do first?",
     "options": ["Disable Git integration",
                 "Clone the repository again into another folder",
                 "Create a new branch in the Git folder's Git dialog and switch to it",
                 "Export the notebooks as a DBC archive"],
     "answer": 2,
     "explanation": "Branches isolate work; the Git dialog lets you create/switch branches, commit, push and pull."},
    {"topic": "D5 CI/CD",
     "q": "After editing notebooks in a Git folder, how do the changes reach the remote repository?",
     "options": ["Through `dbutils.git.push()`",
                 "They are pushed automatically on save",
                 "By exporting a .zip",
                 "Select the changed files, write a commit message and **Commit & Push** in the Git dialog"],
     "answer": 3,
     "explanation": "Git folders commit and push from the UI (or via the Repos API/CLI); pull requests and reviews then happen in the Git provider."},
    {"topic": "D5 CI/CD",
     "q": "What is the name of the main configuration file of a Declarative Automation Bundle (formerly Databricks Asset Bundle)?",
     "options": ["`databricks.yml`",
                 "`bundle.json`",
                 "`pipeline.yml`",
                 "`databricks.cfg`"],
     "answer": 0,
     "explanation": "databricks.yml at the bundle root declares the bundle, variables, includes, resources and targets."},
    {"topic": "D5 CI/CD",
     "q": "Which command deploys a bundle's jobs and pipelines to the **prod** target?",
     "options": ["`databricks bundle run prod`",
                 "`databricks bundle deploy -t prod`",
                 "`databricks jobs create --prod`",
                 "`databricks workspace import prod`"],
     "answer": 1,
     "explanation": "bundle deploy uploads files and creates/updates the resources of the selected target (-t / --target). bundle run starts a deployed job or pipeline."},
    {"topic": "D5 CI/CD",
     "q": "Before deploying, a CI pipeline should check the bundle configuration for errors and resolve its variables. Which command?",
     "options": ["`databricks auth token`",
                 "`databricks bundle init`",
                 "`databricks bundle validate`",
                 "`databricks bundle destroy`"],
     "answer": 2,
     "explanation": "validate parses the configuration, resolves variables and reports errors without deploying."},
    {"topic": "D5 CI/CD",
     "q": "A bundle declares a variable `catalog`. How do you reference it inside a job definition in the bundle?",
     "options": ["`:catalog`",
                 "`{{catalog}}`",
                 "`$catalog`",
                 "`${var.catalog}`"],
     "answer": 3,
     "explanation": "Bundle variables are referenced with ${var.<name>}; other substitutions include ${bundle.target} and ${resources.jobs.<key>.id}."},
    {"topic": "D5 CI/CD",
     "q": "The `catalog` variable must be `sales_dev` in dev and `sales` in prod. Where is the prod value normally set?",
     "options": ["Under `targets: prod: variables: catalog: sales` in databricks.yml (the variable's `default` covers dev)",
                 "In a separate bundle per environment",
                 "In every notebook as a widget default",
                 "In the job's run-as settings"],
     "answer": 0,
     "explanation": "Targets override variable values; values can also come from --var on the CLI or BUNDLE_VAR_<name> environment variables."},
    {"topic": "D5 CI/CD",
     "q": "What does `mode: development` on a bundle target do? (Choose TWO)",
     "options": ["Runs everything as a service principal",
                 "Prefixes deployed resource names with `[dev <user>]` so each developer gets their own copy",
                 "Pauses schedules and triggers of deployed jobs",
                 "Deletes the production jobs"],
     "answer": [1, 2],
     "explanation": "Development mode isolates per-user deployments and pauses schedules/triggers. Production mode is meant for shared deployments, typically run as a service principal."},
    {"topic": "D5 CI/CD",
     "q": "How do you start a job that was deployed with a bundle, from the CLI?",
     "options": ["`databricks bundle deploy --run`",
                 "`databricks bundle start`",
                 "`databricks bundle run -t dev <job_resource_key>`",
                 "`databricks jobs submit databricks.yml`"],
     "answer": 2,
     "explanation": "bundle run takes the resource key from the bundle configuration (not the job ID) and the target."},
    {"topic": "D5 CI/CD",
     "q": "How should a CI system (e.g. GitHub Actions) authenticate to deploy bundles to production?",
     "options": ["With the workspace admin's password",
                 "With the personal access token of the team lead",
                 "No authentication is needed for bundles",
                 "With a service principal using OAuth (machine-to-machine)"],
     "answer": 3,
     "explanation": "Automation should use a service principal with OAuth M2M credentials stored as CI secrets — not a person's identity."},
    {"topic": "D5 CI/CD",
     "q": "A feature branch's test deployment is no longer needed. Which command removes all resources the bundle deployed to that target?",
     "options": ["`databricks bundle destroy -t test`",
                 "`databricks workspace delete /`",
                 "`databricks bundle validate -t test`",
                 "`git branch -d test`"],
     "answer": 0,
     "explanation": "bundle destroy deletes the jobs, pipelines and files deployed by the bundle for that target."},
    {"topic": "D5 CI/CD",
     "q": "Which actions can you perform directly in a Databricks **Git folder** UI? (Choose TWO)",
     "options": ["Resolve merge conflicts when merging/rebasing branches",
                 "Approve and merge a pull request in GitHub",
                 "Assign GitHub repository permissions",
                 "Pull the latest changes from the remote branch"],
     "answer": [0, 3],
     "explanation": "Git folders support clone, branch, commit/push, pull, merge, rebase and conflict resolution. PR approval and repo permissions are managed in the Git provider."},
    # ---------------- D6 Troubleshooting & Optimization ----------------
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "A daily job has become **slower every week**. Where do you first look to confirm the trend and find the responsible task?",
     "options": ["The Unity Catalog lineage graph",
                 "The cluster's init scripts",
                 "The job's run history (Runs tab, matrix view with task durations)",
                 "The notebook's revision history"],
     "answer": 2,
     "explanation": "The run history/matrix view shows durations per run and per task, revealing trends and the slow task; system.lakeflow tables give the same at scale."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "In a stage of 200 tasks, 199 finish in about 10 seconds and one takes 15 minutes. What is the most likely cause?",
     "options": ["The driver is out of memory",
                 "Too few executors",
                 "The table is not optimized with VACUUM",
                 "Data skew — one partition holds far more data than the others"],
     "answer": 3,
     "explanation": "Very uneven task durations indicate skew (e.g. a hot key). Fixes: AQE skew-join handling, salting, choosing better keys."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "The query profile shows large amounts of **spill to disk**. What does it indicate?",
     "options": ["Partitions don't fit in executor memory during shuffles/aggregations",
                 "The table needs a VACUUM",
                 "The network is slow",
                 "Too many small files"],
     "answer": 0,
     "explanation": "Spill happens when data per task exceeds available memory. More memory, more/smaller partitions or less data per task (filter early) reduce it."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "Which advantages does **liquid clustering** have over partitioning plus Z-order? (Choose TWO)",
     "options": ["Clustering keys can be changed without rewriting the existing data",
                 "Clustering is incremental — OPTIMIZE only clusters new or changed data",
                 "It can be combined with PARTITIONED BY on the same table",
                 "It removes the need for a transaction log"],
     "answer": [0, 1],
     "explanation": "Liquid clustering is incremental and its keys are changeable; it can't be combined with partitioning or Z-order."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "Which statement enables liquid clustering on an existing Delta table?",
     "options": ["`OPTIMIZE events ZORDER BY (event_date)`",
                 "`ALTER TABLE events PARTITIONED BY (event_date)`",
                 "`ALTER TABLE events CLUSTER BY (event_date, user_id)`",
                 "`VACUUM events CLUSTER`"],
     "answer": 2,
     "explanation": "ALTER TABLE … CLUSTER BY (cols) sets the keys; subsequent OPTIMIZE runs cluster the data. CLUSTER BY AUTO lets Databricks choose."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "What does **predictive optimization** do?",
     "options": ["Chooses the cheapest instance type for jobs",
                 "Predicts query results before they run",
                 "Caches every table in memory",
                 "Automatically runs maintenance such as OPTIMIZE, VACUUM and ANALYZE on Unity Catalog managed tables"],
     "answer": 3,
     "explanation": "Predictive optimization identifies and runs maintenance operations for UC managed tables, removing the need to schedule them manually."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "What does `CLUSTER BY AUTO` do?",
     "options": ["Lets Databricks choose and adapt the clustering keys based on the table's query patterns",
                 "Partitions the table by date automatically",
                 "Disables clustering",
                 "Clusters the table by every column"],
     "answer": 0,
     "explanation": "Automatic liquid clustering (with predictive optimization) selects keys from observed query workloads and changes them when patterns change."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "A classic cluster fails to start with an error that the requested instance type is **unavailable / quota exceeded** in the region. What is a reasonable fix?",
     "options": ["Increase spark.sql.shuffle.partitions",
                 "Choose another instance type or availability zone, request a higher cloud quota, or use serverless compute",
                 "Run VACUUM on the tables",
                 "Delete the job and recreate it"],
     "answer": 1,
     "explanation": "Startup failures caused by cloud capacity/quotas are fixed at the infrastructure level: different instance type/zone, quota increase, on-demand instead of spot, or serverless."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "Where do you check how many records failed each **expectation** of a declarative pipeline over time?",
     "options": ["The cluster's Spark config",
                 "The Git folder history",
                 "The pipeline event log (and the data-quality metrics in the pipeline UI)",
                 "DESCRIBE HISTORY of the source files"],
     "answer": 2,
     "explanation": "Expectation results are written to the pipeline event log (flow_progress events) and shown in the pipeline graph's data-quality tab."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "On **serverless** compute or a SQL warehouse, where do you analyse a slow query's operators, rows, bytes read and pruning?",
     "options": ["The workspace audit log",
                 "The cluster event log",
                 "The Spark UI's Storage tab",
                 "The query profile"],
     "answer": 3,
     "explanation": "The query profile shows the execution graph with time, rows, memory, spill and files/bytes pruned per operator."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "A table written by frequent small appends now has **thousands of tiny files** and queries are slow. Which actions help? (Choose TWO)",
     "options": ["Run `VACUUM` with 0 hours retention",
                 "Run `OPTIMIZE` (or rely on auto compaction / predictive optimization)",
                 "Increase `spark.sql.shuffle.partitions`",
                 "Use liquid clustering so OPTIMIZE compacts and clusters incrementally"],
     "answer": [1, 3],
     "explanation": "Compaction (OPTIMIZE, auto compaction, predictive optimization) merges small files; liquid clustering keeps layout healthy incrementally. VACUUM only deletes unreferenced files."},
    {"topic": "D6 Troubleshooting & Optimization",
     "q": "A job task fails at random times with an out-of-memory error on the **driver** after `df.collect()` on a large DataFrame. What is the best fix?",
     "options": ["Increase spark.sql.shuffle.partitions",
                 "Avoid collecting large data to the driver — write results to a table or aggregate/limit before collecting",
                 "Add more workers",
                 "Use a spot driver"],
     "answer": 1,
     "explanation": "collect() pulls the whole dataset into driver memory. Keep data distributed (write it out) or reduce it first; more workers don't help the driver."},
    # ---------------- D7 Governance & Security ----------------
    {"topic": "D7 Governance & Security",
     "q": "A user must read the table `main.sales.orders` and nothing else. Which privileges are required?",
     "options": ["ALL PRIVILEGES on the schema",
                 "MODIFY on the table",
                 "USE CATALOG on main, USE SCHEMA on main.sales, SELECT on the table",
                 "SELECT on the table only"],
     "answer": 2,
     "explanation": "Reaching an object requires USE CATALOG and USE SCHEMA on its parents; SELECT grants read access. This is the least-privilege set."},
    {"topic": "D7 Governance & Security",
     "q": "What happens when you run `DROP TABLE` on a Unity Catalog **managed** table?",
     "options": ["Only the metadata is removed; the files stay forever",
                 "Nothing happens until VACUUM",
                 "The table is converted to external",
                 "The table is removed and its data files are deleted (it can be recovered with UNDROP during the retention period)"],
     "answer": 3,
     "explanation": "Managed tables' data is managed by UC; dropped managed tables can be restored with UNDROP TABLE within the retention window (7 days by default)."},
    {"topic": "D7 Governance & Security",
     "q": "What happens when you run `DROP TABLE` on an **external** table?",
     "options": ["The metadata is removed; the data files in the external location remain",
                 "The command fails",
                 "The external location is deleted",
                 "The data files are deleted immediately"],
     "answer": 0,
     "explanation": "External tables point to storage you manage; dropping them removes only the table definition."},
    {"topic": "D7 Governance & Security",
     "q": "What is needed to create an **external table** at `abfss://data@lake.dfs.core.windows.net/sales/`?",
     "options": ["Only CREATE TABLE on the schema",
                 "An external location covering the path (backed by a storage credential) and CREATE EXTERNAL TABLE on it, plus CREATE TABLE on the schema",
                 "A DBFS mount of the container",
                 "A personal access token"],
     "answer": 1,
     "explanation": "Unity Catalog governs paths through external locations (storage credential + URL). Mounts are legacy and not used with UC."},
    {"topic": "D7 Governance & Security",
     "q": "An external Delta table should become a **managed** table without copying data by hand. Which command?",
     "options": ["`ALTER TABLE sales SET LOCATION NULL`",
                 "`UNDROP TABLE sales`",
                 "`ALTER TABLE sales SET MANAGED`",
                 "`CONVERT TO DELTA sales`"],
     "answer": 2,
     "explanation": "SET MANAGED converts an external table to a UC managed table (with a short UNSET window). CONVERT TO DELTA converts Parquet to Delta."},
    {"topic": "D7 Governance & Security",
     "q": "`GRANT SELECT ON SCHEMA main.sales TO analysts` is executed. Which tables can the analysts read (given USE CATALOG/USE SCHEMA)?",
     "options": ["None until SELECT is granted per table",
                 "Only tables created after the grant",
                 "Only tables created before the grant",
                 "All current and future tables and views in the schema"],
     "answer": 3,
     "explanation": "Privileges are inherited by child objects — existing and future ones."},
    {"topic": "D7 Governance & Security",
     "q": "SELECT was granted on the **schema** to a group. To block one table, an admin runs `REVOKE SELECT ON TABLE main.sales.salaries FROM group`. Result?",
     "options": ["The group can still read salaries — the schema-level grant still applies and UC has no DENY",
                 "The command creates a DENY rule",
                 "The group loses access to the whole schema",
                 "The group can no longer read salaries"],
     "answer": 0,
     "explanation": "You can only revoke where something was granted. Move the table to another schema, use a row filter/mask, or restructure the grants."},
    {"topic": "D7 Governance & Security",
     "q": "Which statement about **DENY** is correct?",
     "options": ["DENY is applied with ALTER TABLE",
                 "Unity Catalog doesn't support DENY; only the legacy hive_metastore table ACLs had it",
                 "DENY overrides GRANT in Unity Catalog",
                 "DENY is the only way to remove access"],
     "answer": 1,
     "explanation": "Unity Catalog is allow-only: access exists only if granted (directly or by inheritance). Use REVOKE."},
    {"topic": "D7 Governance & Security",
     "q": "A column mask must show full e-mails to the group `pii_readers` and `***` to everybody else. Which function and statement are correct?",
     "code": "-- function\nCREATE FUNCTION mask_email(email STRING) RETURNS STRING\nRETURN CASE WHEN is_account_group_member('pii_readers') THEN email ELSE '***' END;",
     "options": ["`GRANT MASK ON customers.email TO pii_readers`",
                 "`CREATE VIEW customers MASK email`",
                 "`ALTER TABLE customers ALTER COLUMN email SET MASK mask_email`",
                 "`ALTER TABLE customers SET ROW FILTER mask_email ON (email)`"],
     "answer": 2,
     "explanation": "Column masks are SQL UDFs attached with ALTER COLUMN … SET MASK; the first parameter receives the column value. Row filters are attached with SET ROW FILTER."},
    {"topic": "D7 Governance & Security",
     "q": "Which statement attaches a row filter so that users only see rows of the regions they are allowed to see?",
     "options": ["`CREATE POLICY region_filter ON TABLE sales`",
                 "`GRANT SELECT ON sales WHERE region = 'EMEA' TO emea`",
                 "`ALTER TABLE sales ADD CONSTRAINT region_filter CHECK (region = current_user())`",
                 "`ALTER TABLE sales SET ROW FILTER region_filter ON (region)`"],
     "answer": 3,
     "explanation": "A row filter is a BOOLEAN SQL UDF attached to the table; columns listed in ON (…) are passed to it. GRANT has no WHERE clause."},
    {"topic": "D7 Governance & Security",
     "q": "Analysts have SELECT on the base table `customers` **and** on a dynamic view that masks e-mails. Are e-mails protected?",
     "options": ["No — anyone who can query the base table bypasses the view; use a column mask on the table or remove SELECT on the table",
                 "Yes, the view protects the table",
                 "Yes, because views always override tables",
                 "Only if the view is a materialized view"],
     "answer": 0,
     "explanation": "Dynamic views protect only readers who go through the view. Masks and row filters on the table protect every query."},
    {"topic": "D7 Governance & Security",
     "q": "Which function should a dynamic view or mask use to check membership of an **account-level** group?",
     "options": ["`current_group()`",
                 "`is_account_group_member('grp')`",
                 "`is_member('grp')`",
                 "`has_permission('grp')`"],
     "answer": 1,
     "explanation": "is_account_group_member checks account groups (Unity Catalog). is_member checks legacy workspace-local groups."},
    {"topic": "D7 Governance & Security",
     "q": "What do you need to implement an **ABAC** policy that masks every column tagged as PII across a whole catalog?",
     "options": ["A dynamic view per table",
                 "DENY SELECT on tagged columns",
                 "Governed tags on the columns, a masking UDF, and `CREATE POLICY … COLUMN MASK … MATCH COLUMNS has_tag_value(...)` on the catalog or schema",
                 "A row filter on each table"],
     "answer": 2,
     "explanation": "ABAC policies combine governed tags with UDFs and are defined at catalog/schema level; they apply to all matching tables, current and future."},
    {"topic": "D7 Governance & Security",
     "q": "What is the main advantage of **ABAC policies** over per-table row filters and column masks?",
     "options": ["They work only on external tables",
                 "They make queries faster",
                 "They don't need any functions",
                 "One central policy automatically protects all current and future tables whose columns carry the matching tags"],
     "answer": 3,
     "explanation": "ABAC scales governance: tag the data, write the policy once — new tables are protected as soon as they are tagged."},
    {"topic": "D7 Governance & Security",
     "q": "The **owner** of a table with a row filter queries it. What do they see?",
     "options": ["Only the rows the filter function allows for them — exemptions must be written inside the function",
                 "An error",
                 "No rows",
                 "All rows — owners bypass row filters"],
     "answer": 0,
     "explanation": "Row filters and masks apply to every principal, including owners and admins, unless the function itself makes an exception (e.g. an admin group)."},
    {"topic": "D7 Governance & Security",
     "q": "Ownership of the table `gold.revenue` must move from a departing engineer to the group `data_engineers`. Which statement?",
     "options": ["`UPDATE gold.revenue SET owner = 'data_engineers'`",
                 "`ALTER TABLE gold.revenue OWNER TO `data_engineers``",
                 "`GRANT OWNERSHIP ON gold.revenue TO data_engineers`",
                 "`ALTER TABLE gold.revenue SET OWNER data_engineers`"],
     "answer": 1,
     "explanation": "ALTER <object> … OWNER TO principal transfers ownership. Groups as owners avoid dependence on one person."},
    {"topic": "D7 Governance & Security",
     "q": "A service principal must **create tables** in the schema `main.staging`. Which privileges does it need? (Choose THREE)",
     "options": ["CREATE TABLE on main.staging",
                 "SELECT on every table of the catalog",
                 "USE SCHEMA on main.staging",
                 "USE CATALOG on main"],
     "answer": [0, 2, 3],
     "explanation": "Creating an object requires USE CATALOG + USE SCHEMA on the parents and CREATE TABLE on the schema. Reading other tables is not required."},
    {"topic": "D7 Governance & Security",
     "q": "Which operations does the **MODIFY** privilege on a table allow?",
     "options": ["Granting SELECT to others",
                 "Dropping the table",
                 "Changing the table's owner",
                 "INSERT, UPDATE, DELETE and MERGE of the table's data"],
     "answer": 3,
     "explanation": "MODIFY covers data changes. Ownership (or MANAGE) is needed to drop, change ownership or manage grants."},
]

DOMAINS = ["D1 Platform", "D2 Ingestion", "D3 Transformation", "D4 Lakeflow Jobs", "D5 CI/CD",
           "D6 Troubleshooting & Optimization", "D7 Governance & Security"]
SIMULATION_MIX = {"D1 Platform": 3, "D2 Ingestion": 9, "D3 Transformation": 10, "D4 Lakeflow Jobs": 7, "D5 CI/CD": 5,
                  "D6 Troubleshooting & Optimization": 4, "D7 Governance & Security": 7}
assert len(questions) == 120, len(questions)
assert sum(SIMULATION_MIX.values()) == 45
print({d: sum(q["topic"] == d for q in questions) for d in DOMAINS})

# COMMAND ----------

# MAGIC %md
# MAGIC ## ⏱️ Part 1 · Exam simulation — 45 questions, 90 minutes
# MAGIC Set the widget **`exam_seed`** (top of the notebook) to any number — each seed is a different exam with the official
# MAGIC domain mix — then run the next cell. The timer starts immediately; **Submit exam** shows the score per domain.

# COMMAND ----------

# DBTITLE 1,Build the simulation
import random

dbutils.widgets.text("exam_seed", "1", "exam_seed")
dbutils.widgets.dropdown("practice_domain", "All", ["All"] + DOMAINS, "practice_domain")


def build_simulation(seed: int):
    rng = random.Random(seed)
    picked = []
    for domain, n in SIMULATION_MIX.items():
        picked += rng.sample([q for q in questions if q["topic"] == domain], n)
    rng.shuffle(picked)
    return picked


_seed = int(dbutils.widgets.get("exam_seed") or 1)
simulation = build_simulation(_seed)
print(f"exam #{_seed}: {len(simulation)} questions")

# COMMAND ----------

# DBTITLE 1,⏱️ Start the exam simulation
render_quiz(simulation, title=f"Mock exam #{_seed} · Data Engineer Associate", mode="exam", minutes=90, pass_mark=0.8,
            meta="45 questions · 90 minutes · no feedback until you submit · unanswered = wrong · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 📚 Part 2 · Practice mode — learn from every question
# MAGIC Choose a domain in the **`practice_domain`** widget (or *All* for 120 questions), run the cell, click **Check answer**
# MAGIC after each question to see the explanation.

# COMMAND ----------

# DBTITLE 1,📚 Practice
_domain = dbutils.widgets.get("practice_domain")
_practice = questions if _domain == "All" else [q for q in questions if q["topic"] == _domain]
render_quiz(_practice, title=f"Practice · {_domain}", pass_mark=0.8,
            meta=f"{len(_practice)} questions · instant feedback · {'all domains' if _domain == 'All' else _domain}")

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🗺️ Weak-area map — where to go back
# MAGIC | Domain below 70 % | Presentations | Labs | Quizzes |
# MAGIC |---|---|---|---|
# MAGIC | D1 Platform | 01-P1…P3, 03-P1, 04-P1 | 01-L1, 03-L1, 14-L1 | 00-Q, 01-Q, 03-Q, 04-Q |
# MAGIC | D2 Ingestion | 05-P1…P3, 06-P1…P3, 08-P2 | 05-L1…L3, 06-L1…L4, 14-L2 Parts 1–3 | 05-Q, 06-Q |
# MAGIC | D3 Transformation | 02-P1…P3, 07-P1…P3, 08-P3 | 07-L1…L4, 14-L2 Parts 4–6, 14-L3, 14-CS1, 14-CS2 | 02-Q, 07-Q, 08-Q |
# MAGIC | D4 Lakeflow Jobs | 10-P1…P3 | 10-L1…L4, 14-L4 Parts 2–3 | 10-Q |
# MAGIC | D5 CI/CD | Section 11 (coming) · 14-P2 (D5 slide) | 14-L4 Part 5 | 11-Q (coming) |
# MAGIC | D6 Troubleshooting & Optimization | 12-P1…P4 · 14-P2 (D6 slides) | 12-L1…L5, 14-L3 Part 4, 14-L4 Part 4 | 12-Q |
# MAGIC | D7 Governance & Security | 13-P1…P3, 04-P2 | 13-L1…L4, 14-L1 Part 5, 14-L3 Part 5 | 13-Q |
# MAGIC
# MAGIC > 🎯 Then read **14-P2 · Final Review** and **14-P3 · Exam Strategy** once more, and take a new simulation with another seed.

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key of the current simulation
# print_answer_key(simulation)
