# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 10-Q · Exam Questions — Lakeflow Jobs
# MAGIC **58 exam-style questions** on jobs and tasks (10-P1), control flow, retries and repair (10-P2) and triggers, schedules and
# MAGIC orchestration patterns (10-P3). Multi-answer questions say so. Target **≥ 80 %** before Section 11.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Jobs & task types ----------------
    {"topic": "Jobs & task types",
     "q": "Which Lakeflow component schedules and orchestrates notebooks, SQL, pipelines and dashboards with dependencies, retries and notifications?",
     "options": ["Lakeflow Jobs",
                 "Lakeflow Spark Declarative Pipelines",
                 "Lakeflow Connect",
                 "Unity Catalog"],
     "answer": 0,
     "explanation": "Lakeflow Jobs (formerly Databricks Workflows/Jobs) is the orchestration layer. Connect ingests, Spark Declarative Pipelines transform, Unity Catalog governs."},
    {"topic": "Jobs & task types",
     "q": "A job has tasks A → B and A → C (B and C both depend only on A). How do B and C run?",
     "options": ["Only one of them runs, chosen at random",
                 "In parallel, after A succeeds",
                 "In parallel with A",
                 "B, then C, in alphabetical order"],
     "answer": 1,
     "explanation": "Tasks whose dependencies are met run concurrently. B and C both wait for A (default run-if: All succeeded) and then run in parallel."},
    {"topic": "Jobs & task types",
     "q": "Which task type should you use to run an update of a Lakeflow Spark Declarative Pipeline as a step of a job?",
     "options": ["SQL task with `REFRESH PIPELINE`",
                 "Run Job task",
                 "Pipeline task",
                 "Notebook task that opens the pipeline source file"],
     "answer": 2,
     "explanation": "The pipeline task triggers an update of the selected (triggered) pipeline, optionally a full refresh; the pipeline uses its own compute."},
    {"topic": "Jobs & task types",
     "q": "What compute does a **SQL task** (query, alert or file) require?",
     "options": ["A jobs cluster with Photon",
                 "The pipeline's compute",
                 "Any all-purpose cluster",
                 "A serverless or pro SQL warehouse"],
     "answer": 3,
     "explanation": "SQL tasks run on a SQL warehouse — serverless or pro (classic warehouses aren't supported for SQL tasks)."},
    {"topic": "Jobs & task types",
     "q": "Which three subtypes can a SQL task run? (Choose THREE)",
     "options": ["A Python wheel",
                 "A SQL alert",
                 "A `.sql` file from the workspace or a Git provider",
                 "A saved query",
                 "A JAR"],
     "answer": [1, 2, 3],
     "explanation": "SQL task → Query, Alert or File. Wheels and JARs have their own task types."},
    {"topic": "Jobs & task types",
     "q": "After the nightly load, a published AI/BI dashboard must be refreshed and its subscribers e-mailed. What is the most direct way?",
     "options": ["A dashboard schedule at 06:00",
                 "A dashboard task that depends on the load task",
                 "A SQL alert",
                 "A notebook task calling the dashboards REST API"],
     "answer": 1,
     "explanation": "The dashboard task refreshes a published dashboard (on a SQL warehouse) and can notify subscribers — right after the data is ready."},
    {"topic": "Jobs & task types",
     "q": "A team wants to reuse its standard ingestion job inside three different pipelines without copying its tasks. Which task type helps?",
     "options": ["If/else condition task",
                 "Pipeline task",
                 "Run Job task",
                 "For each task"],
     "answer": 2,
     "explanation": "A Run Job task triggers another job (parent → child) and can pass job parameters — modular, reusable jobs."},
    {"topic": "Jobs & task types",
     "q": "Where can the notebook of a notebook task come from? (Choose TWO)",
     "options": ["An e-mail attachment",
                 "The workspace (e.g. a Git folder)",
                 "A DBFS mount only",
                 "A remote Git repository (Git provider: branch, tag or commit)"],
     "answer": [1, 3],
     "explanation": "Source = Workspace or Git provider. With a Git provider the job checks out the code at run time."},
    {"topic": "Jobs & task types",
     "q": "What is the maximum number of tasks in one job?",
     "options": ["1,000",
                 "10",
                 "100",
                 "Unlimited"],
     "answer": 0,
     "explanation": "A job can have up to 1,000 tasks. Use Run Job tasks to modularise larger workflows."},
    {"topic": "Jobs & task types",
     "q": "Old study material mentions **Databricks Workflows** and the **Delta Live Tables pipeline task**. What are they called today?",
     "options": ["Lakeflow Connect and the SQL task",
                 "Lakeflow Jobs and the pipeline task",
                 "Databricks SQL and the dashboard task",
                 "Unity Catalog and the Run Job task"],
     "answer": 1,
     "explanation": "Workflows/Jobs → Lakeflow Jobs; DLT → Lakeflow Spark Declarative Pipelines, run from a job with the pipeline task."},
    # ---------------- Compute, parameters & task values ----------------
    {"topic": "Compute, parameters & task values",
     "q": "What is the most cost-effective classic compute for a scheduled nightly notebook job?",
     "options": ["A single-node all-purpose cluster shared with analysts",
                 "A SQL warehouse",
                 "A jobs cluster (job compute) created for the run",
                 "An all-purpose cluster that stays on"],
     "answer": 2,
     "explanation": "Job compute is created for the run and terminated afterwards, at a lower DBU rate than all-purpose compute. (Serverless is the other good option.)"},
    {"topic": "Compute, parameters & task values",
     "q": "Serverless jobs offer two modes. Which statement is correct?",
     "options": ["Standard mode is faster but more expensive",
                 "Both modes cost the same DBUs",
                 "Standard mode only supports SQL",
                 "Performance optimized starts fast; standard mode is cheaper with a longer start-up (minutes)"],
     "answer": 3,
     "explanation": "Performance optimized = fast start-up and execution; standard = fewer DBUs, start-up of several minutes — fine for jobs without tight latency needs."},
    {"topic": "Compute, parameters & task values",
     "q": "A job has the job parameter `files` (default `1`). How does a notebook task read it?",
     "options": ["`dbutils.widgets.get(\"files\")` — it arrives as a widget value (a string)",
                 "`os.environ[\"files\"]`",
                 "It can't: job parameters are only for SQL tasks",
                 "`spark.conf.get(\"files\")`"],
     "answer": 0,
     "explanation": "Job parameters are pushed down to notebook tasks and arrive as widgets; values are strings, so convert them (int(...))."},
    {"topic": "Compute, parameters & task values",
     "q": "An operator must re-run a job once for two days of files (`files = 2`) without changing the job. What do they use, and which permission do they need?",
     "options": ["Edit the default value — CAN VIEW",
                 "Run now with different parameters — CAN MANAGE RUN",
                 "Clone the job — CAN VIEW",
                 "Repair run — IS OWNER"],
     "answer": 1,
     "explanation": "Run now with different parameters overrides job parameter values for one run; it requires CAN MANAGE RUN (or higher)."},
    {"topic": "Compute, parameters & task values",
     "q": "Which dynamic value reference gives the date on which the run started (e.g. `2026-07-01`)?",
     "options": ["`{{job.run_date}}`",
                 "`:start_date`",
                 "`{{job.start_time.iso_date}}`",
                 "`${current_date}`"],
     "answer": 2,
     "explanation": "{{job.start_time.iso_date}} (UTC). The legacy form was {{start_date}}."},
    {"topic": "Compute, parameters & task values",
     "q": "Task `quality_check` computes `bad_rows`. How can the downstream If/else task use it?",
     "options": ["Return it with `print()`",
                 "Store it in `spark.conf`",
                 "Write it to a widget",
                 "`quality_check` calls `dbutils.jobs.taskValues.set(key=\"bad_rows\", value=n)`; the If/else task uses `{{tasks.quality_check.values.bad_rows}}`"],
     "answer": 3,
     "explanation": "Task values pass small JSON-serialisable results between tasks; reference them with {{tasks.<task>.values.<key>}} or read them with taskValues.get()."},
    {"topic": "Compute, parameters & task values",
     "q": "A developer runs a notebook that calls `dbutils.jobs.taskValues.get(taskKey=\"load\", key=\"rows\", debugValue=0)` interactively, outside a job. What happens?",
     "options": ["It returns 0, the debugValue",
                 "It waits until the job runs",
                 "It fails because there is no job",
                 "It returns None"],
     "answer": 0,
     "explanation": "debugValue is returned when the notebook runs outside a job, so you can develop and test it interactively."},
    {"topic": "Compute, parameters & task values",
     "q": "What is the size limit of one task value?",
     "options": ["No limit",
                 "48 KiB as JSON",
                 "10 MB",
                 "1 KB"],
     "answer": 1,
     "explanation": "Task values are for small results (≤ 48 KiB as JSON). Larger data goes into tables."},
    {"topic": "Compute, parameters & task values",
     "q": "A job parameter and a task parameter have the same key `env`. Which value does the task get?",
     "options": ["The run fails with a conflict",
                 "Both, comma-separated",
                 "The job parameter's value",
                 "The task parameter's value"],
     "answer": 2,
     "explanation": "Job parameters are pushed down to the tasks and take precedence over task parameters with the same key."},
    # ---------------- Control flow ----------------
    {"topic": "Control flow",
     "q": "Task `cleanup` must run after `load` and `transform` **whatever** their result. Which Run if dependencies condition?",
     "options": ["All succeeded",
                 "None failed",
                 "At least one failed",
                 "All done"],
     "answer": 3,
     "explanation": "All done runs the task once all dependencies have finished, regardless of their status."},
    {"topic": "Control flow",
     "q": "A `notify_oncall` task must run **only** when its upstream task failed. Which condition, and what is its state when the upstream succeeds?",
     "options": ["At least one failed — Excluded",
                 "All succeeded — Skipped",
                 "None failed — Upstream failed",
                 "All done — Succeeded"],
     "answer": 0,
     "explanation": "At least one failed runs only on failure; when the condition is not met the task is marked Excluded (skipped)."},
    {"topic": "Control flow",
     "q": "Task D depends on B (true branch of an If/else) and C (false branch). One branch is always excluded. Which condition lets D run after whichever branch ran successfully?",
     "options": ["All failed",
                 "None failed",
                 "All done",
                 "At least one failed"],
     "answer": 1,
     "explanation": "None failed: no dependency failed and at least one ran (excluded tasks count as successful). All done would also run D after a FAILED branch; the two failure conditions would never run it after a success."},
    {"topic": "Control flow",
     "q": "With the default condition (All succeeded), what is the state of a task whose dependency failed?",
     "options": ["Canceled",
                 "Excluded",
                 "Upstream failed",
                 "Failed"],
     "answer": 2,
     "explanation": "Unmet success-type conditions mark the task Upstream failed; unmet failure-type conditions mark it Excluded."},
    {"topic": "Control flow",
     "q": "Which operators can an If/else condition task use? (Choose TWO groups that are correct)",
     "options": ["`==` and `!=` (compared as strings)",
                 "`>`, `>=`, `<`, `<=` (compared as numbers)",
                 "`AND` / `OR` between several comparisons",
                 "`LIKE` and `IN`"],
     "answer": [0, 1],
     "explanation": "One comparison per task with ==, !=, >, >=, <, <=. == / != compare strings, the others compare numbers."},
    {"topic": "Control flow",
     "q": "An If/else condition is `{{tasks.check.values.ratio}} == 1` and the task value is `1.0`. What is the outcome?",
     "options": ["false — `==` compares the strings \"1.0\" and \"1\"",
                 "The task fails",
                 "true — both are the number one",
                 "true only if the job parameter is numeric"],
     "answer": 0,
     "explanation": "== and != perform string comparison (12.0 == 12 is false); >= would compare numerically (12.0 >= 12 is true)."},
    {"topic": "Control flow",
     "q": "How do you make a task run only when the If/else task `gate` evaluated to **false**?",
     "options": ["Disable the task",
                 "Set its Depends on to `gate (false)`",
                 "Set Run if to At least one failed",
                 "Add a task parameter `outcome = false`"],
     "answer": 1,
     "explanation": "Downstream tasks depend on gate (true) or gate (false); the branch not taken is Excluded."},
    {"topic": "Control flow",
     "q": "A For each task loops over `[\"EU\",\"US\",\"APAC\"]`. How does the nested notebook task receive the current region?",
     "options": ["`{{job.parameters.input}}`",
                 "It reads the whole list and picks its index",
                 "A task parameter whose value is `{{input}}`",
                 "`dbutils.jobs.forEach.current()`"],
     "answer": 2,
     "explanation": "Pass {{input}} (or {{input.<key>}} for JSON objects) as a parameter of the nested task."},
    {"topic": "Control flow",
     "q": "What is the default **concurrency** of a For each task?",
     "options": ["Equal to the number of inputs",
                 "10",
                 "Unlimited",
                 "1 — iterations run one after another"],
     "answer": 3,
     "explanation": "Concurrency defaults to 1; raise it to run iterations in parallel."},
    {"topic": "Control flow",
     "q": "Which statements about For each tasks are true? (Choose TWO)",
     "options": ["Iterations always run on separate all-purpose clusters",
                 "Inputs must be a comma-separated string",
                 "The inputs can come from a task value such as `{{tasks.list.values.items}}`",
                 "A For each task cannot contain another For each task"],
     "answer": [2, 3],
     "explanation": "Inputs: a JSON array typed in, a task value or a job parameter. Nesting For each is not allowed (use a Run Job task to go deeper)."},
    {"topic": "Control flow",
     "q": "Before If/else tasks existed, how was branching typically implemented?",
     "options": ["With `%run` and an `if` around it",
                 "A driver notebook calling `dbutils.notebook.run()` for the chosen child notebook",
                 "It was impossible",
                 "With two separate jobs and cron offsets only"],
     "answer": 1,
     "explanation": "dbutils.notebook.run() runs a child notebook (with parameters and a timeout) and returns its exit value — logic hidden inside code. %run can't be made conditional."},
    # ---------------- Reliability & repair ----------------
    {"topic": "Reliability & repair",
     "q": "A task calling an external API fails about once a week with a timeout and succeeds when re-run. What should you configure?",
     "options": ["A higher maximum concurrent runs",
                 "A continuous trigger",
                 "Retries on the task (with a retry interval)",
                 "Run if = All done on the task"],
     "answer": 2,
     "explanation": "Retries handle transient errors: the task is re-run up to N times after an interval."},
    {"topic": "Reliability & repair",
     "q": "Which dynamic value reference tells a task which execution (attempt) it is in, retries and repairs included?",
     "options": ["`{{run_id}}`",
                 "`{{task.retry}}`",
                 "`{{job.repair_count}}` only",
                 "`{{task.execution_count}}`"],
     "answer": 3,
     "explanation": "{{task.execution_count}} (legacy {{task_retry_count}}). {{job.repair_count}} counts repairs of the job run."},
    {"topic": "Reliability & repair",
     "q": "A run failed at task 7 of 10 because of a bug. You fixed the notebook. Which action completes the run while re-running the fewest tasks?",
     "options": ["Repair run — re-runs the failed task and its dependents",
                 "Increase the retries of task 7",
                 "Run now",
                 "Delete and recreate the job"],
     "answer": 0,
     "explanation": "Repair run re-runs only failed/skipped/canceled tasks and the tasks that depend on them, in the same job run, with the current settings."},
    {"topic": "Reliability & repair",
     "q": "Which statements about repair runs are correct? (Choose TWO)",
     "options": ["A repaired task runs from the beginning, so non-idempotent tasks may duplicate data",
                 "Successful tasks are not re-run",
                 "Repair is the only way to re-run a single-task job",
                 "Repair restores Delta tables to the state before the run"],
     "answer": [0, 1],
     "explanation": "Repair skips successful tasks and restarts failed ones from scratch; it doesn't roll back data. For a single-task job, use Run now."},
    {"topic": "Reliability & repair",
     "q": "A job's duration threshold has **Warning = 30 min** and **Timeout = 2 h**. The run takes 45 minutes. What happens?",
     "options": ["The run is retried",
                 "The run is stopped at 30 minutes",
                 "A duration-warning notification is sent and the run continues",
                 "Nothing — thresholds only apply to SQL tasks"],
     "answer": 2,
     "explanation": "Warning (expected duration) triggers a notification; only the timeout stops the run (state Timed out)."},
    {"topic": "Reliability & repair",
     "q": "A job with the default concurrency is still running when its next scheduled run is due. Queueing is enabled. What happens?",
     "options": ["The new run is skipped",
                 "Both runs execute in parallel",
                 "The active run is canceled",
                 "The new run waits in the queue until the active run finishes"],
     "answer": 3,
     "explanation": "Max concurrent runs defaults to 1; with queueing on, the extra run is queued (up to 48 h) instead of being skipped."},
    {"topic": "Reliability & repair",
     "q": "Where can job notifications be sent? (Choose TWO)",
     "options": ["E-mail addresses",
                 "Only to the job owner's inbox",
                 "Directly into a Delta table",
                 "Notification destinations such as Slack, Microsoft Teams, PagerDuty or webhooks"],
     "answer": [0, 3],
     "explanation": "Notifications (start, success, failure, duration warning, streaming backlog) go to e-mail or system notification destinations."},
    {"topic": "Reliability & repair",
     "q": "Serverless jobs retried a failing non-idempotent task automatically and duplicated data. What explains it?",
     "options": ["Queueing re-runs failed tasks",
                 "Serverless auto-optimization retries failed tasks by default — disable it for at-most-once tasks",
                 "Serverless always runs every task twice",
                 "The For each concurrency was too high"],
     "answer": 1,
     "explanation": "Auto-optimization on serverless job compute optimises compute and retries failed tasks; turn it off where a retry is unsafe."},
    {"topic": "Reliability & repair",
     "q": "You want to keep a task in the job definition but skip it in the next runs while a source system is down. What do you do?",
     "options": ["Delete the task",
                 "Set its retries to 0",
                 "Disable the task",
                 "Set Run if to All failed"],
     "answer": 2,
     "explanation": "A disabled task is skipped at runtime but keeps its configuration and history; enable it again later."},
    # ---------------- Triggers & schedules ----------------
    {"topic": "Triggers & schedules",
     "q": "Which trigger types can start a Lakeflow job automatically? (Choose THREE)",
     "options": ["Table update",
                 "Notebook widget change",
                 "Cluster start",
                 "File arrival",
                 "Scheduled"],
     "answer": [0, 3, 4],
     "explanation": "Scheduled, file arrival, table update and continuous (plus manual/API runs)."},
    {"topic": "Triggers & schedules",
     "q": "Which Quartz cron expression runs a job every day at 06:00:00?",
     "options": ["`0 0 6 * * ?`",
                 "`0 6 * * *`",
                 "`* * 6 0 0 ?`",
                 "`6 0 0 * * ?`"],
     "answer": 0,
     "explanation": "Quartz fields: seconds minutes hours day-of-month month day-of-week. `0 6 * * *` is the 5-field Unix form, not Quartz."},
    {"topic": "Triggers & schedules",
     "q": "In the Quartz expression `0 30 2 ? * MON-FRI`, what does `?` mean?",
     "options": ["A random day",
                 "No specific value for day-of-month (day-of-week is used instead)",
                 "The last day of the month",
                 "Every second"],
     "answer": 1,
     "explanation": "In Quartz you set either day-of-month or day-of-week; the other gets `?`. The expression = 02:30 on weekdays."},
    {"topic": "Triggers & schedules",
     "q": "An hourly job in a time zone with daylight saving time skipped a run at the clock change. What is the recommendation?",
     "options": ["Use a continuous trigger",
                 "Use a file arrival trigger",
                 "Use UTC for the schedule's time zone",
                 "Increase max concurrent runs"],
     "answer": 2,
     "explanation": "Hourly runs can be skipped or delayed at DST transitions; UTC avoids it."},
    {"topic": "Triggers & schedules",
     "q": "Where can a **file arrival** trigger watch for new files?",
     "options": ["A table's `_delta_log`",
                 "A Kafka topic",
                 "Any local folder on the driver",
                 "A Unity Catalog volume or external location (or a sub-path)"],
     "answer": 3,
     "explanation": "File arrival triggers monitor UC volumes and external locations; they check about every minute, recursively."},
    {"topic": "Triggers & schedules",
     "q": "Partners upload many small files in bursts. You want **one** run after a burst, not one per file. Which file-arrival setting helps most?",
     "options": ["Wait after last change",
                 "Maximum concurrent runs = 10",
                 "Minimum time between triggers = 0",
                 "Retry on timeout"],
     "answer": 0,
     "explanation": "Wait after last change debounces: the run starts only after no new file has arrived for that long (each new file resets the timer). Minimum time between triggers limits the run frequency."},
    {"topic": "Triggers & schedules",
     "q": "Which statement about file arrival triggers is true?",
     "options": ["It fires within one second of the upload",
                 "Overwriting an existing file with the same name does not trigger a run",
                 "It only works on DBFS mounts",
                 "The trigger passes the list of new files to the task automatically"],
     "answer": 1,
     "explanation": "Only new files trigger runs; the task must determine which files are new (Auto Loader, COPY INTO, checkpoints). Checks are best-effort about every minute."},
    {"topic": "Triggers & schedules",
     "q": "Which objects can a **table update** trigger monitor? (Choose TWO)",
     "options": ["CSV files in a workspace folder",
                 "Hive metastore tables on DBFS mounts",
                 "Unity Catalog managed or external Delta tables",
                 "Materialized views and streaming tables"],
     "answer": [2, 3],
     "explanation": "UC Delta (and Iceberg) tables, materialized views, streaming tables, views/metric views, shared and system tables — up to 10 per trigger."},
    {"topic": "Triggers & schedules",
     "q": "A job watches three tables with a table update trigger and must start only when **all three** have been refreshed. What do you configure?",
     "options": ["Condition Any updated + retries",
                 "Three separate jobs",
                 "Minimum time between triggers = 3",
                 "Condition All updated"],
     "answer": 3,
     "explanation": "Table update triggers support Any updated or All updated across the monitored tables."},
    {"topic": "Triggers & schedules",
     "q": "Which statements describe a **continuous** job? (Choose TWO)",
     "options": ["It also accepts a cron schedule",
                 "There is always exactly one active run; a new one starts when the previous ends",
                 "Failed runs are retried with exponential back-off",
                 "It runs each task in parallel forever"],
     "answer": [1, 2],
     "explanation": "Continuous jobs keep one run active and retry with exponential back-off; they don't combine with a schedule."},
    # ---------------- Time-based vs data-driven ----------------
    {"topic": "Time-based vs data-driven",
     "q": "The gold job must start after the silver pipeline of another team, whose duration varies from 20 to 90 minutes. Best trigger?",
     "options": ["A file arrival trigger on the workspace folder",
                 "Table update trigger on the silver table",
                 "A continuous job polling the table",
                 "A schedule 2 hours after the silver schedule"],
     "answer": 1,
     "explanation": "Data-driven: start when the upstream table is actually updated. Offset schedules either wait too long or run on stale data."},
    {"topic": "Time-based vs data-driven",
     "q": "Finance needs a report e-mailed every Monday at 07:00 regardless of when the data was last updated. Which trigger?",
     "options": ["Table update",
                 "Continuous",
                 "Scheduled (time-based)",
                 "File arrival"],
     "answer": 2,
     "explanation": "A business deadline at a fixed time → time-based schedule."},
    {"topic": "Time-based vs data-driven",
     "q": "A vendor drops order files into a volume at unpredictable times; they must be processed within minutes. Which trigger is best?",
     "options": ["Table update trigger on the volume",
                 "Manual runs",
                 "Schedule every 1 minute",
                 "File arrival trigger on the volume path"],
     "answer": 3,
     "explanation": "File arrival starts runs only when new files land — fresh data without idle polling runs."},
    {"topic": "Time-based vs data-driven",
     "q": "Ingestion, a pipeline update and a dashboard refresh must always happen in this order, once per night. What is the best design?",
     "options": ["One job: ingestion task → pipeline task → dashboard task, with dependencies and one trigger",
                 "A continuous pipeline and a dashboard schedule",
                 "Three jobs scheduled at 01:00, 02:00 and 03:00",
                 "Three notebooks run by %run from one notebook"],
     "answer": 0,
     "explanation": "Dependencies inside one job guarantee the order whatever the durations; one trigger starts the whole chain."},
    {"topic": "Time-based vs data-driven",
     "q": "What is a drawback of time-based triggers for data pipelines?",
     "options": ["They can't be paused",
                 "They run even when no new data arrived, or before late data is complete",
                 "They require a SQL warehouse",
                 "They can't run notebooks"],
     "answer": 1,
     "explanation": "Schedules ignore data availability: wasted runs when nothing arrived, stale results when the source is late."},
    # ---------------- Monitoring & permissions ----------------
    {"topic": "Monitoring & permissions",
     "q": "Which job permission allows a user to trigger runs and repair failed runs, but not to edit the job?",
     "options": ["CAN MANAGE",
                 "CAN VIEW",
                 "CAN MANAGE RUN",
                 "IS OWNER"],
     "answer": 2,
     "explanation": "CAN VIEW < CAN MANAGE RUN (run, cancel, repair) < CAN MANAGE (edit, permissions, delete); IS OWNER is the single owner."},
    {"topic": "Monitoring & permissions",
     "q": "Whose Unity Catalog permissions do the tasks of a job use when it runs?",
     "options": ["The user who clicked Run now",
                 "Always the account admin",
                 "The workspace admin",
                 "The job's run-as identity (the owner by default, ideally a service principal)"],
     "answer": 3,
     "explanation": "Jobs run as the run-as identity. Production best practice: a service principal, so the job doesn't depend on a person."},
    {"topic": "Monitoring & permissions",
     "q": "You need a report of all failed job runs across the workspace over the last 30 days, in SQL. Which source?",
     "options": ["`system.lakeflow.job_run_timeline`",
                 "`DESCRIBE HISTORY` of each job",
                 "`information_schema.jobs`",
                 "The cluster event log"],
     "answer": 0,
     "explanation": "The Lakeflow system tables (jobs, job_tasks, job_run_timeline, job_task_run_timeline…) record job runs for SQL analysis."},
    {"topic": "Monitoring & permissions",
     "q": "Which view of the Runs tab shows one row per task and one column per run, to spot a task that fails or slows down repeatedly?",
     "options": ["Timeline view of a single run",
                 "Matrix view",
                 "The job's YAML",
                 "The Spark UI"],
     "answer": 1,
     "explanation": "The matrix view compares tasks across runs; the timeline (Gantt) view shows the durations inside one run."},
]

render_quiz(questions, title="Section 10 · Lakeflow Jobs", pass_mark=0.8,
            meta="58 questions · jobs & task types, compute, parameters & task values, control flow, reliability & repair, triggers & schedules, time-based vs data-driven, monitoring & permissions · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Jobs & task types · Compute, parameters & task values · Monitoring & permissions | `presentation/10-P1 - Lakeflow Jobs Fundamentals` + `labs/10-L1` |
# MAGIC | Control flow · Reliability & repair | `presentation/10-P2 - Control Flow, Retries and Repair` + `labs/10-L2` |
# MAGIC | Triggers & schedules · Time-based vs data-driven | `presentation/10-P3 - Triggers, Schedules and Orchestration Patterns` + `labs/10-L3`, `10-L4` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
