# Databricks notebook source
# MAGIC %md
# MAGIC # 🗂️ 00-D · ShopWave Dataset Tour & Data Dictionary
# MAGIC
# MAGIC This notebook creates (if needed) and **previews** every raw dataset used in the course.
# MAGIC All data lives in the Unity Catalog volume **`/Volumes/<catalog>/shopwave/raw/`** and is generated by `Includes/_setup`
# MAGIC with a fixed random seed, so your numbers match the ones in the labs and questions.
# MAGIC
# MAGIC > We only **read files** here. Turning them into tables is what sections 03–08 teach.

# COMMAND ----------

# MAGIC %run ../../Includes/_setup

# COMMAND ----------

# MAGIC %md
# MAGIC ## 📁 What's in the raw volume

# COMMAND ----------

# DBTITLE 1,Folder listing with file counts
rows = []
for d in dbutils.fs.ls(dataset_path):
    files = [f for f in dbutils.fs.ls(d.path) if not f.name.startswith(("_", "."))]
    rows.append((d.name, len(files), sum(f.size for f in files)))
display(spark.createDataFrame(rows, "folder string, files int, bytes long"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 👤 customers-json — 300 customers, 3 JSON-lines files
# MAGIC
# MAGIC | Column | Type | Notes |
# MAGIC |---|---|---|
# MAGIC | `customer_id` | string | `C0001` … `C0300` — primary key |
# MAGIC | `email` | string | ⚠️ ~5 % are **null** |
# MAGIC | `profile` | string | a **JSON document stored as text**: `first_name`, `last_name`, `gender`, `address{street, city, country}` |
# MAGIC | `updated` | string | ISO-8601 timestamp of last profile change |

# COMMAND ----------

# DBTITLE 1,Preview customers
customers_df = spark.read.json(f"{dataset_path}/customers-json")
display(customers_df.limit(10))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 📦 products-csv — 36 products, 2 CSV files
# MAGIC Delimiter **`;`**, first line is a **header**.
# MAGIC
# MAGIC | Column | Type | Notes |
# MAGIC |---|---|---|
# MAGIC | `product_id` | string | `P001` … `P036` |
# MAGIC | `title` | string | product name |
# MAGIC | `brand` | string | |
# MAGIC | `category` | string | Electronics, Home & Kitchen, Books, Sports, Beauty, Toys |
# MAGIC | `price` | double | unit price (USD) |

# COMMAND ----------

# DBTITLE 1,Preview products
products_df = (spark.read
               .option("header", "true")
               .option("delimiter", ";")
               .option("inferSchema", "true")
               .csv(f"{dataset_path}/products-csv"))
display(products_df)

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🛍️ orders-parquet — 2,010 historical orders (Jan–Jun 2026)
# MAGIC
# MAGIC | Column | Type | Notes |
# MAGIC |---|---|---|
# MAGIC | `order_id` | string | `O000001` … — ⚠️ a few **exact duplicates** |
# MAGIC | `order_timestamp` | long | **Unix epoch seconds** → convert with `from_unixtime()` / `timestamp_seconds()` |
# MAGIC | `customer_id` | string | FK → customers · ⚠️ some orders use unknown customer **`C9999`** |
# MAGIC | `quantity` | int | total items in the order · ⚠️ **0** for cancelled orders |
# MAGIC | `total` | double | order amount (USD) |
# MAGIC | `items` | array&lt;struct&lt;product_id, quantity, subtotal&gt;&gt; | nested line items |

# COMMAND ----------

# DBTITLE 1,Preview orders
orders_df = spark.read.parquet(f"{dataset_path}/orders-parquet")
orders_df.printSchema()
display(orders_df.limit(10))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🌊 orders-staging → orders-landing — simulated arriving files
# MAGIC * `orders-staging/` holds 10 JSON batches (`01.json` … `10.json`, ~120 orders each, July 2026).
# MAGIC * `orders-landing/` is the folder your **streaming / Auto Loader** code will watch. Batch `01` is already there.
# MAGIC * `land_new_orders()` copies the next batch; `land_new_orders(all=True)` copies all remaining; `reset_orders_landing()` starts over.

# COMMAND ----------

# DBTITLE 1,Landing folder status
display(dbutils.fs.ls(f"{dataset_path}/orders-landing"))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔍 The deliberate data-quality issues
# MAGIC You will detect and fix these in sections 07–08. Here is proof they exist:

# COMMAND ----------

# DBTITLE 1,Data quality summary
from pyspark.sql import functions as F

summary = [
    ("customers with null email", customers_df.where(F.col("email").isNull()).count()),
    ("orders with quantity = 0 (cancelled)", orders_df.where("quantity = 0").count()),
    ("orders from unknown customer C9999", orders_df.where("customer_id = 'C9999'").count()),
    ("exact duplicate order rows", orders_df.count() - orders_df.distinct().count()),
]
display(spark.createDataFrame(summary, "issue string, rows long"))
