# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 03-Q · Exam Questions — Delta Lake
# MAGIC **36 exam-style questions** on the transaction log (03-P1), working with Delta tables (03-P2) and time travel, clones &
# MAGIC maintenance (03-P3). Target **≥ 80 %** before Section 04.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Fundamentals ----------------
    {"topic": "Fundamentals",
     "q": "What does a Delta Lake table consist of on cloud storage?",
     "options": ["A proprietary binary file managed by a Delta server", "Parquet data files plus a `_delta_log` transaction log of JSON commits and Parquet checkpoints",
                 "CSV files plus an index file", "Rows stored in the Unity Catalog metastore database"],
     "answer": 1,
     "explanation": "Delta = open Parquet data files + the transaction log. The log (JSON commits, periodic checkpoints) defines which files belong to each version."},
    {"topic": "Fundamentals",
     "q": "A Parquet file sits in a Delta table's folder but is **not referenced** in the transaction log. What is it?",
     "options": ["Part of the current table version", "Not part of the table (e.g. an uncommitted or removed file) — readers ignore it",
                 "A checkpoint", "A corrupted table that must be repaired"],
     "answer": 1,
     "explanation": "The log is the source of truth. Unreferenced files come from failed writes or were removed by later commits; VACUUM cleans them up after the retention period."},
    {"topic": "Fundamentals",
     "q": "A job writing to a Delta table crashes half-way. What do readers see?",
     "options": ["The partially written rows", "An error until someone repairs the table",
                 "The last committed version — the failed write never created a commit (atomicity)", "An empty table"],
     "answer": 2,
     "explanation": "Data files are written first; the commit file is created atomically at the end. No commit → the new files are invisible."},
    {"topic": "Fundamentals",
     "q": "An `UPDATE` changes 5 rows in a Delta table **without deletion vectors**. What happens to the Parquet file that contained them?",
     "options": ["It is modified in place", "A new file with the updated rows (and the unchanged rows of that file) is written, and the old file is marked as removed in the log",
                 "Only the 5 rows are appended to a new file; the old rows stay visible", "The file is deleted from storage immediately"],
     "answer": 1,
     "explanation": "Parquet files are immutable (copy-on-write): the log records `remove` for the old file and `add` for the new one. The old file stays on storage for time travel until VACUUM."},
    {"topic": "Fundamentals",
     "q": "With **deletion vectors** enabled, what does a `DELETE` of a few rows typically do?",
     "options": ["Rewrites every file of the table", "Writes small deletion-vector files that mark the rows as deleted; the Parquet files are rewritten later (OPTIMIZE / REORG … PURGE)",
                 "Moves the rows to a quarantine table", "Deletes the rows only from the checkpoint"],
     "answer": 1,
     "explanation": "Deletion vectors (merge-on-read) avoid rewriting whole files for small changes. Physical removal happens when files are rewritten and then VACUUMed."},
    {"topic": "Fundamentals",
     "q": "Two jobs append to the same Delta table at the same time. What does Delta use to keep the table consistent?",
     "options": ["Table-level locks held for the whole job", "Optimistic concurrency control: each writer tries to commit the next version; non-conflicting appends are retried automatically",
                 "The second job always fails", "Writes are queued in the control plane"],
     "answer": 1,
     "explanation": "Writers don't lock; they check for conflicts at commit time. Blind appends don't conflict; conflicting changes (e.g. both updating the same files) fail with a concurrent modification error."},
    {"topic": "Fundamentals",
     "q": "Which **two** features does a Delta table have that an external CSV table does **not**?",
     "options": ["ACID transactions", "Can be queried with SQL", "Time travel", "Stored in cloud object storage"],
     "answer": [0, 2],
     "explanation": "Both are SQL-queryable and live in object storage; only Delta adds transactions, DML, time travel and schema enforcement."},

    # ---------------- Working with tables ----------------
    {"topic": "Working with tables",
     "q": "Which statement creates a table **and** fills it, taking the schema from the query?",
     "options": ["`CREATE TABLE t (id INT, name STRING)`", "`CREATE TABLE t AS SELECT id, name FROM src`", "`INSERT INTO t SELECT * FROM src`", "`ALTER TABLE t ADD COLUMNS (id INT)`"],
     "answer": 1,
     "explanation": "CTAS (CREATE TABLE AS SELECT) infers the schema from the query result and loads the data in one step."},
    {"topic": "Working with tables",
     "q": "You need to rebuild table `sales` from a query whose result has **one extra column**, keeping the table's history. Which statement works?",
     "options": ["`INSERT OVERWRITE sales SELECT ...`", "`DROP TABLE sales; CREATE TABLE sales AS SELECT ...`",
                 "`CREATE OR REPLACE TABLE sales AS SELECT ...`", "`INSERT INTO sales SELECT ...`"],
     "answer": 2,
     "explanation": "CREATE OR REPLACE atomically replaces data and schema and keeps the history. INSERT OVERWRITE requires the existing schema; DROP + CREATE loses the history."},
    {"topic": "Working with tables",
     "q": "A nightly job runs `INSERT INTO orders SELECT * FROM staging`. It fails after writing and is automatically retried. What is the risk?",
     "options": ["None — INSERT INTO is idempotent", "The same rows may be appended twice (duplicates)",
                 "The table is dropped", "The schema is changed"],
     "answer": 1,
     "explanation": "INSERT INTO blindly appends. Use MERGE (insert-only), COPY INTO or overwrite semantics for idempotent loads."},
    {"topic": "Working with tables",
     "q": "What is the difference between `INSERT OVERWRITE t SELECT …` and `CREATE OR REPLACE TABLE t AS SELECT …`?",
     "options": ["There is no difference", "INSERT OVERWRITE replaces only the data and requires a compatible schema; CREATE OR REPLACE can also change the schema and table definition",
                 "INSERT OVERWRITE deletes the table history", "CREATE OR REPLACE appends data"],
     "answer": 1,
     "explanation": "Both create a new version and keep the history. Only CREATE OR REPLACE may change schema, properties and comments."},
    {"topic": "Working with tables",
     "q": "Which `MERGE` inserts rows from `s` that don't exist in `t` and **never modifies existing rows**?",
     "code": "MERGE INTO t USING s ON t.id = s.id\n???",
     "options": ["`WHEN MATCHED THEN UPDATE SET *`", "`WHEN NOT MATCHED THEN INSERT *`", "`WHEN NOT MATCHED BY SOURCE THEN DELETE`", "`WHEN MATCHED THEN DELETE`"],
     "answer": 1,
     "explanation": "An insert-only MERGE is the standard way to deduplicate on load: re-running it inserts nothing new."},
    {"topic": "Working with tables",
     "q": "A MERGE fails with *\"multiple source rows matched and attempted to modify the same target row\"*. What is the fix?",
     "options": ["Add more compute", "Deduplicate the source so each key appears once (e.g. keep the latest row per key)",
                 "Use INSERT INTO instead", "Disable schema enforcement"],
     "answer": 1,
     "explanation": "When several source rows match one target row in an UPDATE/DELETE clause, Delta can't choose. Deduplicate the source first (row_number over key ordered by timestamp)."},
    {"topic": "Working with tables",
     "q": "Which clause removes target rows that **no longer exist in the source** during a MERGE?",
     "options": ["`WHEN NOT MATCHED THEN DELETE`", "`WHEN NOT MATCHED BY SOURCE THEN DELETE`", "`WHEN MATCHED THEN DELETE`", "`DELETE WHERE NOT EXISTS`"],
     "answer": 1,
     "explanation": "NOT MATCHED BY SOURCE targets rows in the target with no matching source row. NOT MATCHED (BY TARGET) is about source rows missing from the target — you can only INSERT there."},
    {"topic": "Working with tables",
     "q": "`df` has a new column `discount` that the Delta table `orders` doesn't have. `df.write.mode('append').saveAsTable('orders')` fails. How do you add the column as part of the append?",
     "options": ["`.option(\"mergeSchema\", \"true\")`", "`.option(\"inferSchema\", \"true\")`", "`.mode(\"ignore\")`", "`.option(\"header\", \"true\")`"],
     "answer": 0,
     "explanation": "mergeSchema enables schema evolution for the write: new columns are added, existing rows get NULL. Without it, schema enforcement rejects the write."},
    {"topic": "Working with tables",
     "q": "Which write is **rejected** by Delta's schema enforcement by default?",
     "options": ["An append that omits a nullable column", "An append with an additional column not in the table",
                 "An append with the same columns in a different order (by-name write)", "An append of zero rows"],
     "answer": 1,
     "explanation": "Unknown extra columns (or incompatible types) are rejected. Missing nullable columns are filled with NULL."},
    {"topic": "Working with tables",
     "q": "How do you add a rule that `price` must be positive to an existing Delta table?",
     "options": ["`ALTER TABLE products ADD CONSTRAINT positive_price CHECK (price > 0)`", "`ALTER TABLE products ALTER COLUMN price SET POSITIVE`",
                 "`CREATE CONSTRAINT positive_price ON products`", "It isn't possible on Delta tables"],
     "answer": 0,
     "explanation": "CHECK constraints are added with ALTER TABLE ADD CONSTRAINT; existing rows must satisfy it, and violating writes fail as a whole."},
    {"topic": "Working with tables",
     "q": "Which command shows a Delta table's **number of files** and **size in bytes**?",
     "options": ["`DESCRIBE HISTORY t`", "`DESCRIBE DETAIL t`", "`SHOW TABLES`", "`DESCRIBE t`"],
     "answer": 1,
     "explanation": "DESCRIBE DETAIL returns format, location, numFiles, sizeInBytes, partition/clustering columns, properties and features."},

    # ---------------- Time travel & maintenance ----------------
    {"topic": "Time travel & maintenance",
     "q": "Which **two** queries read version 5 of table `orders`?",
     "options": ["`SELECT * FROM orders VERSION AS OF 5`", "`SELECT * FROM orders@v5`", "`SELECT * FROM orders WHERE _version = 5`", "`SELECT * FROM orders_v5`"],
     "answer": [0, 1],
     "explanation": "VERSION AS OF n and the @vN shorthand are equivalent. TIMESTAMP AS OF works with a time."},
    {"topic": "Time travel & maintenance",
     "q": "A bad `DELETE` created version 12. You run `RESTORE TABLE t TO VERSION AS OF 11`. What happens to the history?",
     "options": ["Versions after 11 are erased", "A new version 13 is committed whose content equals version 11; version 12 stays in the history",
                 "The table is recreated at version 0", "Nothing — RESTORE only works on external tables"],
     "answer": 1,
     "explanation": "RESTORE is a normal commit. History is append-only; you can still query version 12."},
    {"topic": "Time travel & maintenance",
     "q": "Which command lists operations, users, timestamps and metrics of every change made to a table?",
     "options": ["`DESCRIBE DETAIL`", "`DESCRIBE HISTORY`", "`SHOW TBLPROPERTIES`", "`SHOW GRANTS`"],
     "answer": 1,
     "explanation": "DESCRIBE HISTORY exposes the commitInfo of each version: operation, parameters, user, timestamp and operationMetrics."},
    {"topic": "Time travel & maintenance",
     "q": "What is the **default** retention threshold used by `VACUUM`?",
     "options": ["1 day", "7 days", "30 days", "No retention — it deletes everything unreferenced immediately"],
     "answer": 1,
     "explanation": "7 days (delta.deletedFileRetentionDuration). The transaction log itself is kept 30 days by default (delta.logRetentionDuration)."},
    {"topic": "Time travel & maintenance",
     "q": "After `VACUUM t` with the default retention, which statement is true?",
     "options": ["You can still time travel to any version", "You can no longer time travel to versions whose data files were older than the retention and have been deleted",
                 "The transaction log is deleted", "The table is converted to Parquet"],
     "answer": 1,
     "explanation": "VACUUM removes old unreferenced data files, so versions depending on them can't be read anymore. The log is not deleted by VACUUM."},
    {"topic": "Time travel & maintenance",
     "q": "`VACUUM t RETAIN 0 HOURS` fails with a retention-check error. What does this protect against?",
     "options": ["Deleting files that concurrent or long-running readers/writers may still need, and losing time travel", "Running out of storage",
                 "Unauthorized users", "Schema changes"],
     "answer": 0,
     "explanation": "Retention below the table's threshold is blocked unless spark.databricks.delta.retentionDurationCheck.enabled is set to false — only do that when you're sure nothing else uses the table."},
    {"topic": "Time travel & maintenance",
     "q": "Which command previews the files VACUUM would delete **without deleting them**?",
     "options": ["`VACUUM t DRY RUN`", "`VACUUM t PREVIEW`", "`DESCRIBE VACUUM t`", "`OPTIMIZE t DRY RUN`"],
     "answer": 0,
     "explanation": "DRY RUN returns (up to 1,000) files that would be removed."},
    {"topic": "Time travel & maintenance",
     "q": "A streaming job created 50,000 small files in a Delta table and queries are slow. Which command compacts them?",
     "options": ["`VACUUM`", "`OPTIMIZE`", "`REFRESH TABLE`", "`ANALYZE TABLE`"],
     "answer": 1,
     "explanation": "OPTIMIZE bin-packs small files into larger ones. VACUUM later deletes the replaced small files after the retention period."},
    {"topic": "Time travel & maintenance",
     "q": "What does `OPTIMIZE events ZORDER BY (customer_id)` add compared to a plain `OPTIMIZE events`?",
     "options": ["It creates an index file", "It co-locates rows with similar customer_id values in the same files so filters on customer_id skip more files",
                 "It partitions the table by customer_id into folders", "It deletes duplicate customer_ids"],
     "answer": 1,
     "explanation": "Z-ordering sorts data along the given columns during compaction, improving data skipping via file min/max stats. Unlike plain OPTIMIZE it isn't idempotent (re-running can rewrite data again), and it doesn't create directories — that would be partitioning."},
    {"topic": "Time travel & maintenance",
     "q": "The team needs a **full, independent backup** of a production table — a copy with its own data files that doesn't depend on the source table at all. Which command?",
     "options": ["`CREATE TABLE b SHALLOW CLONE prod`", "`CREATE TABLE b DEEP CLONE prod`", "`CREATE VIEW b AS SELECT * FROM prod`", "`CREATE TABLE b LIKE prod`"],
     "answer": 1,
     "explanation": "A deep clone copies data and metadata, so it's fully independent. A shallow clone only references the source's files (in the legacy Hive metastore it even breaks when the source is vacuumed; Unity Catalog protects referenced files); a view stores no data."},
    {"topic": "Time travel & maintenance",
     "q": "Which statement about a **shallow clone** is correct?",
     "options": ["Updates on the clone also change the source table", "It copies only metadata and references the source's data files, so it's created almost instantly",
                 "It is always slower than a deep clone", "It can't be modified"],
     "answer": 1,
     "explanation": "Shallow clones are cheap metadata copies; writes to the clone go to the clone's own new files, never to the source."},
    {"topic": "Time travel & maintenance",
     "q": "A Unity Catalog **managed** table was dropped by mistake yesterday. How do you recover it?",
     "options": ["`RESTORE TABLE t TO VERSION AS OF 0`", "`UNDROP TABLE t`", "It's impossible — managed table data is deleted immediately", "`CREATE TABLE t DEEP CLONE t`"],
     "answer": 1,
     "explanation": "UNDROP recovers dropped Unity Catalog tables within the retention window (7 days by default). SHOW TABLES DROPPED lists them."},
    {"topic": "Working with tables",
     "q": "A daily job must **re-process only 2026-09-25** in a large Delta table, replacing that day's rows atomically without touching other days. Which approach fits?",
     "options": ["`INSERT OVERWRITE sales SELECT … WHERE order_date = '2026-09-25'`",
                 "`INSERT INTO sales REPLACE WHERE order_date = '2026-09-25' SELECT …` (or `replaceWhere` in Python)",
                 "`DELETE FROM sales` followed by `INSERT INTO sales`", "`CREATE OR REPLACE TABLE sales AS SELECT …`"],
     "answer": 1,
     "explanation": "REPLACE WHERE / replaceWhere atomically replaces only rows matching the predicate. A plain INSERT OVERWRITE would replace the whole (non-partitioned) table; two separate statements aren't atomic."},
    {"topic": "Time travel & maintenance",
     "q": "Which PySpark code reads version 7 of the table `sales.orders`?",
     "options": ["`spark.table(\"sales.orders\").version(7)`", "`spark.read.option(\"versionAsOf\", 7).table(\"sales.orders\")`",
                 "`spark.read.table(\"sales.orders@7\")`", "`spark.read.format(\"history\").load(\"sales.orders\", 7)`"],
     "answer": 1,
     "explanation": "The DataFrame reader options versionAsOf / timestampAsOf do time travel in Python. In SQL: VERSION AS OF 7 or sales.orders@v7."},
    {"topic": "Time travel & maintenance",
     "q": "Nobody on the team schedules OPTIMIZE or VACUUM, yet the Unity Catalog **managed** tables stay compacted and old files get cleaned up. What explains this?",
     "options": ["Delta tables never need maintenance", "Predictive optimization runs OPTIMIZE and VACUUM automatically for UC managed tables",
                 "The SQL warehouse vacuums tables when it stops", "Auto Loader compacts the tables"],
     "answer": 1,
     "explanation": "Predictive optimization analyses usage and triggers maintenance (OPTIMIZE, VACUUM, ANALYZE) for Unity Catalog managed tables — one reason to prefer managed tables."},
    {"topic": "Working with tables",
     "q": "`orders` must always store `order_date` derived from `order_ts`, without the loading jobs computing it. What do you use?",
     "code": "CREATE TABLE orders (\n  order_id   STRING,\n  order_ts   TIMESTAMP,\n  order_date DATE ???\n)",
     "options": ["`DEFAULT current_date()`", "`GENERATED ALWAYS AS (CAST(order_ts AS DATE))`",
                 "`GENERATED ALWAYS AS IDENTITY`", "`CHECK (order_date = CAST(order_ts AS DATE))`"],
     "answer": 1,
     "explanation": "A generated column is computed by Delta on every write from its expression. IDENTITY generates surrogate keys; a CHECK would only validate a value the job still has to supply. Generated columns must be declared at CREATE TABLE (not via CTAS)."},
    {"topic": "Time travel & maintenance",
     "q": "Rows disappeared from `sales.orders` last night. How do you find **who** ran the change and **which operation** it was?",
     "options": ["`DESCRIBE DETAIL sales.orders`", "`DESCRIBE HISTORY sales.orders` — columns userName, operation, operationParameters",
                 "`SHOW GRANTS ON sales.orders`", "`SHOW TBLPROPERTIES sales.orders`"],
     "answer": 1,
     "explanation": "The history (from the transaction log) records version, timestamp, userName, operation (e.g. DELETE), its parameters (the predicate) and metrics for every commit."},
    {"topic": "Working with tables",
     "q": "Which statement creates an **external** Delta table from a query?",
     "options": ["`CREATE TABLE t AS SELECT * FROM src`", "`CREATE TABLE t LOCATION 's3://bucket/tables/t' AS SELECT * FROM src`",
                 "`CREATE TABLE t PARTITIONED BY (d) AS SELECT * FROM src`", "`CREATE EXTERNAL VIEW t AS SELECT * FROM src`"],
     "answer": 1,
     "explanation": "Specifying LOCATION makes the table external: its files live at your path and aren't deleted when the table is dropped. Without LOCATION the table is managed. (Managed vs external in depth → Section 04.)"},
]

render_quiz(questions, title="Section 03 · Delta Lake", pass_mark=0.8,
            meta="36 questions · transaction log, writes & MERGE, time travel, clones, OPTIMIZE & VACUUM · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Fundamentals | `presentation/03-P1 - Delta Lake and the Transaction Log` |
# MAGIC | Working with tables | `presentation/03-P2 - Working with Delta Tables` + `labs/03-L1`, `labs/03-L2` Parts 1–4 |
# MAGIC | Time travel & maintenance | `presentation/03-P3 - Time Travel, Clones and Maintenance` + `labs/03-L2` Parts 5–7 |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
