# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 13-Q · Exam Questions — Governance and Security
# MAGIC **60 exam-style questions** on identities and privileges (13-P1), row/column security and ABAC (13-P2) and managed vs
# MAGIC external tables, lineage and audit (13-P3). Multi-answer questions say so. Target **≥ 80 %** before Section 14.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Identities & roles ----------------
    {"topic": "Identities & roles",
     "q": "Which principal should a production job run as, so that it doesn't depend on a person's account?",
     "options": ["A service principal",
                 "A workspace-local group",
                 "The workspace admin's user",
                 "The account users group"],
     "answer": 0,
     "explanation": "Service principals are identities for automation (identified by an application ID). Jobs, CI/CD and apps should run as service principals."},
    {"topic": "Identities & roles",
     "q": "Which statements about groups in Unity Catalog are true? (Choose TWO)",
     "options": ["A group can't own a table",
                 "Grants should preferably go to groups rather than to individual users",
                 "Only workspace-local groups can receive Unity Catalog grants",
                 "Groups can contain users, service principals and other groups (nesting)"],
     "answer": [1, 3],
     "explanation": "Account groups can be nested and are the recommended grantees and owners. Workspace-local groups are legacy and can't be used in UC grants."},
    {"topic": "Identities & roles",
     "q": "What does **identity federation** give you?",
     "options": ["Users can log in without any identity provider",
                 "Unity Catalog grants are copied into every workspace's Hive metastore",
                 "Users, service principals and groups are managed once at the account level and assigned to many workspaces",
                 "Each workspace keeps its own separate users"],
     "answer": 2,
     "explanation": "With identity federation, identities live in the account (often synced by SCIM from the IdP) and are assigned to workspaces — same identity everywhere."},
    {"topic": "Identities & roles",
     "q": "Which role creates metastores and assigns them to workspaces in the account console?",
     "options": ["Metastore admin",
                 "Catalog owner",
                 "Workspace admin",
                 "Account admin"],
     "answer": 3,
     "explanation": "Account admins manage the account: metastores, workspaces, identities. Metastore admins manage objects and grants inside a metastore; workspace admins manage a workspace."},
    {"topic": "Identities & roles",
     "q": "Which function should a dynamic view use to test membership of an **account** group in Unity Catalog?",
     "options": ["`is_account_group_member('grp')`",
                 "`current_group()`",
                 "`is_member('grp')`",
                 "`has_role('grp')`"],
     "answer": 0,
     "explanation": "is_account_group_member checks account-level groups (incl. nested membership). is_member checks legacy workspace-local groups."},
    {"topic": "Identities & roles",
     "q": "What does `current_user()` return inside a row filter evaluated for a scheduled job?",
     "options": ["The user who created the table",
                 "The job's run-as identity",
                 "The workspace admin",
                 "NULL"],
     "answer": 1,
     "explanation": "Filters and masks are evaluated for the principal running the query — for a job, its run-as user or service principal."},
    {"topic": "Identities & roles",
     "q": "Which built-in group contains every user and service principal of the account?",
     "options": ["`users`",
                 "`all_principals`",
                 "`account users`",
                 "`admins`"],
     "answer": 2,
     "explanation": "`account users` contains all account identities. `admins` and `users` are workspace-local groups."},
    # ---------------- Ownership & privileges ----------------
    {"topic": "Ownership & privileges",
     "q": "An analyst must run `SELECT * FROM prod.sales.orders`. What is the minimum set of privileges?",
     "options": ["ALL PRIVILEGES on the schema",
                 "USE SCHEMA and SELECT only",
                 "SELECT on the table only",
                 "USE CATALOG on prod, USE SCHEMA on prod.sales, SELECT on the table"],
     "answer": 3,
     "explanation": "Reading needs USE CATALOG and USE SCHEMA on the parents plus SELECT on the table (or SELECT inherited from the schema/catalog)."},
    {"topic": "Ownership & privileges",
     "q": "A user has SELECT on a table and USE SCHEMA on its schema, but gets an error that the catalog can't be found or accessed. What is missing?",
     "options": ["USE CATALOG on the catalog",
                 "BROWSE on the table",
                 "CREATE SCHEMA on the catalog",
                 "MODIFY on the table"],
     "answer": 0,
     "explanation": "Without USE CATALOG the user can't reach anything in the catalog, whatever privileges exist below."},
    {"topic": "Ownership & privileges",
     "q": "Data engineers must INSERT, UPDATE and DELETE rows of `sec_orders`. Which privilege allows these changes?",
     "options": ["WRITE FILES",
                 "MODIFY",
                 "SELECT",
                 "CREATE TABLE"],
     "answer": 1,
     "explanation": "MODIFY allows adding, updating and deleting data in a table. (SELECT is also needed to read what you change.)"},
    {"topic": "Ownership & privileges",
     "q": "Analysts must create their own tables and views in schema `sandbox`. Which privilege on the schema?",
     "options": ["MODIFY",
                 "CREATE SCHEMA",
                 "CREATE TABLE",
                 "ALL PRIVILEGES on the catalog"],
     "answer": 2,
     "explanation": "CREATE TABLE on a schema allows creating tables and views in it (plus USE CATALOG/USE SCHEMA). CREATE SCHEMA is granted on a catalog."},
    {"topic": "Ownership & privileges",
     "q": "Which privilege lets a user read the files of a Unity Catalog **volume**?",
     "options": ["USE VOLUME",
                 "SELECT",
                 "READ FILES",
                 "READ VOLUME"],
     "answer": 3,
     "explanation": "Volumes use READ VOLUME / WRITE VOLUME. READ FILES / WRITE FILES are privileges on external locations (path-based access)."},
    {"topic": "Ownership & privileges",
     "q": "Which privilege is required to call a SQL UDF owned by somebody else?",
     "options": ["EXECUTE on the function",
                 "SELECT on the function",
                 "MODIFY on the schema",
                 "USE FUNCTION"],
     "answer": 0,
     "explanation": "EXECUTE on the function (or inherited from its schema/catalog), plus USE CATALOG and USE SCHEMA."},
    {"topic": "Ownership & privileges",
     "q": "Who can grant privileges on a table in Unity Catalog? (Choose THREE)",
     "options": ["Any workspace user",
                 "Any user with SELECT on the table",
                 "A principal with MANAGE on the table",
                 "The owner of the table's schema or catalog",
                 "The table owner"],
     "answer": [2, 3, 4],
     "explanation": "Owners, owners of the parent schema/catalog, principals with MANAGE and metastore admins can grant. SELECT doesn't allow granting."},
    {"topic": "Ownership & privileges",
     "q": "What is true about the **MANAGE** privilege?",
     "options": ["It is the same as ALL PRIVILEGES",
                 "It can only be held by the owner",
                 "It allows managing grants, transferring ownership and dropping the object, without implying data access",
                 "It is included in ALL PRIVILEGES"],
     "answer": 2,
     "explanation": "MANAGE is similar to ownership for administration but doesn't grant data privileges; ALL PRIVILEGES does not include MANAGE."},
    {"topic": "Ownership & privileges",
     "q": "`GRANT ALL PRIVILEGES ON TABLE t TO grp` — what does `SHOW GRANTS ON TABLE t` list for grp?",
     "options": ["Nothing — ALL PRIVILEGES is invisible",
                 "OWNER",
                 "SELECT, MODIFY, … one row per privilege",
                 "`ALL PRIVILEGES` (not each implied privilege)"],
     "answer": 3,
     "explanation": "ALL PRIVILEGES is evaluated at check time (it also covers privileges added later) and is shown as ALL PRIVILEGES."},
    {"topic": "Ownership & privileges",
     "q": "How do you make the group `data_platform` the owner of the catalog `prod`?",
     "options": ["``ALTER CATALOG prod OWNER TO `data_platform` ``",
                 "`SET OWNER prod = data_platform`",
                 "`GRANT OWNERSHIP ON CATALOG prod TO data_platform`",
                 "`GRANT ALL PRIVILEGES ON CATALOG prod TO data_platform`"],
     "answer": 0,
     "explanation": "Ownership is transferred with ALTER <securable> <name> OWNER TO <principal>. Granting ALL PRIVILEGES doesn't change the owner."},
    {"topic": "Ownership & privileges",
     "q": "Who owns a new table by default?",
     "options": ["Nobody until ownership is assigned",
                 "The principal that created it",
                 "The metastore admin",
                 "The schema owner"],
     "answer": 1,
     "explanation": "The creator becomes the owner; transfer it to a group for production objects."},
    # ---------------- GRANT, REVOKE, inheritance & DENY ----------------
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "You run `GRANT SELECT ON SCHEMA prod.sales TO analysts`. Tomorrow a new table `prod.sales.returns` is created. Can analysts read it?",
     "options": ["Only if the table is managed",
                 "Only after `REFRESH GRANTS`",
                 "Yes — privileges granted on a schema are inherited by current and future objects",
                 "No — schema grants only cover existing tables"],
     "answer": 2,
     "explanation": "Inheritance flows down the hierarchy to all current and future children."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "The group `staff` has SELECT on schema `hr`. You run `REVOKE SELECT ON TABLE hr.salaries FROM staff`. What happens?",
     "options": ["staff loses access to hr.salaries only",
                 "The statement fails",
                 "staff loses access to the whole schema",
                 "Nothing changes — staff still reads the table through the schema-level grant"],
     "answer": 3,
     "explanation": "REVOKE removes only a grant made on that object. The inherited SELECT remains; revoke on the schema (and re-grant what's needed) or move the table."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "Which statement correctly gives the group `analysts` read access to `sec_orders`?",
     "options": ["``GRANT SELECT ON TABLE sec_orders TO `analysts` ``",
                 "`GRANT READ ON TABLE sec_orders TO analysts`",
                 "`ALLOW SELECT ON sec_orders FOR analysts`",
                 "`GRANT analysts SELECT ON sec_orders`"],
     "answer": 0,
     "explanation": "GRANT <privilege> ON <securable type> <name> TO <principal>; principals with spaces/special characters in backticks."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "Which statement removes MODIFY on schema `sandbox` from `interns`?",
     "options": ["`DENY MODIFY ON SCHEMA sandbox TO interns`",
                 "`REVOKE MODIFY ON SCHEMA sandbox FROM interns`",
                 "`REVOKE MODIFY ON SCHEMA sandbox TO interns`",
                 "`DROP GRANT MODIFY ON sandbox`"],
     "answer": 1,
     "explanation": "REVOKE … ON … FROM … mirrors GRANT … ON … TO …."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "What does `SHOW GRANTS ON TABLE prod.sales.orders` return?",
     "options": ["The table's row filter",
                 "Only privileges granted directly on the table",
                 "All privileges that affect the table — granted directly or inherited from the schema/catalog — with principal, actionType, objectType, objectKey",
                 "Only the owner"],
     "answer": 2,
     "explanation": "SHOW GRANTS displays inherited and granted privileges; objectType/objectKey show where each one comes from."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "In Unity Catalog, how do you prevent a member of a group from accessing a table that the group can read?",
     "options": ["`DENY SELECT ON TABLE t TO user`",
                 "`REVOKE SELECT ON TABLE t FROM user` — it overrides the group grant",
                 "Make the user the owner",
                 "UC has no DENY: restructure grants (a group without that member, a separate schema) or protect rows/columns with filters, masks or ABAC policies"],
     "answer": 3,
     "explanation": "Unity Catalog is allow-only. Revoking from the user doesn't remove a grant to the group; DENY is only for legacy hive_metastore table ACLs."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "Where is the `DENY` statement supported?",
     "options": ["Only on the legacy hive_metastore (table access control)",
                 "On every Unity Catalog securable",
                 "Only on volumes",
                 "Only on SQL warehouses"],
     "answer": 0,
     "explanation": "DENY applies only to the hive_metastore catalog; it takes precedence over grants and is undone with REVOKE. In UC, ABAC DENY policies (Beta) can only deny MANAGE ACCESS CONTROL."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "In the **legacy** hive_metastore table ACL model, which privilege was required on a database before any other privilege had effect?",
     "options": ["READ_METADATA",
                 "USAGE",
                 "USE SCHEMA",
                 "BROWSE"],
     "answer": 1,
     "explanation": "Legacy table ACLs used USAGE (plus SELECT, MODIFY, CREATE, READ_METADATA, CREATE_NAMED_FUNCTION, ALL PRIVILEGES, and ANY FILE). UC uses USE CATALOG / USE SCHEMA."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "Where in the UI do you grant SELECT on a table to a group?",
     "options": ["The SQL warehouse's Permissions",
                 "Workspace settings → Compute",
                 "Catalog Explorer → the table → Permissions tab → Grant",
                 "The job's Permissions"],
     "answer": 2,
     "explanation": "Catalog Explorer's Permissions tab grants and revokes UC privileges (same effect and audit trail as SQL)."},
    {"topic": "GRANT, REVOKE, inheritance & DENY",
     "q": "Which `information_schema` view lists table privileges including where they are inherited from?",
     "options": ["`row_filters`",
                 "`table_tags`",
                 "`tables`",
                 "`table_privileges` (column `inherited_from`)"],
     "answer": 3,
     "explanation": "information_schema.table_privileges (and schema_privileges, …) expose grants as queryable data."},
    # ---------------- Row filters, masks & dynamic views ----------------
    {"topic": "Row filters, masks & dynamic views",
     "q": "Which statement attaches a row filter function to a table?",
     "options": ["`ALTER TABLE sales SET ROW FILTER region_filter ON (region)`",
                 "`ALTER TABLE sales ADD CONSTRAINT region_filter`",
                 "`CREATE ROW FILTER region_filter ON sales`",
                 "`GRANT FILTER region_filter ON sales`"],
     "answer": 0,
     "explanation": "ALTER TABLE … SET ROW FILTER <function> ON (<columns>); remove it with ALTER TABLE … DROP ROW FILTER."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "What must a row filter function return?",
     "options": ["A WHERE clause string",
                 "BOOLEAN — rows where it returns FALSE are hidden",
                 "An integer row count",
                 "The filtered rows"],
     "answer": 1,
     "explanation": "The SQL UDF returns a boolean per row; FALSE (or NULL) excludes the row."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "Which statement masks the `email` column of `customers` with the function `mask_email`?",
     "options": ["`ALTER TABLE customers SET MASK mask_email ON (email)`",
                 "`UPDATE customers SET email = mask_email(email)`",
                 "`ALTER TABLE customers ALTER COLUMN email SET MASK mask_email`",
                 "`CREATE MASK mask_email ON customers.email`"],
     "answer": 2,
     "explanation": "Column masks are attached per column with ALTER COLUMN … SET MASK (optionally USING COLUMNS for extra arguments)."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "A phone number must be visible only for customers of the reader's regions; the mask needs the row's `country`. How?",
     "options": ["Two masks on the phone column",
                 "It's impossible — masks only receive the masked value",
                 "A row filter on phone",
                 "`ALTER COLUMN phone SET MASK mask_phone USING COLUMNS (country)`"],
     "answer": 3,
     "explanation": "USING COLUMNS passes additional columns of the same row to the mask function."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "The owner of a table with a row filter queries it. What do they see?",
     "options": ["Only the rows the filter function allows for them — owners are not exempt unless the function says so",
                 "An error",
                 "No rows",
                 "All rows — owners bypass row filters"],
     "answer": 0,
     "explanation": "Row filters and column masks apply to every query; exemptions (e.g. an admin group) are written inside the function."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "What is the main weakness of protecting a table with a **dynamic view** only?",
     "options": ["Dynamic views only work on SQL warehouses",
                 "Users with SELECT on the base table bypass the view's logic",
                 "Dynamic views can't use is_account_group_member",
                 "Dynamic views can't filter rows"],
     "answer": 1,
     "explanation": "A view protects only readers who go through it; grant the view and keep the base table private — or attach filters/masks to the table."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "Which operations are NOT supported on a table that has a row filter or column mask? (Choose TWO)",
     "options": ["Deep or shallow clones of the table",
                 "Time travel queries (VERSION/TIMESTAMP AS OF)",
                 "Joins with other tables",
                 "SELECT with a WHERE clause"],
     "answer": [0, 1],
     "explanation": "Time travel and clones would bypass the protections, so they are blocked on protected tables."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "Regional managers' access changes every week. What is the most maintainable way to drive a row filter?",
     "options": ["A new dynamic view per manager",
                 "One filter function per manager",
                 "Hard-coded e-mails in a CASE expression",
                 "A mapping table (user or group → region) queried by the filter function"],
     "answer": 3,
     "explanation": "With a mapping table, access changes are data changes (INSERT/DELETE), not code changes."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "A column mask function for a DOUBLE `salary` column should hide salaries from non-HR users. What can it return for them?",
     "options": ["NULL (or another DOUBLE value)",
                 "An error",
                 "The string 'hidden'",
                 "An empty array"],
     "answer": 0,
     "explanation": "The mask's result must match or be castable to the column type; NULL works for any type."},
    {"topic": "Row filters, masks & dynamic views",
     "q": "In a dynamic view, which expression shows the e-mail only to members of `pii_readers`?",
     "options": ["`MASK(email, 'pii_readers')`",
                 "`CASE WHEN is_account_group_member('pii_readers') THEN email ELSE 'REDACTED' END`",
                 "`email WHERE group = 'pii_readers'`",
                 "`IF(current_user() = 'pii_readers', email, NULL)`"],
     "answer": 1,
     "explanation": "Column-level masking in a view is a CASE on group membership; row-level filtering goes in the WHERE clause."},
    # ---------------- ABAC & tags ----------------
    {"topic": "ABAC & tags",
     "q": "What does an ABAC policy use to decide which columns or tables it applies to?",
     "options": ["Column names matched by regex",
                 "The table's storage location",
                 "Governed tags on the tables/columns (has_tag, has_tag_value)",
                 "Table owners"],
     "answer": 2,
     "explanation": "ABAC policies match objects by their governed tags; tagging a new table/column brings it under the policy automatically."},
    {"topic": "ABAC & tags",
     "q": "Which statement creates a column mask policy for every column tagged `pii` in schema `prod.crm`, except for the PII team?",
     "options": ["`GRANT MASK ON SCHEMA prod.crm TO pii_team`",
                 "`ALTER SCHEMA prod.crm SET MASK redact WHERE TAG = 'pii'`",
                 "`CREATE MASK POLICY pii ON TAG pii USING redact`",
                 "``CREATE POLICY mask_pii ON SCHEMA prod.crm COLUMN MASK prod.crm.redact TO `account users` EXCEPT `pii_team` FOR TABLES MATCH COLUMNS has_tag('pii') AS c ON COLUMN c``"],
     "answer": 3,
     "explanation": "CREATE POLICY … ON <scope> COLUMN MASK <fn> TO … EXCEPT … FOR TABLES MATCH COLUMNS <tag condition> AS alias ON COLUMN alias."},
    {"topic": "ABAC & tags",
     "q": "Why does ABAC scale better than table-level masks for hundreds of tables? (Choose TWO)",
     "options": ["Classifying a column (tagging) is enough to protect it — no per-table ALTER",
                 "ABAC policies make time travel possible on protected tables",
                 "One policy on a catalog/schema covers all current and future tables whose columns carry the tag",
                 "ABAC removes the need for USE CATALOG"],
     "answer": [0, 2],
     "explanation": "ABAC centralises the rule; protection follows the classification. Privileges like USE CATALOG are still required."},
    {"topic": "ABAC & tags",
     "q": "How do governed tags differ from ordinary tags?",
     "options": ["They encrypt the tagged column",
                 "They are account-level, restrict values to an allowed list and control who may assign them — required for ABAC policies",
                 "They are free text",
                 "They can only be put on catalogs"],
     "answer": 1,
     "explanation": "Governed tags add consistency rules (allowed values, assignment permissions); ABAC policies match governed tags."},
    {"topic": "ABAC & tags",
     "q": "Which statement tags the column `email` of `customers`?",
     "options": ["`TAG COLUMN customers.email AS pii`",
                 "`ALTER TABLE customers SET TBLPROPERTIES ('email' = 'pii')`",
                 "`ALTER TABLE customers ALTER COLUMN email SET TAGS ('pii' = 'email')`",
                 "`COMMENT ON COLUMN customers.email IS 'pii'`"],
     "answer": 2,
     "explanation": "SET TAGS / UNSET TAGS on catalogs, schemas, tables, columns and volumes; requires APPLY TAG (and ASSIGN on a governed tag)."},
    {"topic": "ABAC & tags",
     "q": "In a row filter policy, what does `USING COLUMNS (g)` do?",
     "options": ["Masks column g",
                 "Sorts the result by g",
                 "Selects which columns are returned",
                 "Passes the column matched by `MATCH COLUMNS … AS g` as the argument of the filter function"],
     "answer": 3,
     "explanation": "MATCH COLUMNS finds columns by tag and gives them an alias; USING COLUMNS passes them to the UDF."},
    {"topic": "ABAC & tags",
     "q": "Which compute can evaluate ABAC row filter and column mask policies?",
     "options": ["Serverless compute or Databricks Runtime 16.4+",
                 "Only classic clusters with DBR 11.3",
                 "Only SQL warehouses of type classic",
                 "Any Spark 2.x cluster"],
     "answer": 0,
     "explanation": "ABAC requires serverless or DBR 16.4 and above."},
    {"topic": "ABAC & tags",
     "q": "What can an ABAC **DENY** policy (Beta) deny?",
     "options": ["Any privilege on the metastore",
                 "Only the MANAGE ACCESS CONTROL privilege on tagged objects",
                 "Login to the workspace",
                 "SELECT and MODIFY on any table"],
     "answer": 1,
     "explanation": "ABAC DENY policies currently support a single privilege, MANAGE ACCESS CONTROL — who may change grants, ownership and policies."},
    # ---------------- Managed vs external tables ----------------
    {"topic": "Managed vs external tables",
     "q": "What happens to the data files when you `DROP` a **managed** Unity Catalog table?",
     "options": ["They stay in place forever",
                 "Nothing until VACUUM runs",
                 "They are deleted (after the recovery period — `UNDROP TABLE` works for 7 days)",
                 "They are moved to an external location"],
     "answer": 2,
     "explanation": "Managed tables: UC manages the files — DROP removes metadata and data (recoverable with UNDROP within the retention period)."},
    {"topic": "Managed vs external tables",
     "q": "What happens when you `DROP` an **external** table?",
     "options": ["The command fails if the files exist",
                 "The table becomes managed",
                 "The files are deleted immediately",
                 "Only the metadata is removed; the files remain in the external location"],
     "answer": 3,
     "explanation": "External tables point to files you manage; dropping them removes the table definition only."},
    {"topic": "Managed vs external tables",
     "q": "Which statement creates an **external** table?",
     "options": ["`CREATE TABLE t (id INT) LOCATION 'abfss://lake@acct.dfs.core.windows.net/t'`",
                 "`CREATE MANAGED TABLE t (id INT)`",
                 "`CREATE TABLE t AS SELECT 1 AS id`",
                 "`CREATE TABLE t (id INT)`"],
     "answer": 0,
     "explanation": "A LOCATION in an external location (with CREATE EXTERNAL TABLE on it) makes the table external; without LOCATION it is managed."},
    {"topic": "Managed vs external tables",
     "q": "How do you convert an existing external Unity Catalog table to a managed table with the same name, history and grants?",
     "options": ["`CONVERT TO DELTA t`",
                 "`ALTER TABLE t SET MANAGED`",
                 "`ALTER TABLE t UNSET LOCATION`",
                 "Drop and recreate it"],
     "answer": 1,
     "explanation": "SET MANAGED (serverless or DBR 17.3+) moves the data to managed storage; UNSET MANAGED rolls back within 14 days."},
    {"topic": "Managed vs external tables",
     "q": "How can you turn a managed table into an external one?",
     "options": ["`ALTER TABLE t SET EXTERNAL`",
                 "`ALTER TABLE t UNSET MANAGED` at any time",
                 "Create a new table at a LOCATION (CTAS or DEEP CLONE … LOCATION), re-apply grants and swap names",
                 "It happens automatically after 30 days"],
     "answer": 2,
     "explanation": "There is no SET EXTERNAL. UNSET MANAGED only rolls back a recent SET MANAGED conversion."},
    {"topic": "Managed vs external tables",
     "q": "How do you tell whether a table is managed or external?",
     "options": ["`SHOW GRANTS`",
                 "`DESCRIBE HISTORY`",
                 "`SHOW TBLPROPERTIES` → owner",
                 "`DESCRIBE TABLE EXTENDED` → Type (MANAGED/EXTERNAL) and Location"],
     "answer": 3,
     "explanation": "DESCRIBE TABLE EXTENDED (or Catalog Explorer → Details) shows the table type and location."},
    {"topic": "Managed vs external tables",
     "q": "Which features are available for **managed** tables but not external ones? (Choose TWO)",
     "options": ["Automatic liquid clustering",
                 "Files readable directly by other tools at a path you choose",
                 "Predictive optimization (automatic OPTIMIZE/VACUUM)",
                 "Formats like CSV and JSON"],
     "answer": [0, 2],
     "explanation": "Predictive optimization and automatic liquid clustering are for UC managed tables; flexible formats and direct path access are external-table traits."},
    {"topic": "Managed vs external tables",
     "q": "What is an **external location** in Unity Catalog?",
     "options": ["A remote Databricks workspace",
                 "A cloud storage path combined with a storage credential, on which privileges like READ FILES and CREATE EXTERNAL TABLE are granted",
                 "A DBFS mount point",
                 "A Delta Sharing recipient"],
     "answer": 1,
     "explanation": "Storage credential (cloud identity) + path = external location; it governs external tables, external volumes and path access."},
    {"topic": "Managed vs external tables",
     "q": "Which privilege on an external location is needed to create external tables in it?",
     "options": ["MODIFY",
                 "CREATE TABLE only",
                 "CREATE EXTERNAL TABLE",
                 "WRITE VOLUME"],
     "answer": 2,
     "explanation": "CREATE EXTERNAL TABLE on the external location (plus CREATE TABLE on the target schema and the USE privileges)."},
    # ---------------- Lineage, audit & discovery ----------------
    {"topic": "Lineage, audit & discovery",
     "q": "Before dropping a table you want to know which jobs, notebooks and dashboards read it. Where do you look?",
     "options": ["SHOW GRANTS",
                 "The cluster event log",
                 "DESCRIBE HISTORY",
                 "The table's Lineage tab in Catalog Explorer (or system.access.table_lineage)"],
     "answer": 3,
     "explanation": "Unity Catalog captures table- and column-level lineage automatically, including the notebooks, jobs and dashboards involved."},
    {"topic": "Lineage, audit & discovery",
     "q": "An auditor asks who granted SELECT on `hr.salaries` last month. Where is that recorded?",
     "options": ["`system.access.audit` (Unity Catalog `updatePermissions` events)",
                 "`information_schema.table_privileges` history",
                 "`DESCRIBE HISTORY hr.salaries`",
                 "The job run log"],
     "answer": 0,
     "explanation": "Audit logs (system.access.audit) record permission changes with who, when and the request parameters. Table history records data changes."},
    {"topic": "Lineage, audit & discovery",
     "q": "At which levels does Unity Catalog capture lineage? (Choose TWO)",
     "options": ["Column level",
                 "Table level",
                 "Cell level",
                 "Only file level"],
     "answer": [0, 1],
     "explanation": "Lineage is captured for tables and columns (plus the notebooks, jobs and dashboards that read/write them)."},
    {"topic": "Lineage, audit & discovery",
     "q": "A user with a row filter creates `gold_summary` with CTAS from the filtered table. What does `gold_summary` contain and how is it protected?",
     "options": ["All rows, still filtered by the original filter",
                 "An error: CTAS is not allowed on filtered tables",
                 "Only the rows that user could see; the new table has no filter or tags unless you add them",
                 "No rows"],
     "answer": 2,
     "explanation": "Derived tables materialise what the creator saw and don't inherit protections — govern outputs too (tags, grants, policies)."},
    {"topic": "Lineage, audit & discovery",
     "q": "Which privilege lets users discover objects in Catalog Explorer and request access, without reading data?",
     "options": ["SELECT",
                 "USE SCHEMA",
                 "READ VOLUME",
                 "BROWSE"],
     "answer": 3,
     "explanation": "BROWSE (on a catalog or external location) shows objects and metadata for discovery and access requests."},
]

render_quiz(questions, title="Section 13 · Governance and Security", pass_mark=0.8,
            meta="60 questions · identities & roles, ownership & privileges, GRANT/REVOKE/inheritance/DENY, row filters & masks & dynamic views, ABAC & tags, managed vs external tables, lineage & audit · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Identities & roles · Ownership & privileges · GRANT, REVOKE, inheritance & DENY | `presentation/13-P1 - Identities and the Unity Catalog Privilege Model` + `labs/13-L1` |
# MAGIC | Row filters, masks & dynamic views · ABAC & tags | `presentation/13-P2 - Row-Level Security, Column Masks and ABAC` + `labs/13-L2`, `13-L3` |
# MAGIC | Managed vs external tables · Lineage, audit & discovery | `presentation/13-P3 - Managed and External Tables, Lineage and Audit` + `labs/13-L1` Part 8, `13-L3` Parts 7–8 |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
