# Databricks notebook source
# MAGIC %md
# MAGIC # 🗂️ 10-D · Data used in Section 10
# MAGIC
# MAGIC Section 10 is about **orchestration**, so the data is deliberately small and familiar: the **July order files** of the
# MAGIC ShopWave base data (`orders-staging/01.json` … `10.json`, one file per day). The labs deliver them one by one into an
# MAGIC **inbox** folder of the `raw` volume — exactly what a partner or an upstream system does in production — and the jobs
# MAGIC process them.
# MAGIC
# MAGIC | Source | Where | Content |
# MAGIC |---|---|---|
# MAGIC | `orders-staging/01.json … 10.json` | `/Volumes/<catalog>/shopwave/raw/` (generated by `Includes/_setup`) | 121 rows per file = **119 valid orders** + **3 bad rows** (1 exact duplicate, 1 cancelled order with `quantity = 0`, 1 order of the unknown customer `C9999`) |
# MAGIC | `raw/lab10/inbox/` | same volume | the files that have “arrived” (`land10(n)` / the `land_orders` task copies the next file) — the **file arrival trigger** path |
# MAGIC | `customers-json` → `jobs_customers` | | `customer_id` → `country` lookup (300 customers) |
# MAGIC
# MAGIC **Tables written by the job tasks** (all in your course schema):
# MAGIC
# MAGIC | Table | Written by task | Grain / content |
# MAGIC |---|---|---|
# MAGIC | `jobs_bronze_orders` | `load_bronze` | one row per raw record + `source_file`, `batch_id` (one batch per load), `ingested_at` |
# MAGIC | `jobs_silver_orders` | `build_silver_gold` | one row per valid order (dedup, `quantity > 0`), `order_date`, `country`, `known_customer`; quarantined batches are held back |
# MAGIC | `jobs_gold_daily` | `build_silver_gold` | one row per day: `orders`, `revenue`, `avg_order_value`, `unknown_customer_orders` |
# MAGIC | `jobs_gold_kpis` | SQL task `gold_kpis` (file `Users/<you>/shopwave_jobs/10_gold_kpis.sql`) | one row: days, orders, revenue, latest day |
# MAGIC | `jobs_quarantine` | `quarantine_report` | bad rows of a quarantined batch, with `reason` |
# MAGIC | `jobs_country_report` | `country_report` (For each iterations) | one row per batch × country (append-only) |
# MAGIC | `jobs_published` | `publish` | one KPI snapshot per successful publish |
# MAGIC | `jobs_task_log` | every task | `logged_at`, `task`, `attempt`, `status`, `message` — the story of every run |
# MAGIC | `jobs_control` | you (`set_control`) | `publish_enabled` — used to make `publish` fail on purpose |
# MAGIC | `pl10_bronze_orders` · `pl10_daily_revenue` | the 10-L3 **pipeline** | streaming table + materialized view |
# MAGIC
# MAGIC | Key figures | Value |
# MAGIC |---|---|
# MAGIC | File 01 (1 July) | 121 rows · 119 valid · revenue **60,716.61** · top countries Japan, Saudi Arabia, Egypt |
# MAGIC | Files 01–03 | bronze 363 · silver 357 · revenue **201,082.14** |
# MAGIC | Files 02+03 as one batch | **6** bad rows (> 5 → quarantine in 10-L2) · top countries Saudi Arabia, Egypt, France |
# MAGIC | Files 01–02 | silver 238 · revenue **132,359.60** (10-L3) |
# MAGIC
# MAGIC **Jobs the labs create** (all named `10-L…`, all created by you): `10-L1 ShopWave Daily Load` · `10-L2 ShopWave Control
# MAGIC Flow` · `10-L3 Land and Pipeline` · `10-L3 File Arrival Load` · `10-L3 KPIs on Silver Update` · `10-L4 Finance Close` —
# MAGIC plus the pipeline `10-L3 ShopWave inbox pipeline`.

# COMMAND ----------

# MAGIC %run ../../Includes/_setup

# COMMAND ----------

# MAGIC %run ../labs/_10_prepare

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🔍 Preview

# COMMAND ----------

# DBTITLE 1,Inbox and tables
print("inbox:", landed10() or "empty")
_rows = []
for _t in ("jobs_bronze_orders", "jobs_silver_orders", "jobs_gold_daily", "jobs_quarantine", "jobs_country_report",
           "jobs_published", "jobs_gold_kpis", "jobs_task_log", "pl10_bronze_orders", "pl10_daily_revenue"):
    _rows.append((_t, spark.table(_t).count() if spark.catalog.tableExists(_t) else None))
display(spark.createDataFrame(_rows, "table_name STRING, rows LONG"))

# COMMAND ----------

# DBTITLE 1,One staged file: the 3 kinds of bad rows
_f = spark.read.schema(ORDER_SCHEMA).json(f"{dataset_path}/orders-staging/01.json")
display(spark.createDataFrame([
    ("rows", _f.count()),
    ("distinct order_id", _f.select("order_id").distinct().count()),
    ("cancelled (quantity = 0)", _f.where("quantity = 0").select("order_id").distinct().count()),
    ("unknown customer", _f.join(spark.table("jobs_customers"), "customer_id", "left_anti").select("order_id").distinct().count()),
], "metric STRING, value LONG"))

# COMMAND ----------

# DBTITLE 1,Your Section 10 jobs and their latest run
try:
    for _key, _name in JOB_NAMES10.items():
        _s = job_summary(_name, verbose=False)
        if not _s:
            print(f"{_name:<30} — not created")
            continue
        _last = last_run(_name, verbose=False)
        _trig = _s["trigger_type"] or ("schedule" if _s["schedule"] else "manual only")
        print(f"{_name:<30} {len(_s['tasks']):>2} tasks · trigger: {_trig:<13} · last run: "
              f"{(_last or {}).get('state', '-')}")
    print("pipeline:", find_pipeline10() or "not created")
except Exception as e:
    print("Jobs API not reachable here:", _first_line(e))

# COMMAND ----------

# MAGIC %md
# MAGIC ## 🧹 Reset Section 10
# MAGIC `reset_lab10_data()` empties the inbox and the `jobs_*` tables but keeps your jobs. `reset_lab10(confirm="YES")` also
# MAGIC deletes your `10-L…` jobs and the 10-L3 pipeline. **Always** pause triggers you don't need: `pause_lab10_triggers()`.

# COMMAND ----------

# DBTITLE 1,Reset (optional)
# pause_lab10_triggers()
# reset_lab10_data()
# reset_lab10(confirm="YES")
