# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 09-Q · Exam Questions — Databricks SQL & BI Serving
# MAGIC **51 exam-style questions** on SQL warehouses (09-P1), queries, dashboards and alerts (09-P2) and serving gold data to BI
# MAGIC tools (09-P3). Multi-answer questions say so. Target **≥ 80 %** before Section 10.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- SQL warehouses ----------------
    {"topic": "SQL warehouses",
     "q": "A team of SQL analysts needs compute for ad-hoc SQL, AI/BI dashboards and a Power BI connection. Which compute is the best fit?",
     "options": ["A SQL warehouse",
                 "A jobs cluster",
                 "An all-purpose cluster in single-node mode",
                 "A serverless notebook"],
     "answer": 0,
     "explanation": "SQL warehouses are the compute built for SQL and BI: Photon, concurrency scaling, JDBC/ODBC endpoints for BI tools, and they power the SQL editor, dashboards and alerts."},
    {"topic": "SQL warehouses",
     "q": "Which feature is available on **serverless** SQL warehouses but **not** on pro or classic warehouses?",
     "options": ["Predictive IO",
                 "Intelligent Workload Management",
                 "Unity Catalog",
                 "Photon"],
     "answer": 1,
     "explanation": "Classic = Photon; pro = Photon + Predictive IO; serverless = Photon + Predictive IO + Intelligent Workload Management (and 2–6 s start-up)."},
    {"topic": "SQL warehouses",
     "q": "Where does the compute of a **serverless** SQL warehouse run?",
     "options": ["On the BI tool's servers",
                 "On the driver of the workspace's default cluster",
                 "In the Databricks (serverless) compute plane, managed by Databricks",
                 "In the customer's cloud account, in a VPC managed by the customer"],
     "answer": 2,
     "explanation": "Serverless compute runs in Databricks' serverless compute plane; pro and classic warehouses run in your own cloud account."},
    {"topic": "SQL warehouses",
     "q": "Dashboards are fast when one person uses them, but every morning at 9:00 queries wait in a queue for a minute. The warehouse has min = max = 1 cluster. What should you change first?",
     "options": ["Increase the auto stop time",
                 "Switch the channel to Preview",
                 "Increase the cluster size",
                 "Increase the maximum number of clusters"],
     "answer": 3,
     "explanation": "Queueing under concurrent load is fixed by scaling out (more clusters, roughly one per ~10 concurrent queries). Size affects the latency of each query, not concurrency."},
    {"topic": "SQL warehouses",
     "q": "A single complex query on a Small warehouse takes 4 minutes and spills to disk, even at night when nobody else is working. What is the most direct fix?",
     "options": ["Increase the cluster size of the warehouse",
                 "Lower the auto stop time",
                 "Increase the maximum number of clusters",
                 "Run it from the SQL editor instead of a dashboard"],
     "answer": 0,
     "explanation": "A slow single query (spill, heavy joins) needs more resources per query → a bigger size. Extra clusters only help when many queries compete. Also check data layout (Section 12)."},
    {"topic": "SQL warehouses",
     "q": "What is the default **auto stop** of a new **serverless** SQL warehouse created in the UI?",
     "options": ["45 minutes",
                 "10 minutes",
                 "It never stops",
                 "120 minutes"],
     "answer": 1,
     "explanation": "Serverless: 10 minutes by default (minimum 5 in the UI, 1 via the API). Pro and classic: 45 minutes by default, minimum 10."},
    {"topic": "SQL warehouses",
     "q": "An analyst has `SELECT` on the gold tables but gets an error that she cannot use the SQL warehouse. Which permission is missing?",
     "options": ["CAN MANAGE on the dashboard",
                 "MODIFY on the tables",
                 "CAN USE on the SQL warehouse",
                 "USE CATALOG on the catalog"],
     "answer": 2,
     "explanation": "Compute and data are two locks: CAN USE on the warehouse to run queries, and UC privileges (USE CATALOG, USE SCHEMA, SELECT) to read the data."},
    {"topic": "SQL warehouses",
     "q": "Which warehouse permission lets a power user **run queries and see everyone's query history and profiles** on the warehouse, without being able to resize it?",
     "options": ["IS OWNER",
                 "CAN MANAGE",
                 "CAN USE",
                 "CAN MONITOR"],
     "answer": 3,
     "explanation": "CAN MONITOR = CAN USE + monitoring of all queries (history, profiles). CAN MANAGE adds sizing, permissions and deletion."},
    {"topic": "SQL warehouses",
     "q": "An older exam question mentions creating a **SQL endpoint**. What is it today?",
     "options": ["A SQL warehouse",
                 "A JDBC driver",
                 "A Delta Sharing recipient",
                 "A Model Serving endpoint"],
     "answer": 0,
     "explanation": "SQL endpoints were renamed SQL warehouses in 2022; the old REST path /api/2.0/sql/endpoints still exists for compatibility."},
    {"topic": "SQL warehouses",
     "q": "A job must run a saved SQL query, refresh a dashboard and evaluate an alert. What compute do these **SQL / dashboard / alert tasks** require?",
     "options": ["Any all-purpose cluster with Unity Catalog",
                 "A serverless or pro SQL warehouse",
                 "A jobs cluster with Photon",
                 "A classic SQL warehouse only"],
     "answer": 1,
     "explanation": "SQL tasks (query, alert, file) and dashboard tasks run on a SQL warehouse — serverless or pro."},
    # ---------------- SQL editor & parameters ----------------
    {"topic": "SQL editor & parameters",
     "q": "Which query uses a **named parameter marker** correctly in the current SQL editor?",
     "options": ["`SELECT * FROM bi_orders WHERE country = '{country}'`",
                 "`SELECT * FROM bi_orders WHERE country = $country`",
                 "`SELECT * FROM bi_orders WHERE country = :country`",
                 "`SELECT * FROM bi_orders WHERE country = ?country?`"],
     "answer": 2,
     "explanation": "`:name` creates a parameter widget; the value is passed separately from the SQL text. The legacy editor used `{{ country }}`."},
    {"topic": "SQL editor & parameters",
     "q": "A query must read from a table whose name is chosen by the user at run time. What should the query use?",
     "options": ["String concatenation in a notebook before running the query",
                 "`FROM {{ table_name }}`",
                 "`FROM :table_name`",
                 "`FROM IDENTIFIER(:table_name)`"],
     "answer": 3,
     "explanation": "A parameter marker stands for a value; IDENTIFIER(:p) turns a string parameter into a table or column name safely."},
    {"topic": "SQL editor & parameters",
     "q": "A dashboard dataset has a **date range** parameter `period`. How do you reference its bounds?",
     "options": ["`BETWEEN :period.min AND :period.max`",
                 "`BETWEEN :period[0] AND :period[1]`",
                 "`BETWEEN min(:period) AND max(:period)`",
                 "`BETWEEN :period_start AND :period_end` (created automatically)"],
     "answer": 0,
     "explanation": "Date range parameters expose `.min` and `.max`."},
    {"topic": "SQL editor & parameters",
     "q": "What is the advantage of named parameters over building the SQL string with user input?",
     "options": ["They disable the result cache",
                 "Values are sent separately from the SQL text, which prevents SQL injection and enables parameter widgets",
                 "They are required for queries longer than 1,000 characters",
                 "They make the query run on Photon"],
     "answer": 1,
     "explanation": "Parameter values never become part of the SQL text, so they can't change its structure. The same markers work in the editor, dashboards, alerts and the Statement Execution API."},
    {"topic": "SQL editor & parameters",
     "q": "A colleague needs to **change the parameter values and re-run** your saved query, but must not edit its SQL. Which query permission do you grant?",
     "options": ["CAN VIEW",
                 "CAN MANAGE",
                 "CAN RUN",
                 "CAN EDIT"],
     "answer": 2,
     "explanation": "CAN VIEW = see the query text; CAN RUN = refresh / choose parameters; CAN EDIT = change the text; CAN MANAGE = permissions and delete."},
    {"topic": "SQL editor & parameters",
     "q": "Where are visualizations created in the SQL editor stored?",
     "options": ["In a separate dashboard that is created automatically",
                 "Only in the browser cache",
                 "In a Delta table in the user's schema",
                 "With the saved query (as tabs next to the results)"],
     "answer": 3,
     "explanation": "Visualizations belong to the query object. Dashboards today are AI/BI dashboards with their own datasets and widgets."},
    # ---------------- AI/BI dashboards ----------------
    {"topic": "AI/BI dashboards",
     "q": "In an AI/BI dashboard, what feeds the widgets?",
     "options": ["Datasets defined on the Data tab — a table, view, metric view or SQL query",
                 "Notebook cells",
                 "CSV files uploaded to the dashboard",
                 "Saved queries and their visualizations"],
     "answer": 0,
     "explanation": "AI/BI dashboards are built on datasets; each widget aggregates one dataset. Building dashboards from saved queries' visualizations was the legacy model."},
    {"topic": "AI/BI dashboards",
     "q": "A dashboard has a **date range filter** bound to `order_date`. One dataset, `Top products`, is aggregated per product and has no `order_date` column. What happens to the `Top products` table when a user picks March?",
     "options": ["The dashboard adds `order_date` to the dataset automatically",
                 "It is not filtered — a filter only affects datasets that contain the filtered field",
                 "It shows only March data",
                 "The widget shows an error"],
     "answer": 1,
     "explanation": "Filters inject a WHERE on the bound field of each dataset that has it. Add `order_date` to the dataset (or use a parameter in its SQL) to make it filterable."},
    {"topic": "AI/BI dashboards",
     "q": "The `Top products` dataset must return the top **N** products, with N chosen by the viewer. What should you use?",
     "options": ["A metric view",
                 "A second page",
                 "A parameter (`:top_n`) in the dataset SQL, shown as a widget",
                 "A multiple-values filter on `product`"],
     "answer": 2,
     "explanation": "Filters narrow rows of a result; a parameter changes the query itself (a limit, rank threshold, calculation)."},
    {"topic": "AI/BI dashboards",
     "q": "A KPI counter shows **4,304 orders**, but the business knows there were 1,980. The counter sums `orders` from a table at day × country × **category** grain. What is the root cause?",
     "options": ["The dashboard is not published",
                 "The warehouse is too small",
                 "The result cache is stale",
                 "The dataset grain doesn't match the measure: an order with several categories is counted once per category"],
     "answer": 3,
     "explanation": "Summing a pre-aggregated distinct count across a finer grain double-counts. Use an order-grain dataset or a metric view measure `COUNT(DISTINCT order_id)`."},
    {"topic": "AI/BI dashboards",
     "q": "You publish a dashboard with **shared data permission** (embedded credentials). A viewer has **no** `SELECT` on the tables. What does the viewer see?",
     "options": ["The data — queries run with the publisher's data permissions",
                 "An error on every widget",
                 "An empty dashboard until an admin grants SELECT",
                 "Only the rows allowed by the viewer's row filters"],
     "answer": 0,
     "explanation": "Shared data permission = viewers use the publisher's (or a service principal's) data permissions; they don't need SELECT."},
    {"topic": "AI/BI dashboards",
     "q": "Regional managers must see only their region's rows, enforced by a **row filter** on the table. How should the dashboard be published?",
     "options": ["With a schedule that runs once per region",
                 "With individual data permission, so each viewer's own Unity Catalog permissions and row filters apply",
                 "As a draft only",
                 "With shared data permission"],
     "answer": 1,
     "explanation": "Individual data permission runs the queries with each viewer's credentials, so row filters and column masks are applied per viewer."},
    {"topic": "AI/BI dashboards",
     "q": "You keep editing a dashboard after publishing it. What do viewers of the published dashboard see?",
     "options": ["Nothing — editing unpublishes the dashboard",
                 "Every change as soon as it is saved",
                 "The last published snapshot, until you publish again",
                 "The draft, but read-only"],
     "answer": 2,
     "explanation": "Publishing creates a snapshot; the draft stays private to editors until the next Publish."},
    {"topic": "AI/BI dashboards",
     "q": "Which dashboard permission is needed to **publish** a new version of the dashboard?",
     "options": ["Workspace admin only",
                 "CAN VIEW",
                 "CAN RUN",
                 "CAN EDIT"],
     "answer": 3,
     "explanation": "CAN VIEW / CAN RUN: view and interact · CAN EDIT: edit the draft and publish · CAN MANAGE: permissions and delete."},
    {"topic": "AI/BI dashboards",
     "q": "What does a dashboard **schedule** do? (Choose TWO)",
     "options": ["Runs the dashboard's datasets at the scheduled time, which fills the query result cache",
                 "Copies the dashboard into Power BI",
                 "Re-runs the pipeline that loads the data",
                 "Sends snapshots to subscribers (PDF by email, PNG to Slack/Teams)"],
     "answer": [0, 3],
     "explanation": "Schedules refresh the dataset results (faster first load for viewers) and deliver subscriptions. They don't run pipelines — use a job for that."},
    {"topic": "AI/BI dashboards",
     "q": "The nightly pipeline finishes anywhere between 01:00 and 03:30. The dashboard must refresh **as soon as** new data is there. What is the best design?",
     "options": ["A dashboard schedule every 5 minutes",
                 "A Lakeflow Job with a pipeline task followed by a dashboard task that depends on it",
                 "A dashboard schedule at 04:00",
                 "Ask viewers to click Refresh"],
     "answer": 1,
     "explanation": "Data-driven orchestration: the dashboard task refreshes the published dashboard (and can notify subscribers) right after the pipeline task succeeds."},
    {"topic": "AI/BI dashboards",
     "q": "How can an AI/BI dashboard be version-controlled and promoted from dev to prod?",
     "options": ["By exporting screenshots",
                 "It can't; dashboards exist only in the UI",
                 "As a `.lvdash.json` file in a Git folder, deployed with Declarative Automation Bundles or the REST API",
                 "By copying its widgets one by one"],
     "answer": 2,
     "explanation": "Dashboards are workspace files (`.lvdash.json`) with datasets and layout in JSON — Git folders, bundles and the Lakeview REST API all work with them."},
    {"topic": "AI/BI dashboards",
     "q": "What is a **Genie Agent** (formerly a *Genie space*)?",
     "options": ["A SQL warehouse type for AI workloads",
                 "A scheduled job that emails dashboards",
                 "A Python library for building dashboards",
                 "A curated space over selected tables/metric views with instructions and example SQL, where business users ask questions in natural language"],
     "answer": 3,
     "explanation": "Genie Agents translate questions into SQL over curated data and show the SQL; answer quality depends on comments, keys and metric views in the gold layer."},
    # ---------------- Alerts ----------------
    {"topic": "Alerts",
     "q": "What are the parts of a Databricks SQL alert?",
     "options": ["A query, a condition on its result, a schedule and notification recipients/destinations",
                 "A Delta constraint and a trigger",
                 "A notebook, a cluster and a retry policy",
                 "A dashboard and a subscription"],
     "answer": 0,
     "explanation": "An alert runs its query on a schedule on a SQL warehouse, evaluates a condition (column, aggregation, operator, threshold) and notifies users or destinations."},
    {"topic": "Alerts",
     "q": "Which evaluation states can a (new) Databricks SQL alert have?",
     "options": ["GREEN, AMBER, RED",
                 "OK, TRIGGERED, ERROR",
                 "PENDING, ACTIVE, PAUSED",
                 "RUNNING, SUCCEEDED, FAILED"],
     "answer": 1,
     "explanation": "OK = condition not met, TRIGGERED = met, ERROR = the query failed. Legacy alerts also had UNKNOWN (never evaluated)."},
    {"topic": "Alerts",
     "q": "An alert counts quarantined rows: `SELECT count(*) AS bad_rows FROM quarantine WHERE load_date = current_date()`. It should notify when there is at least one bad row. Which condition?",
     "options": ["`bad_rows` < 1",
                 "`bad_rows` is null",
                 "`bad_rows` > 0",
                 "`bad_rows` = 0"],
     "answer": 2,
     "explanation": "Trigger when the value column is greater than the threshold 0."},
    {"topic": "Alerts",
     "q": "The on-call team also wants a message when the alert goes **back to normal**. Which setting?",
     "options": ["Empty result state",
                 "Run as owner",
                 "A second alert with the opposite condition is the only way",
                 "Notify on OK"],
     "answer": 3,
     "explanation": "Notify on OK sends a notification when the state returns to OK. Empty result state defines what an empty result means."},
    {"topic": "Alerts",
     "q": "Notifications must go to a **Slack channel** and to **PagerDuty**. What do you configure?",
     "options": ["Notification destinations (set up by an admin) as recipients of the alert",
                 "A Python UDF that calls the APIs",
                 "A webhook inside the alert query",
                 "A dashboard subscription"],
     "answer": 0,
     "explanation": "Admins define notification destinations (email, Slack, Microsoft Teams, PagerDuty, webhooks); alerts and jobs then select them."},
    {"topic": "Alerts",
     "q": "A data-quality alert must be evaluated **immediately after** the pipeline that loads the data, and later tasks should depend on its result. What should you use?",
     "options": ["A legacy alert on a saved query",
                 "An alert task (SQL task) in the Lakeflow Job, after the pipeline task",
                 "An alert schedule every minute",
                 "A dashboard subscription"],
     "answer": 1,
     "explanation": "Alerts can run as tasks in jobs, so the condition check is orchestrated with the load and downstream tasks can branch on it."},
    {"topic": "Alerts",
     "q": "Which statement about **legacy** Databricks SQL alerts is correct?",
     "options": ["They didn't need a SQL warehouse",
                 "They could only send Slack messages",
                 "They were attached to a saved query and could be in an UNKNOWN state before the first evaluation",
                 "They could not be scheduled"],
     "answer": 2,
     "explanation": "Legacy alerts were built on saved queries (with the query's refresh schedule) and had OK/TRIGGERED/UNKNOWN. New alerts own their query and schedule; states OK/TRIGGERED/ERROR."},
    # ---------------- Gold serving objects ----------------
    {"topic": "Gold serving objects",
     "q": "Business users need a gold object that is **always current**, holds **no copy of the data** and contains light logic over a small table. What should you create?",
     "options": ["A streaming table",
                 "A materialized view refreshed daily",
                 "A table rebuilt by a nightly job",
                 "A view"],
     "answer": 3,
     "explanation": "A view stores only the query and runs it at read time — always current, but you pay the query cost on every read."},
    {"topic": "Gold serving objects",
     "q": "An expensive aggregation over a billion-row fact table is read by 30 dashboards; the facts change once a night. Which gold object is the best fit?",
     "options": ["A materialized view refreshed after the nightly load",
                 "A temporary view",
                 "A view",
                 "A streaming table"],
     "answer": 0,
     "explanation": "Materialized views precompute the result (refreshed incrementally when possible) so reads are fast and cheap; a view would recompute the aggregation for every dashboard read."},
    {"topic": "Gold serving objects",
     "q": "Which statement creates a materialized view that refreshes **when its source tables change**, at most once per hour?",
     "options": ["`CREATE VIEW mv WITH REFRESH ON CHANGE AS …`",
                 "`CREATE MATERIALIZED VIEW mv TRIGGER ON UPDATE AT MOST EVERY INTERVAL 1 HOUR AS …`",
                 "`CREATE MATERIALIZED VIEW mv SCHEDULE EVERY 1 HOUR AS …`",
                 "`CREATE STREAMING TABLE mv TRIGGER EVERY 1 HOUR AS …`"],
     "answer": 1,
     "explanation": "TRIGGER ON UPDATE is data-driven (refresh when upstream data changes, throttled by AT MOST EVERY). SCHEDULE EVERY is time-based."},
    {"topic": "Gold serving objects",
     "q": "Which statements about materialized views in Databricks SQL are correct? (Choose TWO)",
     "options": ["They can be created on a classic SQL warehouse",
                 "A serverless pipeline computes and refreshes them, incrementally when possible",
                 "`REFRESH MATERIALIZED VIEW` refreshes one on demand",
                 "You must run OPTIMIZE and VACUUM on them regularly"],
     "answer": [1, 2],
     "explanation": "MVs need a pro/serverless warehouse (or a pipeline/serverless notebook); they are maintained by a managed pipeline; OPTIMIZE/VACUUM are not supported on them (managed for you)."},
    {"topic": "Gold serving objects",
     "q": "Why define KPIs in a **Unity Catalog metric view** instead of in each dashboard?",
     "options": ["Metric views replace the SQL warehouse",
                 "Metric views store a copy of the data and are therefore faster",
                 "Metric views are required for Power BI",
                 "Measures are defined once (e.g. `COUNT(DISTINCT order_id)`) and queried with `MEASURE()` at any grouping, so every consumer gets the same, correct numbers"],
     "answer": 3,
     "explanation": "Metric views separate dimensions and measures and compute measures correctly at query time for any grouping — one governed definition for dashboards, Genie, SQL and alerts."},
    {"topic": "Gold serving objects",
     "q": "You add `PRIMARY KEY (customer_id)` to `customers` and a `FOREIGN KEY` from `orders`. Some orders reference customers that don't exist. What happens?",
     "options": ["Nothing fails — PK/FK constraints in Databricks are informational, not enforced; BI tools and Genie use them for relationships and joins",
                 "The ALTER TABLE fails",
                 "The orphan orders are deleted",
                 "Future inserts of orphan orders fail"],
     "answer": 0,
     "explanation": "Informational constraints document relationships (ER diagram, Power BI relationships on publish, Genie, optimizer with RELY) but are not enforced."},
    # ---------------- BI connectivity & permissions ----------------
    {"topic": "BI connectivity & permissions",
     "q": "Which values does Power BI Desktop or a JDBC client need to connect to a SQL warehouse? (Choose TWO)",
     "options": ["Server hostname and HTTP path (port 443)",
                 "A credential: OAuth sign-in, a personal access token or a service principal",
                 "The workspace's storage account key",
                 "The warehouse's cluster size"],
     "answer": [0, 1],
     "explanation": "Connection details tab: Server hostname, Port, HTTP path (/sql/1.0/warehouses/<id>) — plus an authentication method."},
    {"topic": "BI connectivity & permissions",
     "q": "What does **Partner Connect** do when you connect a cloud partner such as a BI or ingestion SaaS tool?",
     "options": ["It copies your tables into the partner's storage",
                 "It disables Unity Catalog for the partner",
                 "It creates the resources the partner needs — a SQL warehouse, a service principal and a token — and sets up the connection (admin required)",
                 "It installs the partner's desktop application"],
     "answer": 2,
     "explanation": "Partner Connect automates trials and connections; for desktop tools (Power BI Desktop, Tableau Desktop) it provides a connection file instead."},
    {"topic": "BI connectivity & permissions",
     "q": "A Power BI report must always show the **latest** data without a scheduled import; the SQL warehouse is available during business hours. Which storage mode?",
     "options": ["Import with a daily refresh",
                 "Import",
                 "Export to Excel",
                 "DirectQuery"],
     "answer": 3,
     "explanation": "DirectQuery sends each visual's query to the SQL warehouse (always current, warehouse load). Import copies data into Power BI and refreshes on a schedule."},
    {"topic": "BI connectivity & permissions",
     "q": "Scheduled Power BI refreshes should not depend on an employee's account. What should authenticate them?",
     "options": ["A service principal with OAuth machine-to-machine",
                 "Anonymous access to the warehouse",
                 "The workspace admin's password",
                 "The personal access token of the team lead"],
     "answer": 0,
     "explanation": "Production integrations use a service principal (OAuth M2M), granted CAN USE on the warehouse and the needed UC privileges."},
    {"topic": "BI connectivity & permissions",
     "q": "A new analyst group must query every table and view in `workspace.gold` from the SQL editor. Which set of permissions is sufficient? (Choose TWO)",
     "options": ["MODIFY on the schema",
                 "CAN MANAGE on every dashboard",
                 "CAN USE on a SQL warehouse",
                 "`USE CATALOG` on `workspace`, `USE SCHEMA` and `SELECT` on `workspace.gold`"],
     "answer": [2, 3],
     "explanation": "Data: USE CATALOG + USE SCHEMA + SELECT (granted on the schema it's inherited by all its tables/views). Compute: CAN USE on a warehouse."},
    {"topic": "BI connectivity & permissions",
     "q": "A Python service outside Databricks must run SQL on a warehouse **over HTTPS without installing a driver**. What should it use?",
     "options": ["The Delta Sharing protocol",
                 "The Clusters API",
                 "The Statement Execution API (`POST /api/2.0/sql/statements` with a warehouse id)",
                 "DBFS REST API"],
     "answer": 2,
     "explanation": "The Statement Execution API submits SQL to a warehouse, supports named parameters and returns results as JSON or Arrow (inline or external links)."},
    # ---------------- Monitoring & caching ----------------
    {"topic": "Monitoring & caching",
     "q": "An analyst runs the same query twice within a minute; the tables didn't change. The second run returns instantly. Why?",
     "options": ["The warehouse scaled out",
                 "Delta time travel",
                 "Photon compiles queries twice as fast the second time",
                 "The query result cache served the result"],
     "answer": 3,
     "explanation": "Identical query + unchanged tables → result from the result cache (24 h, invalidated when a table changes; on serverless also a remote cache shared across warehouses)."},
    {"topic": "Monitoring & caching",
     "q": "You benchmark two versions of a query and need both to really execute. What do you run first?",
     "options": ["`SET use_cached_result = false`",
                 "`OPTIMIZE` on the tables",
                 "Restart the workspace",
                 "`CLEAR CACHE ALL`"],
     "answer": 0,
     "explanation": "use_cached_result = false disables the query result cache for the session — for testing and benchmarking only."},
    {"topic": "Monitoring & caching",
     "q": "Which tool shows the **operators** of a finished query (scan, join, aggregate, exchange) with the time, rows and memory of each?",
     "options": ["The warehouse Monitoring tab",
                 "The query profile",
                 "The dashboard schedule history",
                 "DESCRIBE HISTORY"],
     "answer": 1,
     "explanation": "Query History → a query → See query profile. The Monitoring tab shows load over time (running/queued queries, clusters)."},
    {"topic": "Monitoring & caching",
     "q": "You want a weekly report: which dashboards and BI tools sent the most and slowest queries to the warehouses, and how often results came from cache. Where is that data?",
     "options": ["`DESCRIBE HISTORY` of each table",
                 "The pipeline event log",
                 "`system.query.history` (query_source, client_application, durations, from_result_cache)",
                 "The workspace audit log only"],
     "answer": 2,
     "explanation": "system.query.history records statements of warehouses, serverless compute and pipelines with source, client, timings, bytes read and cache usage."},
]

render_quiz(questions, title="Section 09 · Databricks SQL & BI Serving", pass_mark=0.8,
            meta="51 questions · SQL warehouses, SQL editor & parameters, AI/BI dashboards, alerts, gold serving objects, BI connectivity & permissions, monitoring & caching · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | SQL warehouses · Monitoring & caching | `presentation/09-P1 - Databricks SQL and SQL Warehouses` + `labs/09-L1` |
# MAGIC | SQL editor & parameters · AI/BI dashboards · Alerts | `presentation/09-P2 - Queries, Dashboards and Alerts` + `labs/09-L1`, `09-L2`, `09-L3` Part 1 |
# MAGIC | Gold serving objects · BI connectivity & permissions | `presentation/09-P3 - Serving Gold Data to BI Tools` + `labs/09-L3`, `09-L4` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
