# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 12-Q · Exam Questions — Troubleshooting, Monitoring and Optimization
# MAGIC **65 exam-style questions** on job monitoring (12-P1), Spark UI bottlenecks (12-P2), data layout (12-P3) and compute
# MAGIC failures (12-P4). Multi-answer questions say so. Target **≥ 80 %** before Section 13.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Run history & baselines ----------------
    {"topic": "Run history & baselines",
     "q": "Where do you see, for ONE job, the duration of each recent run as a bar and the status of every task of every run in a grid?",
     "options": ["The job's Runs tab in matrix view",
                 "Catalog Explorer → History",
                 "The compute event log",
                 "The SQL editor's query history"],
     "answer": 0,
     "explanation": "The matrix view of a job's runs shows one column per run (bar = run duration) and one row per task (cell colour = status, hover = duration)."},
    {"topic": "Run history & baselines",
     "q": "A job normally takes about 9 minutes. Today's run took 15 minutes. What is the best FIRST step to find the cause?",
     "options": ["Enable predictive optimization",
                 "Compare today's run with recent successful runs task by task (matrix / timeline view) to find which task grew, and whether in queue, setup or execution time",
                 "Delete the run history",
                 "Increase the cluster size and re-run"],
     "answer": 1,
     "explanation": "Narrow it down before changing anything: which task got slower, and did it spend the extra time waiting (queue), starting compute (setup) or executing."},
    {"topic": "Run history & baselines",
     "q": "Why is the median of recent successful runs a better baseline than the average of all runs?",
     "options": ["The median is always smaller",
                 "System tables only store medians",
                 "Failed runs and one-off spikes (e.g. a compute start-up delay) distort the average; the median of successful runs reflects normal behaviour",
                 "The average can't be computed for jobs"],
     "answer": 2,
     "explanation": "Outliers and failed runs (which often end early) pull an average around. A median (or p90) of successful runs is robust."},
    {"topic": "Run history & baselines",
     "q": "In the matrix view one run has a much taller bar than usual, but every task cell shows its normal duration. What is the most likely explanation?",
     "options": ["The run failed",
                 "Predictive optimization ran",
                 "One task regressed",
                 "The run spent extra time before or between tasks — queueing or compute start-up (setup)"],
     "answer": 3,
     "explanation": "If task execution times are normal, the extra time is outside the tasks: queued behind another run, or waiting for compute (capacity, cold start)."},
    {"topic": "Run history & baselines",
     "q": "Which run page view shows the tasks as bars on a time axis, making parallel tasks and the critical path visible?",
     "options": ["Timeline view",
                 "List view",
                 "Graph view",
                 "Matrix view"],
     "answer": 0,
     "explanation": "The timeline view shows each task's start, end and overlap; for serverless tasks it links to the query profiles."},
    {"topic": "Run history & baselines",
     "q": "Which system table do you query for the execution time of each TASK of a multi-task job over the last 90 days?",
     "options": ["system.billing.usage",
                 "system.lakeflow.job_task_run_timeline",
                 "system.access.audit",
                 "system.lakeflow.jobs"],
     "answer": 1,
     "explanation": "job_task_run_timeline has one row per task run with setup/execution/cleanup durations, result_state and termination_code. job_run_timeline is per job run; jobs is the job definition (SCD2)."},
    {"topic": "Run history & baselines",
     "q": "What is true about the `system.lakeflow` job tables? (Choose TWO)",
     "options": ["They keep about a year (365 days) of history",
                 "Runs longer than one hour can be split into several rows; result_state is filled on the last row",
                 "They only contain jobs that ran on serverless compute",
                 "They are updated in real time with no delay"],
     "answer": [0, 1],
     "explanation": "Lakeflow system tables keep 365 days, typically arrive within an hour, and long runs are sliced into multiple rows with the result on the final slice."},
    {"topic": "Run history & baselines",
     "q": "You want to be warned when a job run takes longer than 20 minutes, but the run must NOT be stopped. What do you configure?",
     "options": ["max_concurrent_runs = 1",
                 "Retries with a 20-minute interval",
                 "A timeout of 20 minutes",
                 "A duration threshold (health rule RUN_DURATION_SECONDS) with a duration-warning notification"],
     "answer": 3,
     "explanation": "The duration threshold raises a warning (and notification) and the run continues. A timeout stops the run and marks it Timed out."},
    # ---------------- Job & pipeline health ----------------
    {"topic": "Job & pipeline health",
     "q": "A run's graph view shows: `extract` succeeded, `transform` failed, `load` and `report` show *Upstream failed*. Where do you start debugging?",
     "options": ["`transform`, the first failed task on the path",
                 "`load`",
                 "`report`, because it is the last task",
                 "The run's notification settings"],
     "answer": 0,
     "explanation": "Upstream failed tasks never ran — they are victims. The blocker is the first failed task upstream: open it for the error and stack trace."},
    {"topic": "Job & pipeline health",
     "q": "What does the task status *Upstream failed* mean?",
     "options": ["The task was disabled",
                 "The task was not run because a task it depends on failed and its run-if condition was not met",
                 "The task failed because of a bug in its own code",
                 "The task timed out"],
     "answer": 1,
     "explanation": "With the default run-if 'All succeeded', a failed dependency prevents the task from running and marks it Upstream failed."},
    {"topic": "Job & pipeline health",
     "q": "After fixing the cause of a failed run, you want to re-run only the failed task and its downstream tasks, keeping the results of the tasks that succeeded. What do you use?",
     "options": ["Run now",
                 "Reset the job",
                 "Repair run",
                 "Clone the job"],
     "answer": 2,
     "explanation": "Repair run re-runs the failed and skipped tasks (and their dependents) of the same run, using the current job settings; successful tasks are not re-run."},
    {"topic": "Job & pipeline health",
     "q": "A run shows the status *Succeeded with failures*. What does it mean?",
     "options": ["The run exceeded its duration threshold",
                 "The run was canceled",
                 "All tasks succeeded on retry",
                 "Some tasks failed, but the tasks that determine the run result (e.g. a final task with run-if All done) succeeded"],
     "answer": 3,
     "explanation": "The run outcome depends on the leaf tasks. A cleanup/notification task with 'All done' can succeed even though upstream tasks failed."},
    {"topic": "Job & pipeline health",
     "q": "In an If/else job, the tasks of the branch that was not taken show which status?",
     "options": ["Excluded",
                 "Failed",
                 "Upstream failed",
                 "Canceled"],
     "answer": 0,
     "explanation": "Tasks skipped because of an If/else outcome or an unmet run-if like 'All failed' are Excluded — not an error."},
    {"topic": "Job & pipeline health",
     "q": "Where can you see the number of succeeded, failed and skipped runs per day across ALL your jobs, and filter by error code?",
     "options": ["Compute → Event log",
                 "Jobs & Pipelines → Runs tab (finished-runs count graph and filters)",
                 "Catalog Explorer",
                 "Each job's Tasks tab"],
     "answer": 1,
     "explanation": "The Runs tab of Jobs & Pipelines lists runs of all jobs (last 60 days) with a finished-runs graph, filters (status, job, error code, run-as, time) and top error types."},
    {"topic": "Job & pipeline health",
     "q": "Which TWO pieces of evidence help you decide whether a job failure is a code problem or a compute problem? (Choose TWO)",
     "options": ["The run's termination code (e.g. RUN_EXECUTION_ERROR vs CLUSTER_ERROR)",
                 "The job's tags",
                 "The failed task's error message and stack trace",
                 "The number of job parameters"],
     "answer": [0, 2],
     "explanation": "The termination code classifies the failure (task error vs compute, library, permission...), and the task's error/stack trace shows the actual exception."},
    {"topic": "Job & pipeline health",
     "q": "A job is triggered every 5 minutes, has max concurrent runs = 1 and queueing disabled. Some runs take 7 minutes. What happens to the triggers that arrive while a run is active?",
     "options": ["They wait in the queue",
                 "The active run is canceled",
                 "They run in parallel anyway",
                 "They are skipped"],
     "answer": 3,
     "explanation": "Without queueing, a run that would exceed max concurrent runs is skipped. With queueing on, it waits in the Queued state."},
    {"topic": "Job & pipeline health",
     "q": "For a Lakeflow Spark Declarative Pipeline, where do you find per-flow rows written and expectation pass/drop/fail counts?",
     "options": ["The pipeline graph and its event log (flow_progress, data quality)",
                 "The job's Tasks tab",
                 "The compute event log",
                 "system.billing.usage"],
     "answer": 0,
     "explanation": "The pipeline UI graph and the event log (event_log(TABLE(t)) / event_log('<pipeline_id>')) record flow progress and data-quality metrics."},
    # ---------------- Spark UI: skew, shuffle, spill ----------------
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "What creates a new stage inside a Spark job?",
     "options": ["Each file read",
                 "A shuffle (Exchange) between operations",
                 "Every column added with withColumn",
                 "Every filter"],
     "answer": 1,
     "explanation": "Narrow transformations are pipelined in one stage; a wide transformation needs a shuffle, which is the stage boundary."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "In a stage's Summary Metrics the task Duration is: Min 0.5 s, 25th 1.0 s, Median 1.1 s, 75th 1.3 s, Max 6.2 min. What does this indicate?",
     "options": ["A healthy stage",
                 "Too few shuffle partitions",
                 "Data skew — a few tasks process far more data than the rest",
                 "Disk spill on all tasks"],
     "answer": 2,
     "explanation": "Max far above the 75th percentile (Databricks' rule of thumb: more than 50 % above) means skew: one task gets much more data, usually a hot key."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "Which Spark UI columns show that a stage ran out of execution memory and wrote data to local disk?",
     "options": ["Input Size / Records",
                 "Scheduler Delay",
                 "Shuffle Write Time",
                 "Spill (Memory) and Spill (Disk)"],
     "answer": 3,
     "explanation": "Spill (Memory) is the in-memory size of the spilled data, Spill (Disk) the size written to disk. The columns appear only when spill happened."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "A stage shows a Shuffle Read of 400 GB for a join between a 2 TB fact table and a 30 MB dimension table. What is the most effective fix?",
     "options": ["Broadcast the dimension table so the fact table isn't shuffled",
                 "Increase the number of retries",
                 "Run VACUUM",
                 "Cache the fact table"],
     "answer": 0,
     "explanation": "Broadcasting the small side turns the shuffle join into a broadcast hash join: the big table is joined where it is read, without an exchange."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "Which operations cause a shuffle? (Choose TWO)",
     "options": ["a join of two large tables without broadcast",
                 "`withColumn(...)`",
                 "`filter(...)`",
                 "`groupBy(...).agg(...)`"],
     "answer": [0, 3],
     "explanation": "Aggregations and non-broadcast joins redistribute data by key (wide). filter and withColumn are narrow."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "30 % of all events belong to one customer. Which operation on this data is MOST affected by the skew?",
     "options": ["`sum(amount)` grouped by customer_id",
                 "`filter(event_type = 'view')`",
                 "A shuffle join of events and a large customer table on customer_id",
                 "`select(customer_id, amount)`"],
     "answer": 2,
     "explanation": "A sum is partially aggregated before the shuffle, so only one row per customer and task moves. A shuffle join moves every row of the hot key to one task."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "What does salting do to fix a skewed key?",
     "options": ["Encrypts the key column",
                 "Removes duplicate rows",
                 "Sorts the data by the key",
                 "Adds a random-ish suffix/number to the key so its rows spread across several tasks; results are combined afterwards (or the other side is replicated per salt)"],
     "answer": 3,
     "explanation": "Salting splits a hot key into N sub-keys: two-stage aggregation for group-bys, or replicating the other join side N times for joins."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "Tasks of a sort stage spill tens of GB to disk. Which change most directly reduces the spill? (Choose TWO)",
     "options": ["Disable the disk cache",
                 "Increase the number of shuffle partitions so each task handles less data",
                 "Use spot instances",
                 "Use memory-optimized workers (more memory per core)"],
     "answer": [1, 3],
     "explanation": "Spill happens when a task's data doesn't fit in execution memory: smaller partitions or more memory per core both help (and fixing skew if one task is oversized)."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "Where do you analyse operator-level metrics (rows, time, spill, pruning) of a query run on serverless compute?",
     "options": ["The compute event log",
                 "The query profile (See performance / Query history)",
                 "Ganglia",
                 "Spark UI → Stages"],
     "answer": 1,
     "explanation": "Serverless compute and SQL warehouses have no Spark UI; the query profile shows the operator graph, top operators and metrics."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "The Spark UI shows thousands of tasks per stage, each reading only a few KB, and the job is slow. What is the likely cause?",
     "options": ["A broadcast join",
                 "Data skew",
                 "Too many small files",
                 "Disk spill"],
     "answer": 2,
     "explanation": "Each small file (split) becomes a task; scheduling and file overhead dominate. Compact with OPTIMIZE / auto compaction / predictive optimization."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "In `EXPLAIN` output, which operator indicates a shuffle?",
     "options": ["`Project`",
                 "`FileScan`",
                 "`Filter`",
                 "`Exchange hashpartitioning(...)`"],
     "answer": 3,
     "explanation": "Exchange (hash/range/single partitioning) is a shuffle. BroadcastExchange is the broadcast of a small side."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "Which signal in the Spark UI suggests the DRIVER is the bottleneck rather than the executors?",
     "options": ["Long gaps between jobs on the event timeline while executors are idle",
                 "High Shuffle Read on one task",
                 "Many tasks per stage",
                 "Spill (Disk) > 0"],
     "answer": 0,
     "explanation": "Gaps mean no Spark work is scheduled: the driver is busy (Python loops, collect, pandas, planning)."},
    {"topic": "Spark UI: skew, shuffle, spill",
     "q": "One task of a stage has Shuffle Read Size 2.1 GB while the median is 3 MB. Which TWO fixes address it? (Choose TWO)",
     "options": ["Salting the key / isolating the hot key",
                 "Letting AQE split the skewed partition of the join (skew join) or broadcasting the small side",
                 "Running VACUUM",
                 "Increasing the auto-termination time"],
     "answer": [0, 1],
     "explanation": "The partition sizes show skew. AQE skew join, broadcast or salting spread the hot key; VACUUM and auto-termination are unrelated."},
    # ---------------- AQE, joins & caching ----------------
    {"topic": "AQE, joins & caching",
     "q": "Which are features of Adaptive Query Execution (AQE)? (Choose TWO)",
     "options": ["Coalescing small shuffle partitions at runtime",
                 "Deleting old files",
                 "Choosing liquid clustering keys",
                 "Switching to a broadcast join when a side turns out to be small at runtime"],
     "answer": [0, 3],
     "explanation": "AQE re-plans at stage boundaries: coalesce partitions, switch join strategies, split skewed join partitions. File deletion is VACUUM; keys are chosen by CLUSTER BY AUTO."},
    {"topic": "AQE, joins & caching",
     "q": "What is the default static broadcast threshold `spark.sql.autoBroadcastJoinThreshold` in Apache Spark?",
     "options": ["No limit",
                 "1 GB",
                 "1 MB",
                 "10 MB"],
     "answer": 3,
     "explanation": "10 MB by default (-1 disables automatic broadcast). On Databricks AQE also broadcasts at runtime up to a higher threshold."},
    {"topic": "AQE, joins & caching",
     "q": "What is the default storage level of `df.cache()` for a DataFrame?",
     "options": ["MEMORY_AND_DISK",
                 "DISK_ONLY",
                 "MEMORY_ONLY",
                 "OFF_HEAP"],
     "answer": 0,
     "explanation": "DataFrame cache()/persist() default to MEMORY_AND_DISK (RDD cache() defaults to MEMORY_ONLY)."},
    {"topic": "AQE, joins & caching",
     "q": "Which statements about the Databricks disk cache are true? (Choose TWO)",
     "options": ["It caches any DataFrame, including the results of UDFs",
                 "It stores copies of remote Parquet/Delta files on the workers' local storage",
                 "It is invalidated automatically when files change",
                 "It must be filled manually with df.cache()"],
     "answer": [1, 2],
     "explanation": "The disk cache caches data files automatically on first read and stays consistent; the Spark cache is the manual, DataFrame-level one."},
    {"topic": "AQE, joins & caching",
     "q": "A notebook caches a large DataFrame used once, and the following joins start to spill. What should you do?",
     "options": ["Increase the broadcast threshold",
                 "Switch to DISK_ONLY for all tables",
                 "Remove the cache (or unpersist it) — it only takes executor memory away from the joins",
                 "Cache more DataFrames"],
     "answer": 2,
     "explanation": "Cache only what is reused; a cache consumes executor memory and can cause spill. unpersist() frees it."},
    {"topic": "AQE, joins & caching",
     "q": "What happens when you call `df.cache()` in a notebook on serverless compute?",
     "options": ["The DataFrame is cached in memory",
                 "It is converted into a materialized view",
                 "It is cached on the driver",
                 "It is not supported — rely on the automatic disk cache or materialize the result to a table"],
     "answer": 3,
     "explanation": "Serverless compute doesn't support the Spark cache API; the disk cache is managed for you."},
    # ---------------- Partitioning & Z-order ----------------
    {"topic": "Partitioning & Z-order",
     "q": "Which column is the WORST choice for `PARTITIONED BY` on a 50 GB events table?",
     "options": ["`customer_id` (2 million values)",
                 "`country` (10 values)",
                 "`event_date`",
                 "No partitioning"],
     "answer": 0,
     "explanation": "High-cardinality partition columns create millions of folders with tiny files. Small tables (< ~1 TB) usually shouldn't be partitioned at all."},
    {"topic": "Partitioning & Z-order",
     "q": "Which rules of thumb does Databricks give for partitioning? (Choose TWO)",
     "options": ["Each partition should contain at least ~1 GB of data",
                 "Use at least 4 partition columns",
                 "Partition only large tables (around 1 TB and more)",
                 "Partition every table by its primary key"],
     "answer": [0, 2],
     "explanation": "Partition big tables on low-cardinality columns with ≥ 1 GB per partition — otherwise prefer liquid clustering."},
    {"topic": "Partitioning & Z-order",
     "q": "What does partition pruning do?",
     "options": ["Removes duplicate rows",
                 "Merges small partitions",
                 "Reads only the partition folders that match a filter on the partition column",
                 "Deletes old partitions"],
     "answer": 2,
     "explanation": "A filter on the partition column lets the engine skip whole folders."},
    {"topic": "Partitioning & Z-order",
     "q": "Why is `OPTIMIZE t ZORDER BY (col)` described as not incremental?",
     "options": ["It can only run once per table",
                 "It requires a full table scan of the transaction log",
                 "It only orders the newest file",
                 "The ordering isn't remembered: new data arrives unclustered and each ZORDER run rewrites the affected partition (the whole table if unpartitioned) again"],
     "answer": 3,
     "explanation": "Z-order is applied at OPTIMIZE time per partition. New data breaks it, and the next run re-sorts the whole partition. Liquid clustering is incremental."},
    {"topic": "Partitioning & Z-order",
     "q": "Delta data skipping relies on which information?",
     "options": ["Per-file min/max (and null count) statistics in the transaction log",
                 "The disk cache",
                 "Bloom filters on every column by default",
                 "A B-tree index on each column"],
     "answer": 0,
     "explanation": "Delta stores per-file column statistics (first 32 columns by default) and skips files whose min/max range can't match the filter."},
    {"topic": "Partitioning & Z-order",
     "q": "Which command compacts many small files of a Delta table into fewer large ones and is idempotent?",
     "options": ["`VACUUM t`",
                 "`OPTIMIZE t`",
                 "`ANALYZE TABLE t COMPUTE STATISTICS`",
                 "`REFRESH TABLE t`"],
     "answer": 1,
     "explanation": "OPTIMIZE bin-packs small files; re-running it with nothing to compact does nothing. VACUUM deletes unreferenced files, ANALYZE collects statistics."},
    # ---------------- Liquid clustering ----------------
    {"topic": "Liquid clustering",
     "q": "Which statement creates a table with liquid clustering?",
     "options": ["`CREATE TABLE t (...) BUCKETED BY (customer_id)`",
                 "`CREATE TABLE t (...) ZORDER BY (customer_id)`",
                 "`CREATE TABLE t (...) CLUSTER BY (customer_id)`",
                 "`CREATE TABLE t (...) PARTITIONED BY (customer_id)`"],
     "answer": 2,
     "explanation": "CLUSTER BY defines liquid clustering keys (or CLUSTER BY AUTO). ZORDER BY is an OPTIMIZE clause, not a table property."},
    {"topic": "Liquid clustering",
     "q": "How do you change the clustering keys of a liquid-clustered table?",
     "options": ["Recreate the table",
                 "`ALTER TABLE t PARTITION BY (new_col)`",
                 "`OPTIMIZE t ZORDER BY (new_col)`",
                 "`ALTER TABLE t CLUSTER BY (new_col)` — metadata only; new data and later OPTIMIZE runs use the new keys"],
     "answer": 3,
     "explanation": "Keys are changed without rewriting existing data; `OPTIMIZE t FULL` reclusters everything with the new keys if you want it now."},
    {"topic": "Liquid clustering",
     "q": "What does `OPTIMIZE t FULL` do on a liquid-clustered table?",
     "options": ["Reclusters all data in the table, not only the data that isn't clustered yet",
                 "Disables clustering",
                 "Runs OPTIMIZE on every table of the schema",
                 "Deletes old files"],
     "answer": 0,
     "explanation": "Plain OPTIMIZE is incremental; FULL forces reclustering of all records — e.g. after changing the keys."},
    {"topic": "Liquid clustering",
     "q": "Liquid clustering cannot be combined with which features? (Choose TWO)",
     "options": ["Deletion vectors",
                 "Predictive optimization",
                 "`PARTITIONED BY`",
                 "`ZORDER BY`"],
     "answer": [2, 3],
     "explanation": "A clustered table can't be partitioned or Z-ordered. Deletion vectors and predictive optimization work with it (predictive optimization even runs its OPTIMIZE)."},
    {"topic": "Liquid clustering",
     "q": "What is the maximum number of clustering keys for liquid clustering?",
     "options": ["1",
                 "32",
                 "4",
                 "Unlimited"],
     "answer": 2,
     "explanation": "Up to four columns, chosen from those used in filters. With highly correlated columns, keep only one."},
    {"topic": "Liquid clustering",
     "q": "What does `CLUSTER BY AUTO` require?",
     "options": ["An external table",
                 "A partitioned table",
                 "A SQL warehouse of size Large or bigger",
                 "Predictive optimization on a Unity Catalog managed table"],
     "answer": 3,
     "explanation": "Automatic liquid clustering lets predictive optimization choose keys from query patterns — available for UC managed tables."},
    {"topic": "Liquid clustering",
     "q": "For which workloads does Databricks especially recommend liquid clustering? (Choose TWO)",
     "options": ["Tables with skewed data distribution or changing access patterns",
                 "Only tables smaller than 1 MB",
                 "Tables filtered by high-cardinality columns",
                 "Tables that are never queried"],
     "answer": [0, 2],
     "explanation": "Liquid clustering is recommended for all new tables, especially high-cardinality filters, skew, fast growth, concurrent writes and changing patterns."},
    {"topic": "Liquid clustering",
     "q": "How do you create a liquid-clustered table with the DataFrame API?",
     "options": ["`df.write.partitionBy('c').saveAsTable('t')`",
                 "`df.write.clusterBy('c').saveAsTable('t')`",
                 "`df.write.bucketBy(4, 'c').saveAsTable('t')`",
                 "`df.orderBy('c').write.saveAsTable('t')`"],
     "answer": 1,
     "explanation": "DataFrameWriter.clusterBy (and DataStreamWriter.clusterBy / writeTo(...).clusterBy) create clustered tables."},
    {"topic": "Liquid clustering",
     "q": "You migrate a Hive-partitioned table to liquid clustering. Which approaches work? (Choose TWO)",
     "options": ["Create a new clustered table with CTAS (or DEEP CLONE) and switch readers to it",
                 "`OPTIMIZE t ZORDER BY (cols)`",
                 "`VACUUM t RETAIN 0 HOURS`",
                 "`ALTER TABLE t REPLACE PARTITIONED BY WITH CLUSTER BY (cols)`"],
     "answer": [0, 3],
     "explanation": "Recent runtimes can replace partitioning with clustering in place; otherwise rewrite the data into a new clustered table."},
    # ---------------- Predictive optimization ----------------
    {"topic": "Predictive optimization",
     "q": "Which maintenance operations does predictive optimization run? (Choose TWO)",
     "options": ["DROP TABLE",
                 "OPTIMIZE (including incremental clustering)",
                 "RESTORE",
                 "VACUUM"],
     "answer": [1, 3],
     "explanation": "Predictive optimization runs OPTIMIZE, VACUUM and ANALYZE on UC managed tables when it decides they pay off."},
    {"topic": "Predictive optimization",
     "q": "On which tables does predictive optimization run?",
     "options": ["Unity Catalog managed tables",
                 "External tables only",
                 "Hive metastore tables",
                 "Temporary views"],
     "answer": 0,
     "explanation": "Only UC managed tables (Delta and Iceberg). External tables need their own OPTIMIZE/VACUUM schedule."},
    {"topic": "Predictive optimization",
     "q": "Which statement enables predictive optimization for every table in a schema?",
     "options": ["`OPTIMIZE SCHEMA sales`",
                 "`ALTER SCHEMA sales ENABLE PREDICTIVE OPTIMIZATION`",
                 "`SET spark.databricks.predictive = true`",
                 "`ALTER SCHEMA sales SET TBLPROPERTIES ('optimize' = 'auto')`"],
     "answer": 1,
     "explanation": "ALTER CATALOG | SCHEMA | TABLE ... ENABLE | DISABLE | INHERIT PREDICTIVE OPTIMIZATION. Objects inherit from their parent by default."},
    {"topic": "Predictive optimization",
     "q": "Where can you see which predictive optimization operations ran and what they cost?",
     "options": ["`system.lakeflow.jobs`",
                 "`DESCRIBE DETAIL`",
                 "`system.storage.predictive_optimization_operations_history`",
                 "The compute event log"],
     "answer": 2,
     "explanation": "The predictive optimization history system table records operation type, status, metrics and usage per table."},
    {"topic": "Predictive optimization",
     "q": "A team runs a nightly job with `OPTIMIZE` and `VACUUM` on its UC managed tables, which also have predictive optimization enabled. What is the best recommendation?",
     "options": ["Keep both for safety",
                 "Disable predictive optimization",
                 "Run VACUUM RETAIN 0 HOURS instead",
                 "Remove the manual maintenance job — predictive optimization already runs these operations when useful"],
     "answer": 3,
     "explanation": "Manual maintenance duplicates the work, costs compute and can conflict with writers. Predictive optimization handles it for managed tables."},
    # ---------------- Compute failures & OOM ----------------
    {"topic": "Compute failures & OOM",
     "q": "A cluster fails to start with `CLOUD_PROVIDER_LAUNCH_FAILURE` / insufficient instance capacity. What should you do?",
     "options": ["Retry later, or choose another instance type / zone, use a pool or flexible node types — or serverless compute",
                 "Fix the notebook code",
                 "Increase spark.driver.maxResultSize",
                 "Reinstall the libraries"],
     "answer": 0,
     "explanation": "It's a cloud-side capacity problem (CLOUD_FAILURE), not your code."},
    {"topic": "Compute failures & OOM",
     "q": "A cluster terminates with `INIT_SCRIPT_FAILURE`. Where do you look first?",
     "options": ["The job's run history",
                 "The init script logs (and the script's path / permissions)",
                 "The query profile",
                 "system.billing.usage"],
     "answer": 1,
     "explanation": "The init script returned a non-zero exit code; its logs show which command failed. Also check the script location (workspace files/volumes) and read access."},
    {"topic": "Compute failures & OOM",
     "q": "In a notebook, `%pip install mylib==2.0` runs after `import mylib`, but `mylib.__version__` still shows 1.4. What fixes it?",
     "options": ["Install mylib as a cluster library as well",
                 "Restart the workspace",
                 "Run `dbutils.library.restartPython()` (and put %pip cells at the top of the notebook)",
                 "Clear the disk cache"],
     "answer": 2,
     "explanation": "The running Python process keeps the already-imported module. Restarting Python loads the newly installed version (state is lost)."},
    {"topic": "Compute failures & OOM",
     "q": "Which library source has the HIGHEST precedence when the same package is installed several ways?",
     "options": ["Databricks Runtime built-in version",
                 "Compute-scoped (cluster) library",
                 "A library on DBFS",
                 "Notebook-scoped library installed with %pip"],
     "answer": 3,
     "explanation": "Notebook-scoped libraries override compute-scoped libraries, which override the runtime's versions (Git folder modules rank even higher)."},
    {"topic": "Compute failures & OOM",
     "q": "A notebook runs `df.toPandas()` on a 300 GB table and shows *The spark driver has stopped unexpectedly and is restarting*. What is the problem?",
     "options": ["Driver out of memory — too much data collected to the driver",
                 "Executor out of memory",
                 "Data skew",
                 "A library conflict"],
     "answer": 0,
     "explanation": "collect()/toPandas() bring all rows to the driver. Aggregate, filter or limit in Spark, or write to a table — adding workers doesn't help."},
    {"topic": "Compute failures & OOM",
     "q": "One task of a join stage repeatedly fails with *ExecutorLostFailure … exceeding memory limits* after heavy spill, while the other tasks finish quickly. Most likely cause?",
     "options": ["Too many job parameters",
                 "A skewed key overloading one executor",
                 "An init script failure",
                 "Driver out of memory"],
     "answer": 1,
     "explanation": "Executor OOM concentrated on one task points to skew (or one oversized partition). Fix with AQE skew join, broadcast, salting or more partitions."},
    {"topic": "Compute failures & OOM",
     "q": "Which configurations reduce cost for an interactive all-purpose cluster without hurting its users much? (Choose TWO)",
     "options": ["Disabling Photon",
                 "Autoscaling between a small minimum and a larger maximum of workers",
                 "Auto-termination after a period of inactivity",
                 "A fixed size of 100 workers"],
     "answer": [1, 2],
     "explanation": "Auto-termination stops idle clusters; autoscaling adds workers only when needed."},
    {"topic": "Compute failures & OOM",
     "q": "A batch job uses spot workers and sometimes fails when nodes disappear mid-run. Which setup is the best compromise?",
     "options": ["Disable autoscaling",
                 "Only spot instances with no retries",
                 "Spot driver and spot workers",
                 "On-demand driver, spot workers with fallback to on-demand, plus task retries"],
     "answer": 3,
     "explanation": "Keep the driver on-demand (losing it kills the job), allow fallback to on-demand for workers and retry transient failures — or use on-demand / serverless for strict SLAs."},
    {"topic": "Compute failures & OOM",
     "q": "Why does serverless compute remove most cluster start-up failures?",
     "options": ["Databricks manages the capacity and environment — no VMs to request in your account, no init scripts, no cluster quotas",
                 "It never runs Spark",
                 "It runs on the driver only",
                 "It caches all tables in memory"],
     "answer": 0,
     "explanation": "With serverless, Databricks provisions compute from its own pool; what remains to troubleshoot is your code, environment/libraries and memory usage."},
]

render_quiz(questions, title="Section 12 · Troubleshooting, Monitoring and Optimization", pass_mark=0.8,
            meta="65 questions · run history & baselines, job & pipeline health, Spark UI (skew / shuffle / spill), AQE & caching, partitioning & Z-order, liquid clustering, predictive optimization, compute failures & OOM · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Run history & baselines · Job & pipeline health | `presentation/12-P1 - Monitoring Jobs and Pipeline Health` + `labs/12-L1` |
# MAGIC | Spark UI: skew, shuffle, spill · AQE, joins & caching | `presentation/12-P2 - Finding Bottlenecks - Skew, Shuffle and Spill` + `labs/12-L2` |
# MAGIC | Partitioning & Z-order · Liquid clustering · Predictive optimization | `presentation/12-P3 - Data Layout - Liquid Clustering and Predictive Optimization` + `labs/12-L3` |
# MAGIC | Compute failures & OOM | `presentation/12-P4 - Diagnosing Compute Failures - Startup, Libraries and Memory` + `labs/12-L4` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
