# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 06-Q · Exam Questions — Structured Streaming & Auto Loader
# MAGIC **43 exam-style questions** on streaming fundamentals (06-P1), Auto Loader (06-P2) and stateful streaming (06-P3).
# MAGIC Multi-answer questions say so. Target **≥ 80 %** before Section 07.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
# legacy-demo: input_file_name() is only mentioned in question text
questions = [
    # ---------------- Streaming fundamentals ----------------
    {"topic": "Streaming fundamentals",
     "q": "How does Structured Streaming model a data stream?",
     "options": ["As an unbounded input table to which new rows are appended; queries run incrementally over it",
                 "As a queue of messages that is emptied after reading",
                 "As a series of independent batch jobs with no shared state",
                 "As a materialized view refreshed nightly"],
     "answer": 0,
     "explanation": "New data = new rows in an unbounded table; the same DataFrame/SQL query is executed incrementally in micro-batches."},
    {"topic": "Streaming fundamentals",
     "q": "Which option is **required** for a production streaming write so it can recover after a failure without reprocessing or losing data?",
     "options": ["`outputMode`",
                 "`checkpointLocation`",
                 "`queryName`",
                 "`maxFilesPerTrigger`"],
     "answer": 1,
     "explanation": "The checkpoint stores offsets, commits and state. It is what makes restarts resume exactly where the stream stopped."},
    {"topic": "Streaming fundamentals",
     "q": "Two streaming queries write to different tables. Can they share the same checkpoint location?",
     "options": ["Only if the target tables are in the same schema",
                 "Yes, checkpoints are per workspace",
                 "No — every streaming writer needs its own checkpoint location",
                 "Yes, if both use availableNow"],
     "answer": 2,
     "explanation": "A checkpoint is the identity and memory of ONE stream. Sharing it corrupts progress tracking."},
    {"topic": "Streaming fundamentals",
     "q": "A notebook on **serverless** compute starts `df.writeStream.toTable('t')` without specifying a trigger. What happens?",
     "options": ["It runs in continuous mode",
                 "It runs with a 500 ms micro-batch interval",
                 "It runs once and stops",
                 "It fails: the default (processingTime 0) trigger is not supported; set `trigger(availableNow=True)`"],
     "answer": 3,
     "explanation": "Serverless supports only availableNow (and the deprecated once). The Spark default trigger is ProcessingTime(0), which is not allowed there."},
    {"topic": "Streaming fundamentals",
     "q": "What does `trigger(availableNow=True)` do?",
     "options": ["Processes all data available at start, possibly in several micro-batches, then stops",
                 "Processes one micro-batch only",
                 "Keeps running and checks for data every second",
                 "Processes data in real time with millisecond latency"],
     "answer": 0,
     "explanation": "availableNow is the incremental-batch trigger: all pending data (respecting rate limits such as maxFilesPerTrigger), then the query terminates. It replaces the deprecated trigger(once=True)."},
    {"topic": "Streaming fundamentals",
     "q": "A team wants fresh data every 15 minutes without paying for always-on compute. What is the recommended pattern?",
     "options": ["`trigger(processingTime='15 minutes')` on an all-purpose cluster",
                 "A stream with `trigger(availableNow=True)` scheduled every 15 minutes by a Lakeflow Job",
                 "`trigger(continuous='15 minutes')`",
                 "A batch job that reloads all files every 15 minutes"],
     "answer": 1,
     "explanation": "Scheduled availableNow runs give incremental, exactly-once processing and the compute stops between runs."},
    {"topic": "Streaming fundamentals",
     "q": "Which output mode writes **the whole result table** to the sink on every trigger?",
     "options": ["overwrite",
                 "append",
                 "complete",
                 "update"],
     "answer": 2,
     "explanation": "complete rewrites all result rows each trigger; append writes only new final rows; update writes only changed rows."},
    {"topic": "Streaming fundamentals",
     "q": "A stream counts orders per customer (no watermark) and uses `outputMode('append')`. What happens when it starts?",
     "options": ["It silently switches to complete mode",
                 "It appends a row per customer per micro-batch",
                 "It works but ignores late data",
                 "It fails with an AnalysisException — use complete mode or add a watermark (update needs foreachBatch + MERGE for Delta)"],
     "answer": 3,
     "explanation": "Append requires rows to be final; an aggregate without a watermark can always change, so Spark rejects it."},
    {"topic": "Streaming fundamentals",
     "q": "Which **two** mechanisms together give Structured Streaming its end-to-end exactly-once guarantee with a Delta sink?",
     "options": ["Caching the input DataFrame",
                 "Setting spark.sql.shuffle.partitions",
                 "An idempotent sink (Delta ignores re-committed micro-batches)",
                 "A replayable source with offsets tracked in the checkpoint (write-ahead log)"],
     "answer": [2, 3],
     "explanation": "Offsets are logged before processing; if a batch is replayed after a failure, the Delta sink recognises the batch and does not duplicate it."},
    {"topic": "Streaming fundamentals",
     "q": "Someone deletes the checkpoint of an append-mode stream that reads a folder of files into a Delta table. What happens on the next run?",
     "options": ["The stream fails permanently",
                 "All files in the folder are processed again, creating duplicates in the table",
                 "Only new files are processed",
                 "The table is truncated automatically"],
     "answer": 1,
     "explanation": "Without the checkpoint the stream has no memory of processed files/offsets and starts from the beginning."},
    {"topic": "Streaming fundamentals",
     "q": "Which operation is **not** supported on a non-aggregated streaming DataFrame?",
     "options": ["`where`",
                 "`withColumn`",
                 "`orderBy`",
                 "A join with a static DataFrame"],
     "answer": 2,
     "explanation": "Sorting a stream is only supported after an aggregation in complete output mode. Filters, projections and stream-static joins are fine."},
    {"topic": "Streaming fundamentals",
     "q": "A stream reads a Delta table with `spark.readStream.table('bronze')`. An engineer runs `DELETE FROM bronze WHERE ...`. What happens to the stream by default, and which option lets it continue processing new appends?",
     "options": ["Nothing; deletes are propagated automatically",
                 "It fails; only a full refresh helps",
                 "It reprocesses the whole table; use `maxFilesPerTrigger`",
                 "It fails on the next run; `skipChangeCommits` ignores commits that update or delete data"],
     "answer": 3,
     "explanation": "Delta streaming sources expect appends. skipChangeCommits ignores change commits (they are NOT propagated). Use the change data feed to propagate changes."},
    {"topic": "Streaming fundamentals",
     "q": "Which statement about `display(streaming_df)` in a notebook is true?",
     "options": ["It starts a streaming query to render live results — convenient for demos, not a production sink",
                 "It shows a static snapshot and never starts a query",
                 "It is the recommended way to write streams to Delta",
                 "It stops all active streams"],
     "answer": 0,
     "explanation": "display() on a streaming DataFrame starts a stream. Production streams write to a sink with a checkpoint; on serverless use availableNow writes."},
    {"topic": "Streaming fundamentals",
     "q": "In a streaming checkpoint, what is the role of the `offsets/` and `commits/` folders?",
     "options": ["Both store copies of the source data",
                 "offsets/ records what a micro-batch will read BEFORE it runs (write-ahead log); commits/ marks the batch as completed AFTER the sink commit",
                 "offsets/ holds the schema; commits/ holds the query plan",
                 "offsets/ stores the output rows; commits/ stores the input files"],
     "answer": 1,
     "explanation": "On restart, a batch with an offset entry but no commit is replayed with exactly the same input — the basis of exactly-once processing."},
    {"topic": "Streaming fundamentals",
     "q": "An older notebook uses `trigger(once=True)`. What is the recommended replacement on current Databricks runtimes?",
     "options": ["`trigger(processingTime='0 seconds')`",
                 "`trigger(continuous='1 second')`",
                 "`trigger(availableNow=True)`",
                 "No trigger at all"],
     "answer": 2,
     "explanation": "Trigger.Once is deprecated (DBR 11.3+). availableNow processes all available data (possibly in several micro-batches, respecting rate limits) and then stops."},
    # ---------------- Auto Loader ----------------
    {"topic": "Auto Loader",
     "q": "Which source format name is used to read files with Auto Loader?",
     "options": ["`incremental`",
                 "`autoloader`",
                 "`streamingFiles`",
                 "`cloudFiles`"],
     "answer": 3,
     "explanation": "`spark.readStream.format('cloudFiles')` with `cloudFiles.format` set to the file format."},
    {"topic": "Auto Loader",
     "q": "Which **two** options are needed for an Auto Loader stream that infers the schema of JSON files?",
     "options": ["`cloudFiles.schemaLocation`",
                 "`cloudFiles.maxFilesPerTrigger`",
                 "`cloudFiles.format`",
                 "`cloudFiles.useNotifications`"],
     "answer": [0, 2],
     "explanation": "The format tells Auto Loader how to parse; the schema location stores the inferred schema and its evolution history."},
    {"topic": "Auto Loader",
     "q": "Auto Loader infers the schema of JSON files with default options. What type do the columns get?",
     "options": ["Binary",
                 "STRING for every column (plus `_rescued_data`)",
                 "Exact types (long, double, boolean…)",
                 "VARIANT"],
     "answer": 1,
     "explanation": "For JSON, CSV and XML Auto Loader infers strings unless cloudFiles.inferColumnTypes = true."},
    {"topic": "Auto Loader",
     "q": "An Auto Loader stream should infer types but always read `order_ts` as TIMESTAMP and `price` as DECIMAL(10,2). Which option?",
     "options": ["`cloudFiles.format = 'timestamp'`",
                 "`rescuedDataColumn`",
                 "`cloudFiles.schemaHints = 'order_ts TIMESTAMP, price DECIMAL(10,2)'`",
                 "`cloudFiles.partitionColumns`"],
     "answer": 2,
     "explanation": "Schema hints override the inferred types of chosen columns (and can add columns not yet seen)."},
    {"topic": "Auto Loader",
     "q": "With the **default** schema evolution mode, a new column appears in the source files. What happens?",
     "options": ["The stream fails until an administrator edits the schema",
                 "The column is ignored",
                 "The column's values go to `_rescued_data` and the stream keeps running",
                 "The stream fails once with UnknownFieldException after adding the column to the schema; a restart continues with the new column"],
     "answer": 3,
     "explanation": "addNewColumns is the default when the schema is inferred. Combine it with job retries (or a Lakeflow pipeline) so restarts are automatic."},
    {"topic": "Auto Loader",
     "q": "Which schema evolution mode **never** fails the stream because of new columns and keeps their data in `_rescued_data`?",
     "options": ["rescue",
                 "none",
                 "failOnNewColumns",
                 "addNewColumns"],
     "answer": 0,
     "explanation": "rescue keeps the schema fixed and rescues unknown data. none ignores new columns (data lost unless a rescued data column is configured)."},
    {"topic": "Auto Loader",
     "q": "Which data ends up in Auto Loader's `_rescued_data` column? (choose **two**)",
     "options": ["Columns that are not part of the schema (e.g. in rescue mode)",
                 "Rows from files that were already processed",
                 "Rows removed by a WHERE clause",
                 "Values whose type doesn't match the schema"],
     "answer": [0, 3],
     "explanation": "Rescued data holds type mismatches, columns missing from the schema and case mismatches — the row itself is kept."},
    {"topic": "Auto Loader",
     "q": "After Auto Loader added a new column to its schema, the restarted stream fails when writing to the Delta table with a schema mismatch. What is missing?",
     "options": ["A new checkpoint",
                 "`cloudFiles.includeExistingFiles`",
                 "`.option('mergeSchema', 'true')` on the writer (or schema evolution enabled for the table)",
                 "`cloudFiles.inferColumnTypes`"],
     "answer": 2,
     "explanation": "Auto Loader evolves the stream's schema; the Delta sink must also be allowed to add the column."},
    {"topic": "Auto Loader",
     "q": "Where does Auto Loader keep track of which files it has already processed?",
     "options": ["In the Unity Catalog metastore",
                 "In the source folder as marker files",
                 "In the target table's transaction log",
                 "In the stream's checkpoint (a scalable key-value store)"],
     "answer": 3,
     "explanation": "Discovered/processed files are tracked in the checkpoint's RocksDB store — that's why it scales to millions of files. COPY INTO tracks loaded files with the target table."},
    {"topic": "Auto Loader",
     "q": "Which file detection mode does Auto Loader use by default?",
     "options": ["Directory listing",
                 "Delta change data feed",
                 "File notification with file events",
                 "Kafka topic polling"],
     "answer": 0,
     "explanation": "Directory listing is the default and needs no setup. File notification with file events is recommended for most workloads."},
    {"topic": "Auto Loader",
     "q": "A landing folder receives millions of files per day. Which configuration is recommended for efficient file discovery?",
     "options": ["Directory listing with `maxFilesPerTrigger = 1`",
                 "File notification mode using file events (`cloudFiles.useManagedFileEvents`)",
                 "COPY INTO scheduled every minute",
                 "`cloudFiles.includeExistingFiles = false`"],
     "answer": 1,
     "explanation": "File notification with file events (enabled on the external location) avoids listing huge directories; Databricks recommends it for most workloads."},
    {"topic": "Auto Loader",
     "q": "An Auto Loader stream is started for the first time on a folder that already contains 500 files. With default options, what is processed?",
     "options": ["Only the newest file",
                 "Only files that arrive after the start",
                 "All 500 existing files plus new ones",
                 "Nothing until file notifications are configured"],
     "answer": 2,
     "explanation": "cloudFiles.includeExistingFiles defaults to true (evaluated only at the first start)."},
    {"topic": "Auto Loader",
     "q": "Which SQL statement uses Auto Loader under the hood in a Lakeflow pipeline or Databricks SQL?",
     "options": ["`COPY INTO t FROM '/path' FILEFORMAT = JSON`",
                 "``CREATE TABLE t AS SELECT * FROM json.`/path` ``",
                 "`INSERT INTO t SELECT * FROM read_files('/path')`",
                 "`CREATE OR REFRESH STREAMING TABLE t AS SELECT * FROM STREAM read_files('/path', format => 'json')`"],
     "answer": 3,
     "explanation": "STREAM read_files in a streaming table is Auto Loader. COPY INTO is a separate batch command; the others are full reads."},
    {"topic": "Auto Loader",
     "q": "When is Auto Loader a better choice than COPY INTO? (choose **two**)",
     "options": ["The schema evolves and bad values must be rescued",
                 "The source receives millions of files",
                 "Files must be loaded into a view",
                 "The team only wants a one-off load of 20 files with plain SQL"],
     "answer": [0, 1],
     "explanation": "Auto Loader scales to millions of files and offers schema evolution modes and rescued data. COPY INTO is simpler for small, occasional SQL loads."},
    {"topic": "Auto Loader",
     "q": "An Auto Loader stream is given a full schema with `.schema('id INT, name STRING')` instead of inferring one. What is the default schema evolution mode then?",
     "options": ["failOnNewColumns",
                 "none",
                 "addNewColumns",
                 "rescue"],
     "answer": 1,
     "explanation": "addNewColumns is the default only when Auto Loader infers the schema; with a provided schema the default is none (new columns ignored unless a rescued data column is set)."},
    {"topic": "Auto Loader",
     "q": "Which **two** statements about `read_files` are correct?",
     "options": ["read_files can only read CSV files",
                 "read_files requires a checkpointLocation option in SQL",
                 "`SELECT * FROM read_files('/path', format => 'json')` is a one-time batch read of all files",
                 "`STREAM read_files('/path', format => 'json')` in a streaming table uses Auto Loader and reads only new files on each update"],
     "answer": [2, 3],
     "explanation": "Without STREAM, read_files is a batch table-valued function. With STREAM inside a streaming table it becomes an Auto Loader source; the pipeline manages checkpoints."},
    {"topic": "Auto Loader",
     "q": "An Auto Loader bronze stream must record which file each row came from. What should be added to the query?",
     "options": ["`input_file_name()`",
                 "`DESCRIBE HISTORY`",
                 "`cloudFiles.includeExistingFiles`",
                 "`.select('*', '_metadata.file_path')`"],
     "answer": 3,
     "explanation": "The hidden _metadata column (file_path, file_name, file_size, file_modification_time…) works with Auto Loader; input_file_name() is deprecated (DBR 13.3+) and not supported on serverless / standard access mode."},
    {"topic": "Auto Loader",
     "q": "A scheduled job runs an Auto Loader stream from a Unity Catalog volume into `main.bronze.orders`, with its checkpoint in another volume. Which privileges does the job's service principal need? (choose **two**)",
     "options": ["CREATE EXTERNAL LOCATION on the metastore",
                 "USE CATALOG / USE SCHEMA plus CREATE TABLE (first run) or MODIFY on the target table",
                 "READ VOLUME on the source volume and WRITE VOLUME on the checkpoint volume",
                 "Workspace admin rights"],
     "answer": [1, 2],
     "explanation": "Least privilege: read the source files, write the checkpoint/schema location, and create/modify the target table inside a catalog and schema it can use."},
    # ---------------- Stateful streaming ----------------
    {"topic": "Stateful streaming",
     "q": "Which operation is **stateful** in Structured Streaming?",
     "options": ["`where amount > 0`",
                 "`groupBy(window('ts', '10 minutes')).count()`",
                 "A join with a small static table",
                 "`select` of three columns"],
     "answer": 1,
     "explanation": "Aggregations keep intermediate results (state) across micro-batches. Projections, filters and stream-static joins are stateless."},
    {"topic": "Stateful streaming",
     "q": "`df.withWatermark('event_time', '1 hour')` — the latest event time seen so far is 15:40. What is the watermark?",
     "options": ["15:40",
                 "It depends on the processing time",
                 "14:40",
                 "16:40"],
     "answer": 2,
     "explanation": "Watermark = max event time seen − threshold = 15:40 − 1 hour."},
    {"topic": "Stateful streaming",
     "q": "Which **two** effects does a watermark have on a windowed aggregation?",
     "options": ["It sorts the output by event time",
                 "It turns the query into a batch query",
                 "State for windows older than the watermark can be removed",
                 "Data older than the watermark may be dropped as too late"],
     "answer": [2, 3],
     "explanation": "Watermarks bound lateness and let Spark clean up state; in append mode they also decide when a window is final."},
    {"topic": "Stateful streaming",
     "q": "A windowed count uses a watermark and `outputMode('append')`. When is the result row for the 10:00–10:30 window written?",
     "options": ["Once, after the watermark has passed 10:30",
                 "Immediately when the first event arrives",
                 "At every trigger, updated each time",
                 "Never — append mode can't be used with windows"],
     "answer": 0,
     "explanation": "In append mode a window is emitted exactly once, when it becomes final (watermark > window end)."},
    {"topic": "Stateful streaming",
     "q": "Which window function creates **overlapping** windows of 30 minutes every 10 minutes?",
     "options": ["`window('ts', '30 minutes')`",
                 "`window('ts', '30 minutes', '10 minutes')`",
                 "`session_window('ts', '10 minutes')`",
                 "`window('ts', '10 minutes', '30 minutes')`"],
     "answer": 1,
     "explanation": "The third argument is the slide duration → sliding (overlapping) windows. Two arguments = tumbling; session_window = gap-based."},
    {"topic": "Stateful streaming",
     "q": "A stream must drop duplicate events (same `event_id`) without keeping every id forever. Which code?",
     "options": ["`df.orderBy('event_id').dropDuplicates()`",
                 "`df.distinct()`",
                 "`df.withWatermark('event_time', '2 hours').dropDuplicatesWithinWatermark(['event_id'])`",
                 "`df.dropDuplicates(['event_id'])`"],
     "answer": 2,
     "explanation": "With a watermark, dedup state is bounded. dropDuplicates without a watermark keeps all ids in state forever."},
    {"topic": "Stateful streaming",
     "q": "A team must **upsert** each micro-batch of CDC records into a Delta table with MERGE. What should they use?",
     "options": ["`outputMode('complete')`",
                 "`outputMode('update').toTable(...)`",
                 "`trigger(once=True)`",
                 "`foreachBatch` with a function that runs MERGE"],
     "answer": 3,
     "explanation": "foreachBatch exposes each micro-batch as a batch DataFrame so batch operations such as MERGE can be used."},
    {"topic": "Stateful streaming",
     "q": "What delivery guarantee does `foreachBatch` provide for the code inside the function?",
     "options": ["At-least-once — a retried micro-batch runs the function again, so the logic should be idempotent",
                 "At-most-once",
                 "Exactly-once automatically",
                 "No guarantee at all"],
     "answer": 0,
     "explanation": "Make the function idempotent (e.g. MERGE on keys, or txnAppId/txnVersion for Delta writes)."},
    {"topic": "Stateful streaming",
     "q": "What should be added to a stream-stream **outer** join so it can produce results and bound its state?",
     "options": ["A broadcast hint",
                 "Watermarks on both inputs and an event-time range condition",
                 "Complete output mode",
                 "`trigger(once=True)`"],
     "answer": 1,
     "explanation": "Stream-stream joins keep both sides in state; watermarks + time constraints let Spark know when rows can no longer match."},
    {"topic": "Stateful streaming",
     "q": "Reading from Kafka with `spark.readStream.format('kafka')`, in which column is the message payload and in what type?",
     "options": ["`body` as JSON",
                 "`payload` as STRING",
                 "`value` as BINARY — cast it to string and parse it (e.g. from_json)",
                 "`data` as VARIANT"],
     "answer": 2,
     "explanation": "Kafka rows have key, value (binary), topic, partition, offset and timestamp columns."},
]

render_quiz(questions, title="Section 06 · Structured Streaming & Auto Loader", pass_mark=0.8,
            meta="43 questions · streaming fundamentals, Auto Loader, stateful streaming · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Streaming fundamentals | `presentation/06-P1 - Structured Streaming Fundamentals` + `labs/06-L1` |
# MAGIC | Auto Loader | `presentation/06-P2 - Auto Loader` + `labs/06-L2` |
# MAGIC | Stateful streaming | `presentation/06-P3 - Stateful Streaming …` + `labs/06-L3` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
