# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 07-Q · Exam Questions — Data Transformation & Modeling
# MAGIC **55 exam-style questions** on cleaning & shaping data (07-P1), combining & aggregating (07-P2) and gold modeling, SCD &
# MAGIC data quality (07-P3). Multi-answer questions say so. Target **≥ 80 %** before Section 08.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Cleaning & shaping ----------------
    {"topic": "Cleaning & shaping",
     "q": "A bronze table was loaded from CSV without type inference. Which statement best describes the bronze → silver step?",
     "options": ["Standardise values, cast columns to proper types, handle NULLs and remove duplicates, writing the result to a new silver table",
                 "Delete the bronze table once silver is written, to save storage",
                 "Aggregate the data per day so BI tools can read it",
                 "Convert the Delta table back to CSV so it can be re-ingested"],
     "answer": 0,
     "explanation": "Silver = clean, typed, deduplicated, conformed data. Bronze is kept as replayable history; aggregation is a gold concern."},
    {"topic": "Cleaning & shaping",
     "q": "Which call returns count, mean, stddev, min, max **and the 25 %, 50 % and 75 % percentiles** of the columns of `df`?",
     "options": ["`df.describe()`",
                 "`df.summary()`",
                 "`df.count()`",
                 "`df.printSchema()`"],
     "answer": 1,
     "explanation": "summary() = describe() statistics plus percentiles (you can also pick which statistics to compute)."},
    {"topic": "Cleaning & shaping",
     "q": "A table has 3 billion rows. An analyst needs the number of distinct users quickly and accepts a small error. Which function fits?",
     "options": ["`count(user_id)`",
                 "`count(DISTINCT user_id)`",
                 "`approx_count_distinct(user_id)`",
                 "`collect_set(user_id)` followed by `size()`"],
     "answer": 2,
     "explanation": "approx_count_distinct uses HyperLogLog++: small memory, fast; default rsd (maximum relative standard deviation) = 0.05."},
    {"topic": "Cleaning & shaping",
     "q": "Column `score` has values 10, NULL, 20. What do `count(*)`, `count(score)` and `avg(score)` return?",
     "options": ["3, 2, 10",
                 "3, 3, 10",
                 "2, 2, 15",
                 "3, 2, 15"],
     "answer": 3,
     "explanation": "count(*) counts rows; count(col) and avg(col) ignore NULLs: (10 + 20) / 2 = 15."},
    {"topic": "Cleaning & shaping",
     "q": "On serverless compute (ANSI mode on), `SELECT CAST(amount AS DECIMAL(10,2)) FROM bronze` fails because one row contains `'N/A'`. Which expression returns NULL for such values instead?",
     "options": ["`try_cast(amount AS DECIMAL(10,2))`",
                 "`CAST(amount AS STRING)`",
                 "`amount::decimal(10,2)`",
                 "`decimal(amount)`"],
     "answer": 0,
     "explanation": "try_cast (and try_to_timestamp, try_divide…) return NULL for invalid input; cast raises an error under ANSI mode. `::` is just cast syntax."},
    {"topic": "Cleaning & shaping",
     "q": "Column `paid_at` holds timestamps in two formats: `2026-03-01 10:15:00` and `01/03/2026 10:15`. Which expression parses both?",
     "options": ["`to_timestamp(paid_at)`",
                 "`coalesce(try_to_timestamp(paid_at, 'yyyy-MM-dd HH:mm:ss'), try_to_timestamp(paid_at, 'dd/MM/yyyy HH:mm'))`",
                 "`to_date(paid_at, 'yyyy-MM-dd HH:mm:ss')`",
                 "`cast(paid_at AS TIMESTAMP)`"],
     "answer": 1,
     "explanation": "Try each format and keep the first non-NULL result. The single-format calls fail (ANSI) or return NULL for the other format."},
    {"topic": "Cleaning & shaping",
     "q": "Which PySpark call keeps only rows where `payment_id` is not NULL, whatever the other columns contain?",
     "options": ["`df.dropna(how='all')`",
                 "`df.dropna()`",
                 "`df.dropna(subset=['payment_id'])`",
                 "`df.fillna({'payment_id': ''})`"],
     "answer": 2,
     "explanation": "dropna() without arguments drops rows with a NULL in ANY column; subset restricts the check. how='all' drops only fully-NULL rows."},
    {"topic": "Cleaning & shaping",
     "q": "Which PySpark statement replaces NULLs in `currency` with `'USD'` and NULLs in `qty` with 0, leaving other columns unchanged?",
     "options": ["`df.replace(None, 'USD')`",
                 "`df.fillna('USD')`",
                 "`df.na.drop(subset=['currency', 'qty'])`",
                 "`df.fillna({'currency': 'USD', 'qty': 0})`"],
     "answer": 3,
     "explanation": "fillna/na.fill with a dict fills per column. A single string value would only apply to string columns."},
    {"topic": "Cleaning & shaping",
     "q": "`profile` is a STRING column containing JSON such as `{\"address\": {\"city\": \"Riyadh\"}}`. Which Databricks SQL expression returns the city? **(Select TWO.)**",
     "options": ["`profile.address.city`",
                 "`explode(profile)`",
                 "`from_json(profile, 'address STRUCT<city: STRING>').address.city`",
                 "`profile:address:city`"],
     "answer": [2, 3],
     "explanation": "The `:` path syntax extracts from JSON strings; from_json parses into a struct you can navigate with dots. Dot notation directly on a STRING fails."},
    {"topic": "Cleaning & shaping",
     "q": "What is the purpose of `schema_of_json` when parsing JSON strings with `from_json`?",
     "options": ["It validates that every row matches the table schema",
                 "It derives a schema (DDL string) from a sample JSON value, which from_json can then use",
                 "It converts a struct back into a JSON string",
                 "It infers the schema of all files in a folder"],
     "answer": 1,
     "explanation": "schema_of_json('<sample>') returns something like STRUCT<address: STRUCT<city: STRING>, …> — pass it to from_json."},
    {"topic": "Cleaning & shaping",
     "q": "Orders have an `items` array; cancelled orders have an **empty** array. After `SELECT order_id, explode(items) FROM orders`, what happens to cancelled orders?",
     "options": ["They appear once with a NULL item",
                 "The query fails",
                 "They are removed from the result",
                 "They appear once with an empty struct"],
     "answer": 2,
     "explanation": "explode produces no row for empty or NULL arrays. explode_outer keeps such rows with a NULL element."},
    {"topic": "Cleaning & shaping",
     "q": "`email` contains `lina.ali1@company.com`. Which PySpark expression returns `company.com`?",
     "options": ["`F.split('email', '@').getItem(0)`",
                 "`F.split('email', '@').getItem(2)`",
                 "`F.substring('email', '@', 1)`",
                 "`F.split('email', '@').getItem(1)`"],
     "answer": 3,
     "explanation": "split returns an array; getItem / [] are 0-based, so index 1 is the part after '@'. (SQL split_part(email, '@', 2) is 1-based.)"},
    {"topic": "Cleaning & shaping",
     "q": "Payments are re-sent when their status changes, with a later `updated_at`. You must keep **the most recent version of each payment**. Which approach is deterministic?",
     "options": ["`row_number()` over a window partitioned by `payment_id` ordered by `updated_at` DESC, keeping rank 1",
                 "`df.dropDuplicates(['payment_id'])`",
                 "`df.distinct()`",
                 "`df.orderBy('updated_at').dropDuplicates(['payment_id'])`"],
     "answer": 0,
     "explanation": "dropDuplicates(subset) keeps an arbitrary row (ordering beforehand is not guaranteed to be respected); distinct() only removes identical rows."},
    {"topic": "Cleaning & shaping",
     "q": "A bronze table has an `_ingested_at` column that differs for every load. Duplicate loads created identical business rows. Why does `df.distinct()` NOT remove them?",
     "options": ["Delta tables prevent duplicates, so there is nothing to remove",
                 "The rows differ in `_ingested_at`, so they are not identical — drop that column (or dedup on the business columns) first",
                 "distinct() only works on streaming DataFrames",
                 "distinct() ignores string columns"],
     "answer": 1,
     "explanation": "distinct compares all columns. Remove ingestion metadata before deduplicating, or use dropDuplicates / row_number on the key."},
    {"topic": "Cleaning & shaping",
     "q": "`df.write.saveAsTable('silver_orders')` is run a second time and the table already exists. What happens?",
     "options": ["The data is appended",
                 "The table is overwritten",
                 "The write fails because the default save mode is errorifexists",
                 "Nothing happens"],
     "answer": 2,
     "explanation": "Default mode = errorifexists. Use mode('overwrite') (+ overwriteSchema) or mode('append'); mode('ignore') does nothing."},
    {"topic": "Cleaning & shaping",
     "q": "Which SQL statement is the equivalent of `df.write.mode('overwrite').option('overwriteSchema', 'true').saveAsTable('t')`, where `t` must also get the new schema of `df`?",
     "options": ["`INSERT INTO t SELECT …`",
                 "`CREATE TABLE IF NOT EXISTS t AS SELECT …`",
                 "`MERGE INTO t USING …`",
                 "`CREATE OR REPLACE TABLE t AS SELECT …`"],
     "answer": 3,
     "explanation": "CREATE OR REPLACE TABLE … AS replaces data and schema (keeping table history). INSERT OVERWRITE keeps the existing schema."},
    {"topic": "Cleaning & shaping",
     "q": "Which PySpark call renames column `cust_id` to `customer_id` and keeps all other columns?",
     "options": ["`df.withColumnRenamed('cust_id', 'customer_id')`",
                 "`df.select('customer_id')`",
                 "`df.alias('customer_id')`",
                 "`df.withColumn('customer_id', 'cust_id')`"],
     "answer": 0,
     "explanation": "withColumnRenamed(existing, new) (several at once: withColumnsRenamed({...})). withColumn needs a Column expression and would ADD a column; alias renames a DataFrame, not a column."},
    {"topic": "Cleaning & shaping",
     "q": "`df` already has a column `total` (DOUBLE). What does `df.withColumn('total', F.col('total').cast('decimal(10,2)'))` do?",
     "options": ["Changes the type of `total` in `df` in place",
                 "Returns a new DataFrame whose `total` column is **replaced** by the DECIMAL version (df itself is unchanged)",
                 "Fails because the column already exists",
                 "Adds a second column named `total`"],
     "answer": 1,
     "explanation": "withColumn replaces a column with the same name; DataFrames are immutable, so the result must be assigned (df = df.withColumn(...))."},
    # ---------------- Combining & aggregating ----------------
    {"topic": "Combining & aggregating",
     "q": "`orders` has 343 rows, 2 of them with a customer_id missing from `customers`; 92 customers have no order. How many rows does `orders.join(customers, 'customer_id', 'left')` return (customer_id is unique in customers)?",
     "options": ["341",
                 "435",
                 "343",
                 "433"],
     "answer": 2,
     "explanation": "Left join keeps every left row: 341 matches + 2 unmatched orders = 343. Right would be 433, full 435."},
    {"topic": "Combining & aggregating",
     "q": "Which join returns the orders whose customer_id does **not** exist in `customers`, with order columns only?",
     "options": ["`orders.join(customers, 'customer_id', 'right')`",
                 "`orders.join(customers, 'customer_id', 'left_semi')`",
                 "`orders.crossJoin(customers)`",
                 "`orders.join(customers, 'customer_id', 'left_anti')`"],
     "answer": 3,
     "explanation": "left_anti = rows of the left side with no match (NOT EXISTS). left_semi = rows with a match (EXISTS)."},
    {"topic": "Combining & aggregating",
     "q": "A customer placed 12 orders. How many times does that customer appear in `customers.join(orders, 'customer_id', 'left_semi')`?",
     "options": ["1",
                 "13",
                 "12",
                 "0"],
     "answer": 0,
     "explanation": "A semi join only filters the left side — each qualifying left row appears once, with left columns only."},
    {"topic": "Combining & aggregating",
     "q": "You need a row for every combination of 10 countries and 6 months (even without sales) before left-joining actual revenue. Which operation builds it?",
     "options": ["`countries.union(months)`",
                 "`countries.crossJoin(months)`",
                 "`countries.join(months, 'month', 'full')`",
                 "`countries.join(months, 'country', 'left_semi')`"],
     "answer": 1,
     "explanation": "A cross join returns every combination: 10 × 6 = 60 rows."},
    {"topic": "Combining & aggregating",
     "q": "Revenue must be joined to targets on **both** country and month (same column names on both sides). Which PySpark call is correct?",
     "options": ["`revenue.join(targets, ('country', 'month'), 'cross')`",
                 "`revenue.join(targets, 'country' and 'month', 'left')`",
                 "`revenue.join(targets, ['country', 'month'], 'left')`",
                 "`revenue.join(targets, 'country', 'left').join(targets, 'month', 'left')`"],
     "answer": 2,
     "explanation": "Pass a list of column names for multiple keys (each appears once in the result). With different names use (a.x == b.y) & (a.m == b.n)."},
    {"topic": "Combining & aggregating",
     "q": "After `a.join(b, a.customer_id == b.customer_id)`, `select('customer_id')` fails with `AMBIGUOUS_REFERENCE`. Which fixes are valid? **(Select TWO.)**",
     "options": ["Add `.distinct()` before the select",
                 "Alias the DataFrames and select `'a.customer_id'`",
                 "Set `spark.sql.shuffle.partitions` to 1",
                 "Join with `a.join(b, 'customer_id')` instead"],
     "answer": [1, 3],
     "explanation": "A join on the column name keeps a single key column; aliases disambiguate the two columns an expression join keeps."},
    {"topic": "Combining & aggregating",
     "q": "Two tables are joined on `customer_id`. Some rows on **both** sides have `customer_id = NULL`. What happens to them in an inner join `ON a.customer_id = b.customer_id`?",
     "options": ["They don't match: NULL = NULL is not true",
                 "The join fails",
                 "They match each other",
                 "They are matched to every row"],
     "answer": 0,
     "explanation": "NULL = NULL evaluates to NULL, so no match. Use the null-safe operator <=> (eqNullSafe) if NULL keys should match."},
    {"topic": "Combining & aggregating",
     "q": "A 5-billion-row fact table is joined to a 2 MB country lookup. Which technique avoids shuffling the fact table?",
     "options": ["`fact.repartition(1000)` before the join",
                 "A broadcast join: `fact.join(F.broadcast(countries), 'country_code')`",
                 "Calling `collect()` on the fact table first",
                 "A cross join"],
     "answer": 1,
     "explanation": "Broadcasting the small side sends a copy to every executor; the big side is joined in place without a shuffle."},
    {"topic": "Combining & aggregating",
     "q": "Which setting makes Spark broadcast tables automatically when they are smaller than a given size (and disables it with `-1`)?",
     "options": ["`spark.default.parallelism`",
                 "`spark.sql.shuffle.partitions`",
                 "`spark.sql.autoBroadcastJoinThreshold`",
                 "`spark.driver.memory`"],
     "answer": 2,
     "explanation": "autoBroadcastJoinThreshold (10 MB by default in Apache Spark). On serverless it is managed — use hints instead."},
    {"topic": "Combining & aggregating",
     "q": "What does `spark.sql.shuffle.partitions` control?",
     "options": ["The number of executors in the cluster",
                 "The default partitions of RDD operations such as parallelize",
                 "The number of files written by every table",
                 "The number of partitions used after a shuffle (joins, aggregations) in DataFrame/SQL operations"],
     "answer": 3,
     "explanation": "Default 200 in Apache Spark (auto on serverless). spark.default.parallelism is the RDD equivalent."},
    {"topic": "Combining & aggregating",
     "q": "A job on classic compute fails with out-of-memory errors when calling `collect()` on a large result, while executors are fine. Which parameter is relevant?",
     "options": ["`spark.driver.memory`",
                 "`spark.sql.autoBroadcastJoinThreshold`",
                 "`spark.sql.shuffle.partitions`",
                 "`spark.executor.memory`"],
     "answer": 0,
     "explanation": "collect() brings all data to the driver. (Better: don't collect large results.) Memory settings are cluster configuration, set before the cluster starts."},
    {"topic": "Combining & aggregating",
     "q": "You changed `spark.sql.shuffle.partitions` from 200 to 64 to speed up a job. What is the correct way to validate the change?",
     "options": ["Assume it helped because fewer partitions are always faster",
                 "Re-run the same query on the same data, compare duration and the query profile (spill, skew, task sizes), and keep the change only if it helps",
                 "Restart the workspace",
                 "Check that the table still has 200 files"],
     "answer": 1,
     "explanation": "Tuning is measure → change one parameter → re-measure. Too few partitions can cause spill; too many cause overhead."},
    {"topic": "Combining & aggregating",
     "q": "`a` has 100 rows and `b` has 80 rows; 30 rows are identical in both. How many rows does `a.union(b)` return?",
     "options": ["30",
                 "150",
                 "180",
                 "100"],
     "answer": 2,
     "explanation": "DataFrame union behaves like SQL UNION ALL: duplicates are kept → 180. a.union(b).distinct() (SQL UNION) would give 150 if each side has no internal duplicates."},
    {"topic": "Combining & aggregating",
     "q": "`a` has columns (id, name) and `b` has (name, id), both STRING. Which call stacks them correctly?",
     "options": ["`a.crossJoin(b)`",
                 "`a.intersect(b)`",
                 "`a.union(b)`",
                 "`a.unionByName(b)`"],
     "answer": 3,
     "explanation": "union matches by position (the names and ids would be mixed silently); unionByName matches by column name."},
    {"topic": "Combining & aggregating",
     "q": "Which SQL operation returns the rows of query A that are **not** in query B, without duplicates?",
     "options": ["`A EXCEPT B` (also written `MINUS`)",
                 "`A UNION ALL B`",
                 "`A LEFT SEMI JOIN B`",
                 "`A INTERSECT B`"],
     "answer": 0,
     "explanation": "EXCEPT / MINUS = set difference (distinct). EXCEPT ALL keeps duplicates; DataFrame equivalents are subtract() and exceptAll()."},
    {"topic": "Combining & aggregating",
     "q": "Which aggregate returns the **distinct** product categories bought by each customer as an array?",
     "options": ["`array_contains('category')`",
                 "`collect_set('category')`",
                 "`collect_list('category')`",
                 "`explode('category')`"],
     "answer": 1,
     "explanation": "collect_set removes duplicates; collect_list keeps every value (and array_distinct(collect_list(…)) would also work)."},
    {"topic": "Combining & aggregating",
     "q": "You need revenue per category with **one column per month**. Which PySpark pattern does this?",
     "options": ["`df.groupBy('category', 'month').sum('amount')`",
                 "`df.groupBy('month').agg(F.collect_list('category'))`",
                 "`df.groupBy('category').pivot('month').agg(F.sum('amount'))`",
                 "`df.select('category', F.explode('month'))`"],
     "answer": 2,
     "explanation": "pivot turns the distinct values of `month` into columns. Passing the list of values avoids an extra job."},
    {"topic": "Combining & aggregating",
     "q": "Products have units sold 50, 40, 40, 30 in one category. What does `dense_rank()` ordered by units DESC return?",
     "options": ["1, 2, 2, 4",
                 "1, 1, 1, 1",
                 "1, 2, 3, 4",
                 "1, 2, 2, 3"],
     "answer": 3,
     "explanation": "dense_rank gives ties the same rank without gaps. rank → 1, 2, 2, 4; row_number → 1, 2, 3, 4."},
    {"topic": "Combining & aggregating",
     "q": "Which window expression computes each customer's **running total** of order amounts in time order?",
     "options": ["`F.sum('total').over(Window.partitionBy('customer_id').orderBy('order_ts').rowsBetween(Window.unboundedPreceding, Window.currentRow))`",
                 "`F.sum('total').over(Window.partitionBy('customer_id'))`",
                 "`df.groupBy('customer_id').agg(F.sum('total'))`",
                 "`F.lag('total').over(Window.orderBy('order_ts'))`"],
     "answer": 0,
     "explanation": "Partition by customer, order by time, frame from the first row to the current row. Without orderBy you get the customer's grand total on every row."},
    {"topic": "Combining & aggregating",
     "q": "For each order you need the timestamp of the same customer's **previous** order. Which function?",
     "options": ["`first('order_ts')`",
                 "`lag('order_ts', 1)`",
                 "`lead('order_ts', 1)`",
                 "`rank()`"],
     "answer": 1,
     "explanation": "lag looks at the previous row of the window (partitioned by customer, ordered by order_ts); lead looks at the next one."},
    {"topic": "Combining & aggregating",
     "q": "Which SQL expression keeps only the items with quantity ≥ 2 **inside** each order's `items` array, without exploding it?",
     "options": ["`explode(items) WHERE quantity >= 2`",
                 "`transform(items, i -> i.quantity >= 2)`",
                 "`filter(items, i -> i.quantity >= 2)`",
                 "`exists(items, i -> i.quantity >= 2)`"],
     "answer": 2,
     "explanation": "filter returns the matching elements. transform would return an array of booleans; exists returns one boolean."},
    {"topic": "Combining & aggregating",
     "q": "Which setting controls the default number of partitions for **RDD** operations such as `sc.parallelize` and RDD shuffles (not DataFrame/SQL shuffles)?",
     "options": ["`spark.sql.shuffle.partitions`",
                 "`spark.executor.memory`",
                 "`spark.sql.files.maxPartitionBytes`",
                 "`spark.default.parallelism`"],
     "answer": 3,
     "explanation": "spark.default.parallelism (default: total executor cores) is the RDD setting, set in the cluster config; DataFrame/SQL shuffles use spark.sql.shuffle.partitions."},
    # ---------------- Gold, SCD & data quality ----------------
    {"topic": "Gold, SCD & data quality",
     "q": "BI dashboards read an expensive aggregation many times per hour; the source tables change a few times a day. The team wants the result precomputed and refreshed incrementally when possible, with minimal custom code. Which object?",
     "options": ["A materialized view",
                 "A view",
                 "A temporary view",
                 "A Python UDF"],
     "answer": 0,
     "explanation": "Materialized views store precomputed results and are refreshed (incrementally where possible). A view recomputes on every query."},
    {"topic": "Gold, SCD & data quality",
     "q": "Which statements about **views** in Unity Catalog are true? **(Select TWO.)**",
     "options": ["A view processes only new rows since its last refresh",
                 "A view is a saved query evaluated when it is read, so it always reflects the current data",
                 "A view can expose only selected columns or rows of a table to a group",
                 "A view stores a copy of the data and must be refreshed"],
     "answer": [1, 2],
     "explanation": "Views store no data (no refresh), are always current, and are a common security layer. Processing only new rows describes a streaming table."},
    {"topic": "Gold, SCD & data quality",
     "q": "New JSON files land every few minutes and must be appended to a table, processing each file exactly once, using SQL only. Which gold/silver object fits?",
     "options": ["A materialized view with a full recompute each time",
                 "A temporary view",
                 "A streaming table: `CREATE STREAMING TABLE … AS SELECT * FROM STREAM read_files(…)`",
                 "A view over `read_files`"],
     "answer": 2,
     "explanation": "Streaming tables process only new source data on each refresh — ideal for append-only ingestion."},
    {"topic": "Gold, SCD & data quality",
     "q": "In a star schema for sales, which table holds `quantity` and `amount` per order line together with keys to date, customer and product?",
     "options": ["A bridge view",
                 "The bronze table",
                 "A dimension table",
                 "The fact table"],
     "answer": 3,
     "explanation": "Facts hold measures at a defined grain (one row per order line) plus foreign keys; dimensions hold descriptive attributes."},
    {"topic": "Gold, SCD & data quality",
     "q": "Reports must show every order under the country the customer lived in **when the order was placed**, even after customers move. How should the customer dimension be maintained?",
     "options": ["SCD type 2 — close the current row and insert a new version with validity dates",
                 "Drop and recreate the dimension from the latest export every night",
                 "Deduplicate customers with dropDuplicates(['customer_id'])",
                 "SCD type 1 — overwrite changed attributes"],
     "answer": 0,
     "explanation": "SCD2 keeps every version (valid_from / valid_to / is_current); a point-in-time join finds the version valid at order time."},
    {"topic": "Gold, SCD & data quality",
     "q": "An SCD2 MERGE detects changes with `t.email <> s.email`. A customer who had **no e-mail (NULL)** now has one. What happens?",
     "options": ["The MERGE fails",
                 "The change is missed, because `NULL <> 'x'` is NULL, not TRUE",
                 "The customer is deleted",
                 "A new version is created correctly"],
     "answer": 1,
     "explanation": "Use null-safe comparisons: NOT (t.email <=> s.email) or t.email IS DISTINCT FROM s.email."},
    {"topic": "Gold, SCD & data quality",
     "q": "Why does the classic single-MERGE SCD type 2 pattern send each **changed** row twice in the source (once with `merge_key = customer_id`, once with `merge_key = NULL`)?",
     "options": ["To make the MERGE idempotent",
                 "Because Delta requires two rows per key",
                 "Because one source row can trigger only one action: the matching copy closes the current row, the NULL-key copy never matches and is inserted as the new version",
                 "To delete the old version"],
     "answer": 2,
     "explanation": "WHEN MATCHED → UPDATE (close), WHEN NOT MATCHED → INSERT (new version). New customers only need the first copy."},
    {"topic": "Gold, SCD & data quality",
     "q": "A silver payments table must not contain negative amounts, whatever job writes to it. What enforces this in the table itself?",
     "options": ["`ALTER TABLE payments ADD CONSTRAINT pk PRIMARY KEY (payment_id)`",
                 "A comment on the column",
                 "A view that filters negative amounts",
                 "`ALTER TABLE payments ADD CONSTRAINT amount_non_negative CHECK (amount >= 0)`"],
     "answer": 3,
     "explanation": "CHECK constraints are enforced on every write (the whole write fails on a violation). PK/FK constraints in Unity Catalog are informational only."},
    {"topic": "Gold, SCD & data quality",
     "q": "`ALTER TABLE payments ADD CONSTRAINT positive CHECK (amount > 0)` fails. The most likely reason:",
     "options": ["Existing rows already violate the condition",
                 "CHECK constraints are not supported on Delta tables",
                 "Constraints can only be added with CREATE TABLE",
                 "The table has too many columns"],
     "answer": 0,
     "explanation": "Delta validates existing data when a CHECK constraint is added. Fix or quarantine the violating rows first."},
    {"topic": "Gold, SCD & data quality",
     "q": "Rows that break data quality rules must be kept for investigation, with the reason, while clean rows continue to silver. Which strategy is this?",
     "options": ["Fail",
                 "Quarantine",
                 "Fix",
                 "Drop"],
     "answer": 1,
     "explanation": "Quarantine = write failing rows (plus the broken rule names) to a separate table; valid + quarantine = input."},
    {"topic": "Gold, SCD & data quality",
     "q": "Which is generally the **fastest** way to apply the same string clean-up in many queries, while keeping it reusable and governed in Unity Catalog?",
     "options": ["A pandas UDF",
                 "Collecting the data to the driver and cleaning it in Python",
                 "A SQL UDF: `CREATE FUNCTION clean(m STRING) RETURNS STRING RETURN regexp_replace(lower(trim(m)), '[ -]+', '_')`",
                 "A Python UDF registered with `@udf`"],
     "answer": 2,
     "explanation": "SQL UDFs are inlined into the query plan like built-in functions and are UC objects (GRANT EXECUTE). Python UDFs process row by row."},
    {"topic": "Gold, SCD & data quality",
     "q": "In a Lakeflow Spark Declarative Pipeline, which expectation **removes** rows that fail the rule but lets the update continue?",
     "options": ["`CONSTRAINT valid_amount EXPECT (amount >= 0)`",
                 "`CONSTRAINT valid_amount EXPECT (amount >= 0) ON VIOLATION FAIL UPDATE`",
                 "`ALTER TABLE t ADD CONSTRAINT valid_amount CHECK (amount >= 0)`",
                 "`CONSTRAINT valid_amount EXPECT (amount >= 0) ON VIOLATION DROP ROW`"],
     "answer": 3,
     "explanation": "Default EXPECT only records the violation (warn); DROP ROW drops failing rows; FAIL UPDATE stops the update. A Delta CHECK constraint fails the whole write."},
    {"topic": "Gold, SCD & data quality",
     "q": "Which statement about `PRIMARY KEY` and `FOREIGN KEY` constraints on Unity Catalog tables is true?",
     "options": ["They are informational: they document relationships (for tools and the optimizer) but are not enforced",
                 "They reject duplicate keys on every write",
                 "They reject rows whose foreign key has no parent row",
                 "They can only be defined on external tables"],
     "answer": 0,
     "explanation": "Only NOT NULL and CHECK constraints are enforced by Delta. Uniqueness and referential integrity must be checked by your pipeline (e.g. a left anti join)."},
    {"topic": "Gold, SCD & data quality",
     "q": "Which SQL creates a materialized view of revenue per country and later brings it up to date?",
     "options": ["`CREATE TEMP VIEW mv AS SELECT …` then `CACHE TABLE mv`",
                 "`CREATE MATERIALIZED VIEW mv AS SELECT …` then `REFRESH MATERIALIZED VIEW mv` (or a schedule)",
                 "`CREATE VIEW mv AS SELECT …` then `REFRESH TABLE mv`",
                 "`CREATE TABLE mv AS SELECT …` then `OPTIMIZE mv`"],
     "answer": 1,
     "explanation": "CREATE [OR REPLACE] MATERIALIZED VIEW computes the result; REFRESH MATERIALIZED VIEW (or SCHEDULE / TRIGGER ON UPDATE) keeps it current."},
    {"topic": "Gold, SCD & data quality",
     "q": "In `CREATE OR REFRESH STREAMING TABLE bronze AS SELECT * FROM STREAM read_files('/Volumes/…/landing', format => 'json')`, what does the `STREAM` keyword do?",
     "options": ["It makes the query run continuously on a SQL warehouse",
                 "It turns the table into a materialized view",
                 "It reads the source incrementally, so each refresh processes only files not yet processed",
                 "Nothing — it is optional decoration"],
     "answer": 2,
     "explanation": "A streaming table must read a streaming source: STREAM read_files(...) (Auto Loader) or STREAM(table). Without STREAM the query is a batch read."},
]

render_quiz(questions, title="Section 07 · Data Transformation & Modeling", pass_mark=0.8,
            meta="55 questions · cleaning & shaping, combining & aggregating, gold modeling / SCD / data quality · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Cleaning & shaping | `presentation/07-P1 - Cleaning and Shaping Data` + `labs/07-L1` |
# MAGIC | Combining & aggregating | `presentation/07-P2 - Combining and Aggregating Data` + `labs/07-L2` |
# MAGIC | Gold, SCD & data quality | `presentation/07-P3 - Modeling Gold …` + `labs/07-L3` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
