# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 08-Q · Exam Questions — Medallion Architecture & Declarative Pipelines
# MAGIC **51 exam-style questions** on the medallion architecture and multi-hop streaming (08-P1), Lakeflow Spark Declarative
# MAGIC Pipelines (08-P2) and expectations, AUTO CDC and monitoring (08-P3). Multi-answer questions say so. Target **≥ 80 %**
# MAGIC before Section 09.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Medallion & multi-hop ----------------
    {"topic": "Medallion & multi-hop",
     "q": "In a medallion architecture, which layer should keep the data **as it arrived from the source**, so that downstream tables can be rebuilt after a logic change?",
     "options": ["Bronze",
                 "Gold",
                 "Silver",
                 "None — the source system is always the replay point"],
     "answer": 0,
     "explanation": "Bronze is the raw, append-only, replayable copy (plus ingestion metadata). Sources may delete or overwrite data, so you keep your own copy."},
    {"topic": "Medallion & multi-hop",
     "q": "Which task belongs in the **silver** layer?",
     "options": ["Granting analysts access to a BI dashboard",
                 "Casting types, removing duplicates, handling nulls and joining reference data",
                 "Landing raw JSON exactly as received",
                 "Computing monthly revenue per country for a dashboard"],
     "answer": 1,
     "explanation": "Silver = cleaned, conformed, deduplicated and enriched records. Aggregations for a use case are gold; raw landing is bronze."},
    {"topic": "Medallion & multi-hop",
     "q": "Why do bronze tables typically include columns such as `_metadata.file_name` (or `file_path`) and an ingestion timestamp?",
     "options": ["They are needed for Z-ordering",
                 "They replace the need for a checkpoint",
                 "They record where and when each row was ingested — useful for debugging, auditing and reprocessing single files",
                 "They are required by Delta Lake"],
     "answer": 2,
     "explanation": "Ingestion metadata = lineage at row level. It is not required by Delta and does not replace a streaming checkpoint."},
    {"topic": "Medallion & multi-hop",
     "q": "A hand-coded pipeline has three streaming hops (bronze → silver → gold). How many checkpoint locations are needed?",
     "options": ["None if the targets are Delta tables",
                 "Two — one for the source and one for the final sink",
                 "One, shared by all streams of the pipeline",
                 "Three — one per streaming query"],
     "answer": 3,
     "explanation": "Every streaming query needs its own checkpoint; checkpoints must never be shared between streams."},
    {"topic": "Medallion & multi-hop",
     "q": "An engineer converts a Unix timestamp in **seconds** (`order_timestamp`, BIGINT) into a TIMESTAMP in silver. Which expression is correct?",
     "options": ["`from_unixtime(order_timestamp)` (optionally cast to TIMESTAMP)",
                 "`to_date(order_timestamp, 'yyyy-MM-dd')`",
                 "`CAST(order_timestamp AS DATE)`",
                 "`unix_timestamp(order_timestamp)`"],
     "answer": 0,
     "explanation": "from_unixtime converts seconds since the epoch into a timestamp string (cast it, or use timestamp_seconds()). unix_timestamp does the opposite."},
    {"topic": "Medallion & multi-hop",
     "q": "A silver stream joins new orders with a **static Delta table** of customers. A customer's country is updated in the customer table. What happens to silver?",
     "options": ["All existing silver rows of that customer are updated automatically",
                 "Only orders processed **after** the change get the new country; rows already written keep the old value",
                 "The stream fails because the static table changed",
                 "Nothing changes until the stream is restarted with a new checkpoint"],
     "answer": 1,
     "explanation": "In a stream-static join the stream drives processing; each micro-batch joins the latest version of the Delta static side. Existing output rows are never re-joined."},
    {"topic": "Medallion & multi-hop",
     "q": "A stream-static **inner** join enriches orders with customers. Orders from customers that are not yet in the customer table…",
     "options": ["cause the stream to fail",
                 "are written with NULL customer columns",
                 "are silently dropped from the output",
                 "are buffered until the customer arrives"],
     "answer": 2,
     "explanation": "Inner joins keep only matches. Use a left join (stream on the left) to keep them with NULLs and flag or quarantine them."},
    {"topic": "Medallion & multi-hop",
     "q": "A gold stream computes revenue per day and country from silver **without** a watermark and writes to a Delta table. Which output mode works?",
     "options": ["update — directly into the Delta table",
                 "Any mode works for aggregations",
                 "append",
                 "complete"],
     "answer": 3,
     "explanation": "Without a watermark the groups never become final, so append is rejected. Complete rewrites the full aggregate each trigger. The Delta sink supports append and complete (update needs foreachBatch + MERGE)."},
    {"topic": "Medallion & multi-hop",
     "q": "Which gold object stores **no data** and computes its result on every read?",
     "options": ["View",
                 "Streaming table",
                 "Table created with CTAS",
                 "Materialized view"],
     "answer": 0,
     "explanation": "A (standard) view is a saved query. MVs, streaming tables and CTAS tables all store data."},
    # ---------------- SDP concepts & syntax ----------------
    {"topic": "SDP concepts & syntax",
     "q": "Which is the **current** name of the product formerly called Delta Live Tables?",
     "options": ["Delta Engine",
                 "Lakeflow Spark Declarative Pipelines",
                 "Lakeflow Connect",
                 "Lakeflow Jobs"],
     "answer": 1,
     "explanation": "DLT → Lakeflow Declarative Pipelines → Lakeflow Spark Declarative Pipelines (SDP). Lakeflow Connect ingests, Lakeflow Jobs orchestrates."},
    {"topic": "SDP concepts & syntax",
     "q": "What does it mean that pipelines are **declarative**?",
     "options": ["You write the order in which tables are updated",
                 "Pipelines can only be written in SQL",
                 "You define the datasets and their queries; the pipeline derives the dependency graph and manages execution, checkpoints and retries",
                 "Every table is fully recomputed on every run"],
     "answer": 2,
     "explanation": "You state WHAT each dataset contains; SDP works out HOW (order, incremental processing, state, retries)."},
    {"topic": "SDP concepts & syntax",
     "q": "Which dataset type processes each input row **exactly once** and requires an **append-only** source?",
     "options": ["View",
                 "Temporary view",
                 "Materialized view",
                 "Streaming table"],
     "answer": 3,
     "explanation": "Streaming tables are incremental: each row is processed once. Updates/deletes in the source break them unless skipChangeCommits is used."},
    {"topic": "SDP concepts & syntax",
     "q": "A gold aggregate must always reflect the current content of silver, including rows that were **updated or deleted**. Which dataset type fits?",
     "options": ["Materialized view",
                 "Streaming table",
                 "Temporary view",
                 "Streaming table with skipChangeCommits"],
     "answer": 0,
     "explanation": "A materialized view keeps its result correct with respect to its inputs (incremental refresh when possible). skipChangeCommits would IGNORE the changes."},
    {"topic": "SDP concepts & syntax",
     "q": "Which SQL statement incrementally ingests new JSON files from a volume in a pipeline?",
     "options": ["`COPY INTO raw FROM '/Volumes/c/s/v/in' FILEFORMAT = JSON`",
                 "`CREATE OR REFRESH STREAMING TABLE raw AS SELECT * FROM STREAM read_files('/Volumes/c/s/v/in', format => 'json')`",
                 "``CREATE TABLE raw AS SELECT * FROM json.`/Volumes/c/s/v/in` ``",
                 "`CREATE OR REFRESH MATERIALIZED VIEW raw AS SELECT * FROM read_files('/Volumes/c/s/v/in', format => 'json')`"],
     "answer": 1,
     "explanation": "STREAM read_files (Auto Loader) into a streaming table reads only new files on each update. Without STREAM, read_files is a batch read."},
    {"topic": "SDP concepts & syntax",
     "q": "In a pipeline, `orders_silver` must read only the **new** rows of `orders_bronze` (another dataset of the same pipeline). Which FROM clause is correct?",
     "options": ["`FROM LIVE.orders_bronze`",
                 "`FROM orders_bronze`",
                 "`FROM STREAM(orders_bronze)`",
                 "`FROM cloud_files(orders_bronze)`"],
     "answer": 2,
     "explanation": "STREAM(...) reads incrementally. A plain FROM is a batch read (materialized view semantics). LIVE. is the legacy prefix."},
    {"topic": "SDP concepts & syntax",
     "q": "Which Python import is used for pipeline code today?",
     "options": ["`import dlt`",
                 "`import delta.pipelines as dp`",
                 "`from databricks import lakeflow`",
                 "`from pyspark import pipelines as dp`"],
     "answer": 3,
     "explanation": "`from pyspark import pipelines as dp` (aligned with Apache Spark Declarative Pipelines). `import dlt` is legacy but still works."},
    {"topic": "SDP concepts & syntax",
     "q": "A Python function decorated with `@dp.table` returns `spark.read.table('orders_silver').groupBy('country').count()`. What is created?",
     "options": ["A materialized view",
                 "A temporary view",
                 "An error — @dp.table requires a streaming DataFrame",
                 "A streaming table"],
     "answer": 0,
     "explanation": "@dp.table creates a streaming table for a streaming DataFrame and a materialized view for a batch DataFrame. @dp.materialized_view makes the intent explicit."},
    {"topic": "SDP concepts & syntax",
     "q": "Which decorator defines a dataset that is used **inside** the pipeline but is **not published** to Unity Catalog?",
     "options": ["`@dp.append_flow`",
                 "`@dp.temporary_view`",
                 "`@dp.materialized_view`",
                 "`@dp.table`"],
     "answer": 1,
     "explanation": "@dp.temporary_view (legacy @dlt.view) = pipeline-scoped view. SQL: CREATE TEMPORARY VIEW."},
    {"topic": "SDP concepts & syntax",
     "q": "Which code is **not allowed** inside a function that defines a pipeline dataset? **(Choose TWO.)**",
     "options": ["`df.writeStream.toTable('silver')`",
                 "`spark.conf.get('dataset_path')`",
                 "`df.count()` to log the number of rows",
                 "`return spark.readStream.table('bronze').where('qty > 0')`"],
     "answer": [0, 2],
     "explanation": "Dataset functions must only return a DataFrame; actions (collect, count, toPandas) and writes (save, saveAsTable, start, toTable) are not allowed. Reading a configuration value is fine."},
    {"topic": "SDP concepts & syntax",
     "q": "The pipeline **Configuration** contains `dataset_path = /Volumes/main/raw/files`. How do SQL and Python pipeline code read it?",
     "options": ["SQL `:dataset_path` · Python `dbutils.widgets.get('dataset_path')`",
                 "Only Python can read configuration values",
                 "SQL `{{dataset_path}}` · Python `os.environ['dataset_path']`",
                 "SQL `${dataset_path}` · Python `spark.conf.get('dataset_path')`"],
     "answer": 3,
     "explanation": "Configuration keys become Spark conf values: `${key}` substitution in SQL, spark.conf.get in Python. (The newer Beta 'Parameters' use :name markers in SQL only.)"},
    {"topic": "SDP concepts & syntax",
     "q": "In the Lakeflow Pipelines Editor, where does the pipeline look for its source code by default?",
     "options": ["In the `transformations/` folder under the pipeline's root folder",
                 "In every notebook of the user's home folder",
                 "In the `explorations/` folder",
                 "In DBFS under /pipelines"],
     "answer": 0,
     "explanation": "Source files (.sql/.py) live in transformations/ (configurable). explorations/ holds ad-hoc notebooks that are NOT part of the pipeline."},
    {"topic": "SDP concepts & syntax",
     "q": "Two SQL files of a pipeline are named `z_bronze.sql` and `a_gold.sql`; gold reads bronze. In which order are the datasets updated?",
     "options": ["In parallel, so gold may read stale data",
                 "Bronze first, then gold — the order comes from the dependency graph",
                 "In the order the files were created",
                 "Alphabetically: gold first, then bronze — the update fails"],
     "answer": 1,
     "explanation": "File names and statement order don't matter; the pipeline resolves references between datasets into a DAG."},
    {"topic": "SDP concepts & syntax",
     "q": "Which SQL feature is **not supported** in pipeline dataset definitions?",
     "options": ["`JOIN` between a stream and a materialized view",
                 "`CREATE TEMPORARY VIEW`",
                 "`PIVOT`",
                 "`COMMENT` on a table"],
     "answer": 2,
     "explanation": "PIVOT needs eager data loading to compute the output schema, which pipelines don't support."},
    {"topic": "SDP concepts & syntax",
     "q": "A streaming table in a pipeline reads another table as a stream. Someone runs a `DELETE` on the source table. What happens on the next update, and how can it be avoided?",
     "options": ["The pipeline converts the streaming table into a materialized view",
                 "Nothing — deletes are propagated automatically",
                 "The deleted rows are re-inserted",
                 "The flow fails because the source is no longer append-only; use `skipChangeCommits` (changes are ignored), a materialized view, or a full refresh"],
     "answer": 3,
     "explanation": "Streaming reads require append-only sources. skipChangeCommits skips the change commits (they are not propagated)."},
    # ---------------- Settings & updates ----------------
    {"topic": "Settings & updates",
     "q": "A pipeline must process new data **every hour** at the lowest cost. Which pipeline mode and trigger?",
     "options": ["Triggered mode, scheduled hourly (a Lakeflow Job with a pipeline task)",
                 "Continuous mode",
                 "Triggered mode started manually",
                 "Continuous mode with a 1-hour interval"],
     "answer": 0,
     "explanation": "Triggered = process what's available, then stop (compute released). Continuous keeps compute running for low latency."},
    {"topic": "Settings & updates",
     "q": "Which statements describe **development** behaviour of pipeline updates? **(Choose TWO.)**",
     "options": ["Automatic retries on failure",
                 "Compute is reused between updates for faster iteration",
                 "Compute is terminated immediately after every update",
                 "Retries are disabled so errors surface immediately"],
     "answer": [1, 3],
     "explanation": "Development (UI/editor runs): reuse compute, no retries. Production (jobs, API, continuous): automatic retries, restarts on recoverable errors, compute released after the update."},
    {"topic": "Settings & updates",
     "q": "A classic-compute pipeline uses `AUTO CDC` but **no** expectations. What is the minimum product edition?",
     "options": ["Advanced",
                 "Core",
                 "Pro",
                 "Premium"],
     "answer": 2,
     "explanation": "Core = streaming tables & MVs, Pro = + CDC, Advanced = + expectations (data quality). Serverless pipelines include all features."},
    {"topic": "Settings & updates",
     "q": "A classic pipeline on the **Pro** edition adds `CONSTRAINT valid EXPECT (id IS NOT NULL) ON VIOLATION DROP ROW`. What is needed?",
     "options": ["Enable Photon",
                 "Switch the channel to Preview",
                 "Nothing, Pro supports expectations",
                 "Switch to the Advanced edition (or serverless)"],
     "answer": 3,
     "explanation": "Expectations are an Advanced-edition feature on classic compute."},
    {"topic": "Settings & updates",
     "q": "What does the pipeline **channel** setting control?",
     "options": ["The runtime version: Current (default) or Preview to test upcoming changes",
                 "Which catalog the tables are published to",
                 "The Git branch the code is read from",
                 "Where notifications are sent"],
     "answer": 0,
     "explanation": "Channel = pipeline runtime version (current / preview)."},
    {"topic": "Settings & updates",
     "q": "What does a **full refresh** do to a streaming table?",
     "options": ["Only recomputes downstream materialized views",
                 "Truncates the table, clears its checkpoints and reprocesses all data still available in the source",
                 "Validates the code without writing data",
                 "Appends all source data again on top of the existing rows"],
     "answer": 1,
     "explanation": "Full refresh = rebuild from the source. If the source no longer has old data, that data is lost from the table."},
    {"topic": "Settings & updates",
     "q": "A streaming table ingests from Kafka (7-day retention) and holds 2 years of data. How do you make sure nobody accidentally wipes it with a full refresh?",
     "options": ["Use the Preview channel",
                 "Set `delta.appendOnly = false`",
                 "Set `pipelines.reset.allowed = false` in the table properties",
                 "Switch to continuous mode"],
     "answer": 2,
     "explanation": "pipelines.reset.allowed = false blocks full refreshes for that table."},
    {"topic": "Settings & updates",
     "q": "You changed one table's logic and want to check the code and the dependency graph **without writing any data**. Which option?",
     "options": ["Full refresh",
                 "Run file",
                 "Refresh selection",
                 "Dry run (validate)"],
     "answer": 3,
     "explanation": "Dry run resolves datasets, schemas and the graph but does not materialize anything."},
    {"topic": "Settings & updates",
     "q": "Which statements about serverless pipelines are true? **(Choose TWO.)**",
     "options": ["They require Unity Catalog",
                 "Cluster settings are not configurable",
                 "They only support the Core edition",
                 "You choose the worker instance types"],
     "answer": [0, 1],
     "explanation": "Serverless pipelines need UC and remove compute configuration (standard vs performance-optimized mode instead). All features (CDC, expectations) are available."},
    {"topic": "Settings & updates",
     "q": "In a UC pipeline with default catalog `main` and default schema `sales`, the code defines `CREATE OR REFRESH MATERIALIZED VIEW daily_revenue …`. Where is it published?",
     "options": ["It is not published — only temporary views are",
                 "`main.sales.daily_revenue`",
                 "`main.default.daily_revenue`",
                 "`hive_metastore.sales.daily_revenue`"],
     "answer": 1,
     "explanation": "Unqualified names go to the pipeline's default catalog and schema. Fully qualified names can write elsewhere."},
    # ---------------- Expectations ----------------
    {"topic": "Expectations",
     "q": "Rows with a NULL `email` must be **kept**, but the team wants to know how many there are. Which definition?",
     "options": ["`CONSTRAINT has_email EXPECT (email IS NOT NULL) ON VIOLATION FAIL UPDATE`",
                 "`CONSTRAINT has_email EXPECT (email IS NOT NULL) ON VIOLATION DROP ROW`",
                 "`CONSTRAINT has_email EXPECT (email IS NOT NULL)`",
                 "`CONSTRAINT has_email CHECK (email IS NOT NULL)`"],
     "answer": 2,
     "explanation": "Without ON VIOLATION the expectation only warns: the row is written and counted in the metrics."},
    {"topic": "Expectations",
     "q": "What happens when a record violates an expectation defined with `ON VIOLATION FAIL UPDATE`?",
     "options": ["The record is dropped and counted",
                 "The record is written to a quarantine table",
                 "A warning is logged and processing continues",
                 "The update fails and the flow's transaction is rolled back; manual intervention is needed"],
     "answer": 3,
     "explanation": "Fail = stop. The target is not partially written; fix the data or the rule and run again."},
    {"topic": "Expectations",
     "q": "Which Python decorator drops invalid rows for **several** rules defined in a dictionary?",
     "options": ["`@dp.expect_all_or_drop(rules)`",
                 "`@dp.expect_all(rules, action='drop')`",
                 "`@dp.expect_or_drop(rules)`",
                 "`@dp.drop_invalid(rules)`"],
     "answer": 0,
     "explanation": "expect_all / expect_all_or_drop / expect_all_or_fail take a dict of name → condition."},
    {"topic": "Expectations",
     "q": "Where can you see how many records each expectation dropped? **(Choose TWO.)**",
     "options": ["The pipeline's Data quality tab for the table",
                 "The pipeline event log (`flow_progress` events)",
                 "The Spark UI of the SQL warehouse",
                 "`DESCRIBE HISTORY` of the table"],
     "answer": [0, 1],
     "explanation": "Data quality metrics are shown in the UI and stored in the event log under details:flow_progress.data_quality.expectations."},
    {"topic": "Expectations",
     "q": "Invalid rows must not reach silver, but the data team wants to **inspect** them later. Which design?",
     "options": ["A Delta CHECK constraint on silver",
                 "An expectation with ON VIOLATION FAIL UPDATE",
                 "Drop them in silver with the rules, and write the **inverted** rules into a separate quarantine table",
                 "A warn expectation on silver only"],
     "answer": 2,
     "explanation": "The quarantine pattern: valid table with DROP expectations + a quarantine table with the inverse condition (or a flag column)."},
    {"topic": "Expectations",
     "q": "Which datasets support expectations?",
     "options": ["Only streaming tables",
                 "Only materialized views",
                 "Only tables outside pipelines",
                 "Streaming tables, materialized views and temporary views"],
     "answer": 3,
     "explanation": "All three pipeline dataset types (and standalone MVs/STs in Databricks SQL). Not supported with AUTO CDC FROM SNAPSHOT."},
    {"topic": "Expectations",
     "q": "What is the key difference between a pipeline **expectation** and a Delta **CHECK constraint**?",
     "options": ["A CHECK constraint makes the whole write fail; an expectation lets you choose warn, drop or fail and records metrics",
                 "Expectations are enforced only on read",
                 "CHECK constraints can drop invalid rows",
                 "There is none"],
     "answer": 0,
     "explanation": "CHECK = all-or-nothing enforcement on a Delta table. Expectations = flexible actions + data-quality metrics in pipelines."},
    # ---------------- AUTO CDC ----------------
    {"topic": "AUTO CDC",
     "q": "Which clause makes sure an **older** change that arrives late never overwrites a newer one in the target?",
     "options": ["`COLUMNS * EXCEPT`",
                 "`SEQUENCE BY`",
                 "`APPLY AS DELETE WHEN`",
                 "`KEYS`"],
     "answer": 1,
     "explanation": "SEQUENCE BY defines the logical order of changes per key (sortable, not NULL)."},
    {"topic": "AUTO CDC",
     "q": "The target of an AUTO CDC flow must be…",
     "options": ["a materialized view",
                 "a temporary view",
                 "a streaming table created beforehand (`CREATE OR REFRESH STREAMING TABLE t` / `dp.create_streaming_table`)",
                 "any Delta table outside the pipeline"],
     "answer": 2,
     "explanation": "Create the target streaming table first, then the flow: CREATE FLOW … AS AUTO CDC INTO t / dp.create_auto_cdc_flow(target='t', …)."},
    {"topic": "AUTO CDC",
     "q": "An SCD type 2 target produced by AUTO CDC contains which extra columns?",
     "options": ["`valid_from`, `valid_to`, `is_current`",
                 "`_commit_version` and `_commit_timestamp`",
                 "`_start_date` and `_end_date`",
                 "`__START_AT` and `__END_AT`"],
     "answer": 3,
     "explanation": "__START_AT / __END_AT (type of the SEQUENCE BY column); __END_AT NULL = current version. _commit_version belongs to Change Data Feed."},
    {"topic": "AUTO CDC",
     "q": "A CDC event with `operation = 'DELETE'` is applied to an SCD type **2** target. What happens?",
     "options": ["The current version is closed (its `__END_AT` is set); history is kept",
                 "All versions of the key are deleted",
                 "A new version with NULL values is inserted",
                 "Nothing — SCD2 ignores deletes"],
     "answer": 0,
     "explanation": "SCD1 removes the row; SCD2 closes the current version and keeps the history."},
    {"topic": "AUTO CDC",
     "q": "Which clause is supported for SCD type **1** only?",
     "options": ["`KEYS`",
                 "`APPLY AS TRUNCATE WHEN`",
                 "`SEQUENCE BY`",
                 "`APPLY AS DELETE WHEN`"],
     "answer": 1,
     "explanation": "Truncate events (empty the table) are only supported for SCD type 1."},
    {"topic": "AUTO CDC",
     "q": "Legacy code uses `APPLY CHANGES INTO LIVE.customers FROM STREAM(LIVE.cdc) …`. What is the current equivalent?",
     "options": ["`MERGE INTO customers USING cdc …`",
                 "`CREATE MATERIALIZED VIEW customers AS SELECT * FROM cdc`",
                 "`AUTO CDC INTO customers FROM STREAM(cdc) …` (e.g. inside `CREATE FLOW … AS`)",
                 "`COPY INTO customers FROM cdc`"],
     "answer": 2,
     "explanation": "AUTO CDC replaced APPLY CHANGES with the same syntax; the LIVE. prefix is no longer needed."},
    # ---------------- Monitoring & event log ----------------
    {"topic": "Monitoring & event log",
     "q": "Which query reads the event log of the pipeline that manages the table `main.sales.orders_silver`?",
     "options": ["`SHOW EVENTS FOR main.sales.orders_silver`",
                 "`SELECT * FROM system.access.audit WHERE table = 'orders_silver'`",
                 "`DESCRIBE HISTORY main.sales.orders_silver`",
                 "`SELECT * FROM event_log(TABLE(main.sales.orders_silver))`"],
     "answer": 3,
     "explanation": "event_log(TABLE(t)) or event_log('<pipeline-id>'); only the owner of the pipeline's tables may call it. Optionally publish the event log to a UC table."},
    {"topic": "Monitoring & event log",
     "q": "Which `event_type` contains the **data-quality metrics** and rows written per flow?",
     "options": ["`flow_progress`",
                 "`flow_definition`",
                 "`cluster_resources`",
                 "`user_action`"],
     "answer": 0,
     "explanation": "flow_progress: status, metrics (num_output_rows, backlog) and data_quality.expectations. flow_definition holds lineage; user_action is audit."},
    {"topic": "Monitoring & event log",
     "q": "An auditor asks who **started and edited** a pipeline last week. Which event type?",
     "options": ["`update_progress`",
                 "`user_action`",
                 "`planning_information`",
                 "`flow_progress`"],
     "answer": 1,
     "explanation": "user_action events record actions (create, edit, start, stop) with the user name."},
    {"topic": "Monitoring & event log",
     "q": "A scheduled pipeline update failed during the night. What is the **first** thing to look at?",
     "options": ["Delete the checkpoints and run a full refresh",
                 "Switch the pipeline to continuous mode",
                 "The failed update in the pipeline UI (graph + ERROR events / event log messages) to find the failing flow and the cause",
                 "Recreate the pipeline"],
     "answer": 2,
     "explanation": "Diagnose first: the update details show which flow failed and why (expectation, schema change, non-append source…). Then fix and refresh (selectively if needed)."},
]

render_quiz(questions, title="Section 08 · Medallion Architecture & Declarative Pipelines", pass_mark=0.8,
            meta="51 questions · medallion & multi-hop, SDP concepts & syntax, settings & updates, expectations, AUTO CDC, monitoring · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Medallion & multi-hop | `presentation/08-P1 - Medallion Architecture and Multi-hop Streaming` + `labs/08-L1` |
# MAGIC | SDP concepts & syntax · Settings & updates | `presentation/08-P2 - Lakeflow Spark Declarative Pipelines` + `labs/08-L2` |
# MAGIC | Expectations · AUTO CDC · Monitoring & event log | `presentation/08-P3 - Expectations, AUTO CDC and Pipeline Monitoring` + `labs/08-L3`, `08-L4` |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
