# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 04-Q · Exam Questions — Unity Catalog & Data Objects
# MAGIC **32 exam-style questions** on Unity Catalog architecture and names (04-P1), managed vs external tables (04-P2) and
# MAGIC views, volumes & functions (04-P3). Some questions have **more than one** correct answer — they say so.
# MAGIC Target **≥ 80 %** before Section 05.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
questions = [
    # ---------------- Architecture & namespace ----------------
    {"topic": "Architecture & namespace",
     "q": "What is the correct Unity Catalog object hierarchy, from top to bottom?",
     "options": ["Metastore → catalog → schema → table/view/volume/function",
                 "Catalog → metastore → schema → table",
                 "Workspace → catalog → schema → table",
                 "Metastore → schema → catalog → table"],
     "answer": 0,
     "explanation": "The metastore is the top-level container; catalogs are the first level of the three-level namespace, schemas the second, and data/AI objects the third."},
    {"topic": "Architecture & namespace",
     "q": "A company has three workspaces in the same cloud region. How many Unity Catalog metastores do they typically use?",
     "options": ["None — Unity Catalog doesn't use a metastore",
                 "One — a single metastore per region shared by the workspaces",
                 "One per catalog",
                 "Three — one per workspace"],
     "answer": 1,
     "explanation": "Unity Catalog has one metastore per region; every workspace in that region is attached to it, so data and permissions are defined once and enforced everywhere."},
    {"topic": "Architecture & namespace",
     "q": "Which advantage does Unity Catalog have over the legacy per-workspace Hive metastore?",
     "options": ["It stores data in a proprietary format",
                 "It removes the need for compute",
                 "Access control, auditing and lineage are defined centrally and apply across all attached workspaces",
                 "Tables no longer need a schema"],
     "answer": 2,
     "explanation": "Centralized governance (define once, secure everywhere) with built-in auditing, lineage and discovery is the core benefit. The Hive metastore was per workspace with separate table ACLs."},
    {"topic": "Architecture & namespace",
     "q": "After `USE CATALOG dev;` and `USE SCHEMA hr;`, which table does `SELECT * FROM sales.orders` read?",
     "options": ["sales.orders in hive_metastore",
                 "hr.sales.orders",
                 "dev.hr.orders",
                 "dev.sales.orders"],
     "answer": 3,
     "explanation": "A two-part name is schema.object and resolves in the current catalog. The current schema only matters for one-part names."},
    {"topic": "Architecture & namespace",
     "q": "Which **two** statements set or show the current context?",
     "options": ["`DESCRIBE CONTEXT`",
                 "`ALTER SESSION SET CATALOG dev`",
                 "`SELECT current_catalog(), current_schema()`",
                 "`USE CATALOG dev`"],
     "answer": [2, 3],
     "explanation": "`USE CATALOG` / `USE SCHEMA` change the current catalog/schema for the session; `current_catalog()` and `current_schema()` return them. `DESCRIBE CONTEXT` and `ALTER SESSION` are not Databricks SQL commands."},
    {"topic": "Architecture & namespace",
     "q": "Which objects live **inside a schema** in Unity Catalog? (choose **three**)",
     "options": ["Storage credentials",
                 "Functions",
                 "External locations",
                 "Views",
                 "Volumes"],
     "answer": [1, 3, 4],
     "explanation": "Tables, views, volumes, functions and models live in schemas. Storage credentials, external locations, connections and shares are metastore-level securables."},
    {"topic": "Architecture & namespace",
     "q": "What is an **external location** in Unity Catalog?",
     "options": ["A workspace in another region",
                 "A DBFS mount point",
                 "A cloud storage path combined with the storage credential that can access it",
                 "A table stored outside Databricks"],
     "answer": 2,
     "explanation": "External location = path + storage credential. It governs access to that path and is required to create external tables/volumes and managed locations."},
    {"topic": "Architecture & namespace",
     "q": "A data engineer wants a list of every table in catalog `prod`, with its type and owner, using SQL. What should they query?",
     "options": ["`DESCRIBE CATALOG prod`",
                 "`SHOW CATALOGS`",
                 "`dbutils.fs.ls('/Volumes/prod')`",
                 "`prod.information_schema.tables`"],
     "answer": 3,
     "explanation": "Every catalog has a read-only information_schema; `tables` has one row per table/view with `table_type`, `table_owner`, `data_source_format` and more (`system.information_schema` spans all catalogs)."},
    {"topic": "Architecture & namespace",
     "q": "`CREATE DATABASE sales` is run in a Unity Catalog workspace. What does it create?",
     "options": ["A schema named `sales` in the current catalog",
                 "A new catalog",
                 "A new metastore",
                 "An error: DATABASE is not supported"],
     "answer": 0,
     "explanation": "DATABASE and SCHEMA are synonyms. It creates the schema `sales` in the current catalog."},
    # ---------------- Managed vs external ----------------
    {"topic": "Managed vs external",
     "q": "Which statement creates an **external** table?",
     "options": ["`CREATE SCHEMA prod.s MANAGED LOCATION 's3://acme/s'`",
                 "`CREATE TABLE prod.s.t (id INT) LOCATION 's3://acme/tables/t'`",
                 "`CREATE TABLE prod.s.t AS SELECT * FROM src`",
                 "`CREATE TABLE prod.s.t (id INT)`"],
     "answer": 1,
     "explanation": "A table-level LOCATION (inside an external location) makes the table external. A schema's MANAGED LOCATION only changes where managed tables are stored."},
    {"topic": "Managed vs external",
     "q": "A data engineer runs `DROP TABLE orders` and later notices the underlying data files were deleted as well. What kind of table was it?",
     "options": ["External table",
                 "Temporary view",
                 "Managed table",
                 "Any Delta table - DROP always deletes files"],
     "answer": 2,
     "explanation": "Dropping a managed table removes the data too (Unity Catalog purges the files after the recovery period). Dropping an external table leaves the files in place."},
    {"topic": "Managed vs external",
     "q": "Schema `prod.hr` was created with `MANAGED LOCATION 's3://hr-bucket/uc'`, catalog `prod` with `MANAGED LOCATION 's3://prod/uc'`. Where are the files of a new managed table `prod.hr.salaries` stored?",
     "options": ["The metastore root",
                 "It fails: managed tables need a LOCATION",
                 "s3://prod/uc",
                 "s3://hr-bucket/uc (under generated sub-folders)"],
     "answer": 3,
     "explanation": "The most specific managed location wins: schema, then catalog, then metastore (then default storage)."},
    {"topic": "Managed vs external",
     "q": "Which **two** are reasons Databricks recommends **managed** tables?",
     "options": ["Predictive optimization can maintain them automatically",
                 "Unity Catalog manages the file lifecycle and cleans up files after drops",
                 "Other engines can write to their files directly by path",
                 "They support any file format including CSV"],
     "answer": [0, 1],
     "explanation": "Managed tables get automatic maintenance, performance features and lifecycle management. Direct path access and CSV/JSON formats are external-table use cases."},
    {"topic": "Managed vs external",
     "q": "A managed table was dropped by mistake yesterday. What is the quickest way to recover it with its data?",
     "options": ["Re-run `CREATE TABLE t`",
                 "`UNDROP TABLE t`",
                 "It cannot be recovered",
                 "`RESTORE TABLE t TO VERSION AS OF 0`"],
     "answer": 1,
     "explanation": "UNDROP TABLE recovers dropped Unity Catalog tables within the recovery period (7 days by default). RESTORE works on an existing table's history, not on a dropped table."},
    {"topic": "Managed vs external",
     "q": "What happens when you run `DROP SCHEMA prod.staging` and the schema still contains tables?",
     "options": ["The tables are moved to the default schema",
                 "The schema and its tables are dropped",
                 "The statement fails because the default is RESTRICT",
                 "Only empty tables are dropped"],
     "answer": 2,
     "explanation": "DROP SCHEMA defaults to RESTRICT and fails on a non-empty schema. Add CASCADE to drop everything in it."},
    {"topic": "Managed vs external",
     "q": "Which privilege on an external location lets a user register external tables under its path?",
     "options": ["`CREATE MANAGED STORAGE`",
                 "`MODIFY`",
                 "`READ FILES`",
                 "`CREATE EXTERNAL TABLE`"],
     "answer": 3,
     "explanation": "CREATE EXTERNAL TABLE on the external location (plus USE CATALOG, USE SCHEMA and CREATE TABLE on the target schema). READ/WRITE FILES allow path-based file access; CREATE MANAGED STORAGE allows using the path as a managed location."},
    {"topic": "Managed vs external",
     "q": "How can you check whether table `t` is managed or external?",
     "options": ["`DESCRIBE EXTENDED t` and read the Type row",
                 "`OPTIMIZE t`",
                 "`SELECT * FROM t LIMIT 1`",
                 "`SHOW CATALOGS`"],
     "answer": 0,
     "explanation": "DESCRIBE EXTENDED shows Type: MANAGED or EXTERNAL (also in information_schema.tables.table_type and Catalog Explorer ▸ Details)."},
    {"topic": "Managed vs external",
     "q": "Which formats can a Unity Catalog **managed** table use?",
     "options": ["Any format, including CSV and JSON",
                 "Delta Lake and Apache Iceberg",
                 "Delta Lake and ORC",
                 "Parquet only"],
     "answer": 1,
     "explanation": "Managed tables are Delta (default) or Iceberg. External tables also support CSV, JSON, Avro, Parquet, ORC and text."},
    # ---------------- Views ----------------
    {"topic": "Views",
     "q": "A temporary view is created in notebook A. Where can it be queried?",
     "options": ["In any job that references notebook A",
                 "In any notebook on the same cluster",
                 "Only in notebook A's Spark session",
                 "In any notebook of the workspace"],
     "answer": 2,
     "explanation": "Temp views belong to one Spark session. Other notebooks have their own sessions, even on the same cluster."},
    {"topic": "Views",
     "q": "Which **two** events make an existing temporary view unavailable?",
     "options": ["Running a `%sql` cell after a Python cell",
                 "Restarting the cluster",
                 "Detaching and re-attaching the notebook to compute",
                 "Running another cell in the same notebook"],
     "answer": [1, 2],
     "explanation": "Detach/re-attach and a compute restart start a new Spark session, which loses all temp views. Mixing languages in one notebook keeps the same session."},
    {"topic": "Views",
     "q": "A notebook calls `dbutils.notebook.run('./child', 600)`. The caller created temp view `tv_sales` before the call. Can the child query `tv_sales`?",
     "options": ["No — the child runs separately with its own session",
                 "Yes — notebook.run shares the caller's variables and views",
                 "Only if the view is referenced as global_temp.tv_sales",
                 "Only on serverless compute"],
     "answer": 0,
     "explanation": "dbutils.notebook.run starts a separate run with its own Spark session. `%run` would execute the other notebook inside the caller's session instead."},
    {"topic": "Views",
     "q": "Where is a **global temporary view** registered and how do you query it?",
     "options": ["In the current schema, as `v`",
                 "In the system-preserved schema `global_temp`, as `global_temp.v`",
                 "In the `system` catalog",
                 "In Unity Catalog, as `catalog.schema.v`"],
     "answer": 1,
     "explanation": "Global temp views live in `global_temp` and are shared by notebooks on the same classic cluster until it restarts. They are a legacy feature and not supported on serverless compute."},
    {"topic": "Views",
     "q": "A dashboard runs an expensive aggregation over a large table many times a day; results may be up to one hour old. Which object fits best?",
     "options": ["A stored view",
                 "A temporary view",
                 "A materialized view refreshed on a schedule",
                 "A global temp view"],
     "answer": 2,
     "explanation": "A materialized view stores the precomputed result and refreshes it (often incrementally) on demand, on a schedule or when sources change. A stored view re-runs the aggregation on every query."},
    {"topic": "Views",
     "q": "An analyst has `SELECT` on view `gold.v_sales` (and USE CATALOG/USE SCHEMA) but no privilege on the underlying table `silver.sales`. What happens when they query the view?",
     "options": ["It returns only the columns they have access to",
                 "The query fails because they need SELECT on silver.sales",
                 "It returns zero rows",
                 "It works — the view owner's privileges on the underlying table are used"],
     "answer": 3,
     "explanation": "Unity Catalog checks the view owner's permissions on the objects a view references, so views can expose a subset of data without granting access to the base tables."},
    {"topic": "Views",
     "q": "A row is inserted into table `silver.customers`. View `gold.v_customers` selects from that table. When does the view show the new row?",
     "options": ["Immediately on the next query — a view stores only its query",
                 "After the next scheduled refresh",
                 "Never, until the view is re-created",
                 "After `REFRESH VIEW gold.v_customers`"],
     "answer": 0,
     "explanation": "A (non-materialized) view has no data of its own; its query runs against the current table data every time."},
    {"topic": "Views",
     "q": "Which command lists the views in the current schema, showing which ones are temporary?",
     "options": ["`SHOW CATALOGS`",
                 "`SHOW VIEWS`",
                 "`DESCRIBE SCHEMA`",
                 "`LIST VIEWS`"],
     "answer": 1,
     "explanation": "SHOW VIEWS returns namespace, viewName and isTemporary (SHOW TABLES also lists views with isTemporary)."},
    # ---------------- Volumes & functions ----------------
    {"topic": "Volumes & functions",
     "q": "What is the file path of file `a.csv` in volume `landing` of schema `sales` in catalog `prod`?",
     "options": ["`/prod/sales/landing/a.csv`",
                 "`s3://prod.sales.landing/a.csv`",
                 "`/Volumes/prod/sales/landing/a.csv`",
                 "`dbfs:/mnt/prod/sales/landing/a.csv`"],
     "answer": 2,
     "explanation": "Volume paths follow /Volumes/<catalog>/<schema>/<volume>/<path>."},
    {"topic": "Volumes & functions",
     "q": "Which **two** statements about volumes are true?",
     "options": ["Volumes store non-tabular files of any format and are governed by Unity Catalog",
                 "Access is controlled with READ VOLUME and WRITE VOLUME privileges",
                 "You can register a Delta table whose location is inside a volume",
                 "Volumes are only available on classic compute"],
     "answer": [0, 1],
     "explanation": "Volumes hold files (CSV, JSON, images, PDFs, libraries…) with READ/WRITE VOLUME privileges. Tables can't be registered on volume paths, and volumes work on serverless."},
    {"topic": "Volumes & functions",
     "q": "Your team used DBFS mounts (`dbfs:/mnt/raw`) for landing files. What is the Unity Catalog replacement?",
     "options": ["Volumes (managed or external)",
                 "Global temp views",
                 "Materialized views",
                 "The hive_metastore catalog"],
     "answer": 0,
     "explanation": "Volumes replace DBFS mounts and the DBFS root for files, with Unity Catalog governance."},
    {"topic": "Volumes & functions",
     "q": "Which statement creates a SQL user-defined function stored in Unity Catalog?",
     "options": ["`DEFINE FUNCTION to_eur(usd) = usd * 0.92`",
                 "`CREATE FUNCTION prod.fx.to_eur(usd DOUBLE) RETURNS DOUBLE RETURN usd * 0.92`",
                 "`CREATE VIEW to_eur AS SELECT usd * 0.92`",
                 "`spark.udf.register('to_eur', lambda usd: usd * 0.92)`"],
     "answer": 1,
     "explanation": "CREATE FUNCTION … RETURNS … RETURN creates a permanent SQL UDF in a schema. spark.udf.register creates a session-scoped function that isn't stored in Unity Catalog."},
    {"topic": "Volumes & functions",
     "q": "Which command shows a UDF's parameters, return type, body and owner?",
     "options": ["`EXPLAIN prod.fx.to_eur`",
                 "`SHOW FUNCTIONS`",
                 "`DESCRIBE FUNCTION EXTENDED prod.fx.to_eur`",
                 "`DESCRIBE DETAIL prod.fx.to_eur`"],
     "answer": 2,
     "explanation": "DESCRIBE FUNCTION EXTENDED shows the full definition. SHOW FUNCTIONS (or SHOW USER FUNCTIONS) only lists names; DESCRIBE DETAIL is for Delta tables."},
    # ---------------- Legacy Hive metastore ----------------
    {"topic": "Legacy Hive metastore",
     "q": "In a legacy Hive metastore, `CREATE SCHEMA db` then `CREATE TABLE db.orders (id INT)`. Where are the files of `orders` stored by default?",
     "options": ["`dbfs:/mnt/db/orders`",
                 "`/Volumes/db/orders`",
                 "`dbfs:/FileStore/db/orders`",
                 "`dbfs:/user/hive/warehouse/db.db/orders`"],
     "answer": 3,
     "explanation": "Hive-metastore managed tables go to dbfs:/user/hive/warehouse/<db>.db/<table> (tables in `default` go directly under /user/hive/warehouse)."},
]

render_quiz(questions, title="Section 04 · Unity Catalog & Data Objects", pass_mark=0.8,
            meta="32 questions · UC architecture & names, managed vs external, views, volumes & functions, legacy Hive · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Architecture & namespace | `presentation/04-P1 - Unity Catalog Architecture and Namespace` + `labs/04-L1` Parts 1–7 |
# MAGIC | Managed vs external | `presentation/04-P2 - Managed vs External Tables and Storage` + `labs/04-L1` Parts 8–10 |
# MAGIC | Views | `presentation/04-P3 - Views, Volumes and Functions` §1–3 + `labs/04-L2` Parts 1–5 |
# MAGIC | Volumes & functions | `presentation/04-P3` §4–5 + `labs/04-L2` Parts 6–7 |
# MAGIC | Legacy Hive metastore | `04-P1` §7 and `04-P2` §7 |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
