# Databricks notebook source
# MAGIC %md
# MAGIC # 📝 05-Q · Exam Questions — Data Ingestion & Loading
# MAGIC **37 exam-style questions** on ingestion patterns & Lakeflow Connect (05-P1), querying files & `read_files` (05-P2) and
# MAGIC `COPY INTO`, semi-structured and other sources (05-P3). Multi-answer questions say so. Target **≥ 80 %** before Section 06.

# COMMAND ----------

# MAGIC %run ../../Includes/_quiz

# COMMAND ----------

# DBTITLE 1,Question bank (collapse this cell - it contains the answers)
# legacy-demo: input_file_name() is only mentioned in question text
questions = [
    # ---------------- Patterns & connectors ----------------
    {"topic": "Patterns & connectors",
     "q": "Each night a job reloads **all** files of a sales export into a table, although only a few files are new. Which pattern is this, and what is its main drawback?",
     "options": ["Batch (full load) — cost and runtime grow with the total data size",
                 "Incremental batch — duplicates",
                 "Streaming — high latency",
                 "Change data capture — needs a gateway"],
     "answer": 0,
     "explanation": "A full load re-reads everything each run. Incremental batch processes only data that is new since the last run."},
    {"topic": "Patterns & connectors",
     "q": "Which statement best describes **incremental batch** ingestion?",
     "options": ["Data is queried in place without being copied",
                 "Each triggered run processes only data that arrived since the previous run",
                 "Each run truncates the table and reloads everything",
                 "Data is processed continuously with sub-second latency"],
     "answer": 1,
     "explanation": "Incremental batch = triggered runs that pick up only new data (e.g. COPY INTO, Auto Loader with availableNow, managed connectors on a schedule)."},
    {"topic": "Patterns & connectors",
     "q": "The sales team needs Salesforce objects in Unity Catalog every day with the **least code and maintenance**, including handling API limits and schema changes. What should the data engineer use?",
     "options": ["A notebook using the Salesforce REST API",
                 "COPY INTO from the Salesforce URL",
                 "A Lakeflow Connect managed connector for Salesforce",
                 "Lakehouse Federation"],
     "answer": 2,
     "explanation": "Managed connectors handle authentication, incremental reads, API limits, retries and schema evolution. COPY INTO reads files, not APIs; federation queries databases in place."},
    {"topic": "Patterns & connectors",
     "q": "In the standard architecture, which component is used by Lakeflow Connect **database** connectors (e.g. SQL Server) but **not** by SaaS connectors?",
     "options": ["A Unity Catalog connection",
                 "Streaming tables as the destination",
                 "A serverless ingestion pipeline",
                 "An ingestion gateway that captures snapshots and change data"],
     "answer": 3,
     "explanation": "Database connectors run an ingestion gateway that continuously extracts snapshots and CDC changes into staging; SaaS connectors call the app's API directly from the ingestion pipeline."},
    {"topic": "Patterns & connectors",
     "q": "In which Unity Catalog object does a Lakeflow Connect managed connector keep the credentials for the source system?",
     "options": ["A connection",
                 "An external location",
                 "A storage credential",
                 "A secret scope only"],
     "answer": 0,
     "explanation": "A UC connection stores the source credentials (CREATE CONNECTION / USE CONNECTION privileges). Storage credentials and external locations are for cloud storage."},
    {"topic": "Patterns & connectors",
     "q": "Which **two** belong to Lakeflow Connect **standard** connectors?",
     "options": ["Auto Loader for cloud object storage",
                 "The Salesforce connector",
                 "Apache Kafka via Structured Streaming",
                 "The Workday connector"],
     "answer": [0, 2],
     "explanation": "Standard connectors give more customization: Auto Loader (cloud storage), message buses such as Kafka/Kinesis/Pub/Sub, SFTP. Salesforce and Workday are managed connectors."},
    {"topic": "Patterns & connectors",
     "q": "An analyst wants to turn a 30 MB CSV file on her laptop into a Unity Catalog table, without code. What is the fastest way?",
     "options": ["Create an Auto Loader stream",
                 "Configure a managed connector",
                 "New ▸ Add or upload data ▸ Create or modify a table",
                 "Run COPY INTO against her laptop's path"],
     "answer": 2,
     "explanation": "The file upload UI creates a managed Delta table from CSV/TSV/JSON/Avro/Parquet/text files (up to 10 files, 2 GB)."},
    {"topic": "Patterns & connectors",
     "q": "A team must pull data from an internal REST API that no connector supports, daily. Which approach follows Databricks best practice?",
     "options": ["Hard-code the API token in the notebook and write straight into a gold table",
                 "Auto Loader pointed at the API URL",
                 "A Partner Connect integration is always required",
                 "A notebook that reads the token with dbutils.secrets, lands the raw responses in a volume, loads them with an idempotent load (e.g. COPY INTO), scheduled by a Lakeflow Job"],
     "answer": 3,
     "explanation": "Custom sources: extract in a notebook, land raw data in cloud storage/volumes, load idempotently into UC tables, orchestrate with Lakeflow Jobs; keep credentials in secrets."},
    {"topic": "Patterns & connectors",
     "q": "A notebook on **serverless** compute fails with `spark.read.format('jdbc')` using a JDBC URL and driver class. What is the recommended alternative to read the PostgreSQL database?",
     "options": ["Use a Unity Catalog connection (Lakehouse Federation / query-based or database connector)",
                 "Use COPY INTO with FILEFORMAT = JDBC",
                 "Install the PostgreSQL JAR in the notebook",
                 "Use input_file_name()"],
     "answer": 0,
     "explanation": "The URL-and-driver style jdbc source is not supported on serverless (nor are custom JARs in notebooks). Use a Unity Catalog connection: a JDBC connection, Lakehouse Federation, or a Lakeflow Connect connector."},
    {"topic": "Patterns & connectors",
     "q": "A company wants to analyse a live operational MySQL database from Databricks **without copying** the data. What fits?",
     "options": ["COPY INTO",
                 "Lakehouse Federation (foreign catalog)",
                 "Auto Loader",
                 "File upload"],
     "answer": 1,
     "explanation": "Lakehouse Federation exposes an external database as a foreign catalog in Unity Catalog and runs queries against it in place."},
    {"topic": "Patterns & connectors",
     "q": "A SQL Server managed connector must keep the **full history** of changes to the `customers` table (old and new versions of each row). Which setting is required?",
     "options": ["SCD type 1",
                 "COPY_OPTIONS force",
                 "SCD type 2",
                 "A continuous ingestion gateway is enough by itself"],
     "answer": 2,
     "explanation": "Managed connectors can apply changes as SCD type 1 (overwrite, default) or SCD type 2 (keep history with start/end markers). The gateway captures changes; the SCD setting decides how they are stored."},
    # ---------------- Querying files ----------------
    {"topic": "Querying files",
     "q": "Which query reads **all JSON files** in the folder `/Volumes/main/raw/files/customers` as one table?",
     "options": ["`READ JSON FROM /Volumes/main/raw/files/customers`",
                 "`SELECT * FROM '/Volumes/main/raw/files/customers'.json`",
                 "`SELECT * FROM json.'/Volumes/main/raw/files/customers'`",
                 "``SELECT * FROM json.`/Volumes/main/raw/files/customers` ``"],
     "answer": 3,
     "explanation": "Direct file queries use ``format.`path` `` with backticks; a directory path reads all its files."},
    {"topic": "Querying files",
     "q": "A `;`-delimited CSV with a header is queried with ``SELECT * FROM csv.`/path` ``. What is the result?",
     "options": ["One column `_c0` containing whole lines, and the header line appears as a data row",
                 "Only the header row",
                 "Correct columns and types",
                 "An error: CSV can't be queried directly"],
     "answer": 0,
     "explanation": "Direct queries use default options (comma delimiter, no header). CSV isn't self-describing, so options are needed — use read_files or a reader."},
    {"topic": "Querying files",
     "q": "Which **two** formats are **self-describing** (column names and types stored with the data)?",
     "options": ["Avro",
                 "CSV",
                 "Plain text",
                 "Parquet"],
     "answer": [0, 3],
     "explanation": "Parquet, Avro, ORC and Delta store their schema. JSON carries names but types are inferred. CSV/text need options."},
    {"topic": "Querying files",
     "q": "Which `read_files` option keeps the inferred schema but forces `amount` to DOUBLE?",
     "options": ["`inferColumnTypes => false`",
                 "`schema => 'amount DOUBLE'`",
                 "`schemaHints => 'amount DOUBLE'`",
                 "`mergeSchema => true`"],
     "answer": 2,
     "explanation": "schemaHints overrides chosen columns while inferring the rest. schema would require the full schema."},
    {"topic": "Querying files",
     "q": "With `read_files` and schema hints, a value `n/a` in a DOUBLE column… ",
     "options": ["is converted to 0",
                 "fails the whole query",
                 "drops the row silently",
                 "becomes NULL and the original value is stored in `_rescued_data`"],
     "answer": 3,
     "explanation": "The rescued data column (default `_rescued_data`) collects values that don't match the schema, as JSON, so no data is lost."},
    {"topic": "Querying files",
     "q": "A notebook uses `input_file_name()` to record the source file and now fails on a Unity Catalog serverless workspace. What is the replacement?",
     "options": ["`_metadata.file_path`",
                 "`dbutils.fs.ls()`",
                 "`current_file()`",
                 "`DESCRIBE DETAIL`"],
     "answer": 0,
     "explanation": "input_file_name() is deprecated and not available on Unity Catalog; the hidden _metadata column provides file_path, file_name, file_size, file_modification_time…"},
    {"topic": "Querying files",
     "q": "`SELECT * FROM read_files('/Volumes/…/returns', format => 'csv', header => true)` — does the result include `_metadata`?",
     "options": ["Only when pathGlobFilter is set",
                 "No — `_metadata` is hidden and must be selected explicitly",
                 "Only for JSON files",
                 "Yes, always as the first column"],
     "answer": 1,
     "explanation": "_metadata is a hidden column: select it explicitly, e.g. `SELECT *, _metadata.file_name`."},
    {"topic": "Querying files",
     "q": "A JSON source file contains one pretty-printed JSON **array** spanning many lines. Which option is required?",
     "options": ["`recursiveFileLookup => true`",
                 "`header => true`",
                 "`multiLine => true`",
                 "`wholetext => true`"],
     "answer": 2,
     "explanation": "By default JSON is read as JSON Lines (one record per line). multiLine parses records that span lines."},
    {"topic": "Querying files",
     "q": "A folder of CSV exports also contains a `manifest.txt`. How do you make `read_files` read only the CSV files?",
     "options": ["`format => 'csv'` is enough",
                 "`header => true`",
                 "`mode => 'DROPMALFORMED'`",
                 "`pathGlobFilter => '*.csv'`"],
     "answer": 3,
     "explanation": "format tells Spark how to parse, not which files to pick; pathGlobFilter (or fileNamePattern) filters file names."},
    {"topic": "Querying files",
     "q": "What does the `binaryFile` format return?",
     "options": ["One row per file with path, modificationTime, length and content (bytes)",
                 "Only the file names",
                 "The file's text decoded as UTF-8",
                 "One row per line of each file"],
     "answer": 0,
     "explanation": "binaryFile reads whole files as bytes — used for images, PDFs, audio (unstructured data). text returns one row per line in a `value` column."},
    {"topic": "Querying files",
     "q": "A table was created with `CREATE TABLE sales_csv (...) USING CSV OPTIONS (header 'true') LOCATION '...'`. New files were added to the location, but queries don't show them. What should be run?",
     "options": ["`OPTIMIZE sales_csv`",
                 "`REFRESH TABLE sales_csv`",
                 "`MSCK REPAIR TABLE` is the only option",
                 "`VACUUM sales_csv`"],
     "answer": 1,
     "explanation": "Non-Delta external tables can have their file listing cached; REFRESH TABLE invalidates the cache. Delta tables don't need this."},
    {"topic": "Querying files",
     "q": "Which is a limitation of an external table defined `USING CSV` compared with a Delta table?",
     "options": ["It can't have more than 100 columns",
                 "It can't be queried with SQL",
                 "No ACID transactions, time travel or MERGE/UPDATE/DELETE, and slower queries",
                 "It can't be in Unity Catalog at all"],
     "answer": 2,
     "explanation": "CSV/JSON tables are plain files: no transaction log, no time travel, no DML, re-parsed on each read. CTAS them into Delta to get those features."},
    {"topic": "Querying files",
     "q": "Before `read_files` existed, how was a `;`-delimited CSV with a header loaded into a Delta table with CTAS?",
     "options": ["CTAS directly from ``csv.`path` `` with options in the SELECT",
                 "COPY INTO a view",
                 "It was impossible",
                 "Create a temporary view `USING CSV OPTIONS (path …, header 'true', delimiter ';')` with a schema, then CTAS from the view"],
     "answer": 3,
     "explanation": "Direct queries can't take options, so a temp view with the schema and reader options was created first, then CTAS selected from it."},
    {"topic": "Querying files",
     "q": "A legacy workspace has `CREATE TABLE erp_orders USING JDBC OPTIONS (url '...', dbtable 'orders', ...)`. What does querying `erp_orders` do, and what is the Unity Catalog replacement?",
     "options": ["It queries the live external database on each read; replace with Lakehouse Federation (connection + foreign catalog)",
                 "It reads files from DBFS; replace with volumes",
                 "It reads a Delta copy refreshed nightly; replace with COPY INTO",
                 "It streams changes; replace with Auto Loader"],
     "answer": 0,
     "explanation": "A USING JDBC table is a pointer to the external database: no data is copied and every query goes to the source. In UC, Lakehouse Federation exposes external databases through connections and foreign catalogs."},
    # ---------------- COPY INTO ----------------
    {"topic": "COPY INTO",
     "q": "A scheduled `COPY INTO` runs twice; no new files arrived between the runs. What does the second run load?",
     "options": ["All files again",
                 "Nothing — already loaded files are skipped",
                 "Only the most recent file",
                 "It fails"],
     "answer": 1,
     "explanation": "COPY INTO is idempotent: files already loaded into the target table are skipped."},
    {"topic": "COPY INTO",
     "q": "A file that `COPY INTO` already loaded is **overwritten** with corrected data under the same name. With default options, what does the next run do?",
     "options": ["Loads it again, producing both versions",
                 "Fails with a checksum error",
                 "Skips it",
                 "Loads the corrected file and replaces old rows"],
     "answer": 2,
     "explanation": "Files that were loaded are skipped even if they were modified since. Use 'force' = 'true' (into a cleaned table) or fix the rows another way."},
    {"topic": "COPY INTO",
     "q": "What does `COPY_OPTIONS ('force' = 'true')` do?",
     "options": ["Overwrites the table",
                 "Forces schema evolution",
                 "Validates without writing",
                 "Loads all matching files regardless of whether they were loaded before (idempotency disabled)"],
     "answer": 3,
     "explanation": "force disables the load-history check, so re-running can create duplicates. It does not truncate the table."},
    {"topic": "COPY INTO",
     "q": "The source starts sending a new column. Which setting lets `COPY INTO` add it to the target table?",
     "options": ["`COPY_OPTIONS ('mergeSchema' = 'true')`",
                 "`VALIDATE ALL`",
                 "`PATTERN = '*'`",
                 "`FORMAT_OPTIONS ('inferSchema' = 'true')`"],
     "answer": 0,
     "explanation": "COPY_OPTIONS mergeSchema evolves the table schema. FORMAT_OPTIONS mergeSchema merges schemas across the files being read."},
    {"topic": "COPY INTO",
     "q": "Which statement creates a valid target for `COPY INTO` when you want the schema inferred from the files?",
     "options": ["`CREATE VIEW bronze.orders`",
                 "`CREATE TABLE IF NOT EXISTS bronze.orders`",
                 "`CREATE TEMP VIEW orders`",
                 "`CREATE VOLUME bronze.orders`"],
     "answer": 1,
     "explanation": "An empty (schemaless) Delta table plus mergeSchema lets COPY INTO infer and set the schema on the first load. The target must be a Delta table."},
    {"topic": "COPY INTO",
     "q": "You want to check that new files parse correctly and match the table schema **without loading them**. What do you add?",
     "options": ["`DRY RUN`",
                 "`LIMIT 0`",
                 "`VALIDATE ALL` (or `VALIDATE 10 ROWS`)",
                 "`COPY_OPTIONS ('force' = 'false')`"],
     "answer": 2,
     "explanation": "VALIDATE checks parsing, schema and constraints and returns a preview/result without writing data."},
    {"topic": "COPY INTO",
     "q": "Which clause adds the source file name to each row during `COPY INTO`?",
     "options": ["It isn't possible",
                 "`FORMAT_OPTIONS ('input_file_name' = 'true')`",
                 "`COPY_OPTIONS ('addFileName' = 'true')`",
                 "`FROM (SELECT *, _metadata.file_name AS source_file FROM '/Volumes/…/landing')`"],
     "answer": 3,
     "explanation": "COPY INTO accepts a SELECT over the source path, including casts, renames and the _metadata column."},
    {"topic": "COPY INTO",
     "q": "Files arrive continuously — several **million per day** — and their schema changes over time. Which tool is recommended?",
     "options": ["Auto Loader",
                 "COPY INTO",
                 "CTAS from read_files",
                 "File upload UI"],
     "answer": 0,
     "explanation": "Auto Loader scales to millions of files (file notification mode), tracks state in a checkpoint and supports schema evolution and rescued data. COPY INTO suits thousands of files."},
    # ---------------- Semi & unstructured ----------------
    {"topic": "Semi & unstructured",
     "q": "Which **two** statements about the `VARIANT` type are true?",
     "options": ["It can be used as a liquid clustering key",
                 "Values are extracted with paths such as `raw:review.title::string`",
                 "Adding a new JSON field requires ALTER TABLE",
                 "It stores semi-structured data in an efficient binary encoding"],
     "answer": [1, 3],
     "explanation": "VARIANT is binary-encoded and flexible; query it with `:` paths and `::` casts. It can't be a clustering/partition/Z-order key, and new fields need no schema change."},
    {"topic": "Semi & unstructured",
     "q": "How do you load each JSON record of a folder into a single `VARIANT` column `raw` with `COPY INTO`?",
     "options": ["`FORMAT_OPTIONS ('multiLine' = 'raw')`",
                 "`FILEFORMAT = VARIANT`",
                 "`FORMAT_OPTIONS ('singleVariantColumn' = 'raw')`",
                 "`COPY_OPTIONS ('variant' = 'true')`"],
     "answer": 2,
     "explanation": "singleVariantColumn (COPY INTO, Auto Loader) puts the whole record into one VARIANT column."},
    {"topic": "Semi & unstructured",
     "q": "A column `payload` holds JSON **text**. Which function converts it to `VARIANT`, returning NULL instead of failing on malformed JSON?",
     "options": ["`to_json(payload)`",
                 "`from_json(payload)`",
                 "`schema_of_json(payload)`",
                 "`try_parse_json(payload)`"],
     "answer": 3,
     "explanation": "parse_json converts JSON text to VARIANT (error on invalid input); try_parse_json returns NULL instead. from_json converts to a STRUCT with a given schema."},
    {"topic": "Semi & unstructured",
     "q": "Product photos (PNG) must be ingested for an ML team while staying governed by Unity Catalog. Which **two** options fit?",
     "options": ["Load them with `FILEFORMAT = CSV`",
                 "Keep them in the DBFS root /FileStore",
                 "Store the files in a Unity Catalog volume",
                 "Read them with the `binaryFile` format into a Delta table"],
     "answer": [2, 3],
     "explanation": "Volumes govern files of any format; binaryFile turns each file into a row with its bytes. DBFS root is legacy and not governed by UC."},
]

render_quiz(questions, title="Section 05 · Data Ingestion & Loading", pass_mark=0.8,
            meta="37 questions · patterns & Lakeflow Connect, querying files & read_files, COPY INTO, VARIANT & unstructured · target ≥ 80 %")

# COMMAND ----------

# MAGIC %md
# MAGIC ### 📌 If you scored below 80 %
# MAGIC | Weak topic | Review |
# MAGIC |---|---|
# MAGIC | Patterns & connectors | `presentation/05-P1 - Ingestion Patterns and Lakeflow Connect` + `labs/05-L2` Parts 8–9 |
# MAGIC | Querying files | `presentation/05-P2 - Querying Files and read_files` + `labs/05-L1` |
# MAGIC | COPY INTO | `presentation/05-P3` §2–4 + `labs/05-L2` Parts 1–6 |
# MAGIC | Semi & unstructured | `presentation/05-P3` §5–6 + `labs/05-L1` Part 4, `labs/05-L2` Part 7 |

# COMMAND ----------

# DBTITLE 1,Optional - print the answer key
# print_answer_key(questions)
